### ISSUE TITLE
dumpAllFunctionsAsJson gives incorrect result description

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1009]
Gives result desc as Successfully fetched all containers instead of saying functions

**Comment by ligadata-ashish** [comment]
@ligadata-dhaval Could you provide more details around the issue. How, where, when? Please update here before working on fix

**Comment by ligadata-dhaval** [comment]
@ligadata-ashish We are no more supporting user defined functions so might as well close this issue. I have already deprecated the function calls and made a pull request for it.

**Comment by ligadata-dhaval** [comment]
@ligadata-pokuri @ligadata-william  Shall I close this issue as we are not supporting user defined functions?

**Comment by ligadata-dhaval** [comment]
Closing this issue as we do not support user defined functions
