### ISSUE TITLE
PMML should print the input to the log when exceptions happen

### ISSUE THREAD

**Issue by ligadata-rich** [LigaData/Kamanja#1014]
Bill is testing some PMML that is throwing InvalidResultExceptions.  He cannot discern from the current logs which record/msg is causing the problem.

We need to add a try{...}catch{...} around the JpmmlAdapter's evaluateModel(msg : ContainerInterface): ModelResultBase  method's call to :

   val evalResultRaw : MutableMap[FieldName, _] = modelEvaluator.evaluate(preparedFields.asJava).asScala

The prepared fields need to be printed.

**Comment by ligadata-rich** [comment]
Assuming @ligadata-william or @ligadatahari find no issues, this issue is solved.

**Comment by ligadata-william** [comment]
I've tested and merged the fix given here. Closing.
