### ISSUE TITLE
Uploading model in kamanja takes about 5 minutes

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1020]
Every time a model is added to metadata, the jar dependencies are being added with it. This is happening each time whether the jars exist there already or not. This is taking approx. 5 minutes per model, which is far too much time.

Found in branch 1.4.0.Test

**Comment by ligadata-william** [comment]
Giving this to you @ligadata-pokuri. Reassign if this is more appropriate for someone else.

**Comment by ligadata-pokuri** [comment]
Excluding 2.10 & 2.11 built fat jars for now. Can you sync and check.

This check-in has fixes for this:
SHA-1: caf3a0651ff280079a411661bf09c0047aff7434

* Excluding system fat jars from uploading (for now excluding scala 2.10 & scala 2.11 version jars)

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
