### ISSUE TITLE
Array[AMessageType] ingestion at initial load and during zk notification FAILS

### ISSUE THREAD

**Issue by ligadata-rich** [LigaData/Kamanja#1027]
While trying to test the ingestion of AdapterMessageBinding I am seeing an issue in the MetadataAPIImpl.LoadAllObjectsIntoCache() path.  I believe similar issues are found in the zk Update call back path as well.

What happens:

At boot up, this "load all" command issues the following query to the storage adapter in use (in my case this is the cassandra storage adapter): 

     select * from metadata_objects

What is happening is that the list of objects is processing the Array[Msg] before the Msg itself has been updated.  The metadata manager throws an exception when it can't find the Msg type.  Unfortunately, the catch thinks it is a com.ligadata.Exceptions.TypeParsingException but really it is that the NoSuchElementException from the metadata... this needs to be corrected so that it is obvious who is throwing this exception... the fact that it is a NoSuchElement exception needs to be written to the throw message.

In some fashion the BaseMsg instances need to be processed first before the types based upon them (e.g., Array, Map).

I give to Pokuri for now.

**Comment by ligadata-pokuri** [comment]
This is not bug. We are just dumping trace in case if type is trying to resolve without loading messaes. We resolve the same types after msgs loaded

**Comment by ligadata-pokuri** [comment]
Rich, if you verified it, close this issue
