### ISSUE TITLE
Leader selection issues with SmartFileAdapter in a Cluster mode

### ISSUE THREAD

**Issue by ligadata-haitham** [LigaData/Kamanja#1032]
when running Kamanja in Cluster mode, and having SmartFileAdapter added to ClusterConfig.json adapters(along with kafka input adapter), the messages are not being processed. 
there seem to be an issue with leader selection, causing the engine not to call StartProcessing methods in the configured adapters.

logs and ClusterConfig.json are included.

[LeaderSelectionWithSmartFileAdapterLogs.zip](https://github.com/LigaData/Kamanja/files/234496/LeaderSelectionWithSmartFileAdapterLogs.zip)

**Comment by ligadata-pokuri** [comment]
Fixed in 1.4.0. with check-in 8e368f6e0aba20c8a38e87b513154011647a0c1f

**Comment by ligadata-pokuri** [comment]
Verify it once

**Comment by ligadata-yasser** [comment]
verfied
