### ISSUE TITLE
When starting engine for medical sample, output is incorrect

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#1034]
When starting the engine for the medical sample, the output looks incorrect:

bash $KAMANJA_HOME/bin/kamanja start -v

 WARN [main] - DATABASE_SCHEMA remains unset
 WARN [main] - DO_AUTH remains unset
 WARN [main] - MODEL_EXEC_LOG remains unset
 WARN [main] - JAR_TARGET_DIR remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - ZOOKEEPER_CONNECT_STRING remains unset
 WARN [main] - SECURITY_IMPL_CLASS remains unset
 WARN [main] - DATABASE remains unset
 WARN [main] - AUDIT_IMPL_JAR remains unset
 WARN [main] - SECURITY_IMPL_JAR remains unset
 WARN [main] - FUNCTION_FILES_DIR remains unset
 WARN [main] - MESSAGE_FILES_DIR remains unset
 WARN [main] - COMPILER_WORK_DIR remains unset
 WARN [main] - CONTAINER_FILES_DIR remains unset
 WARN [main] - ZNODE_PATH remains unset
 WARN [main] - NOTIFY_ENGINE remains unset
 WARN [main] - DATABASE_HOST remains unset
 WARN [main] - SCALA_HOME remains unset
 WARN [main] - SERVICE_PORT remains unset
 WARN [main] - CLASSPATH remains unset
 WARN [main] - AUDIT_IMPL_CLASS remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - SSL_CERTIFICATE remains unset
 WARN [main] - SERVICE_HOST remains unset
 WARN [main] - CONCEPT_FILES_DIR remains unset
 WARN [main] - DATABASE_LOCATION remains unset
 WARN [main] - JAVA_HOME remains unset
 WARN [main] - MANIFEST_PATH remains unset
 WARN [main] - TYPE_FILES_DIR remains unset
 WARN [main] - MODEL_FILES_DIR remains unset
 WARN [main] - DO_AUDIT remains unset
 WARN [main] - JAR_PATHS remains unset
 WARN [main] - GIT_ROOT remains unset
 WARN [main] - CONFIG_FILES_DIR remains unset
 WARN [main] - ROOT_DIR remains unset
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/alisonapel/Downloads/installKamanja/Kamanja-1.4.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/alisonapel/Downloads/installKamanja/Kamanja-1.4.0_2.11/lib/system/ExtDependencyLibs_2.11-1.4.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
 WARN [main] - failed to join /224.0.75.75:7500 on awdl0: java.net.SocketException: Can't assign requested address

-------------------------------------------------------------------
GMS: address=Dans-MacBook-Pro-65435, cluster=EH_CACHE, physical address=10.1.10.31:7800
-------------------------------------------------------------------
objc[6092]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
 WARN [main] - The configuration request.timeout.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration max.buffer.full.block.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration network.request.timeout.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration max.block.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration request.timeout.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration max.buffer.full.block.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration network.request.timeout.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration max.block.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration request.timeout.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration max.buffer.full.block.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration network.request.timeout.ms = null was supplied but isn't a known config.
 WARN [main] - The configuration max.block.ms = null was supplied but isn't a known config.
 WARN [main] - DistributionCheck:Going to do registerNodesChangeNotification in KamanjaLeader
 WARN [main] - DistributionCheck:registerNodesChangeNotification. Registering as new listener and starting leader
 WARN [main] - DistributionCheck:Done registerNodesChangeNotification in KamanjaLeader
 WARN [main] - KamanjaManager is running now. Waiting for user to terminate with SIGTERM, SIGINT or SIGABRT signals
 WARN [main-EventThread] - DistributionCheck:EnvCtxtEventChangeCallback. Entered from EnvCtxtEventChangeCallback. Got new ClusterStatus. NodeId:1, LeaderNodeId:1, Participents:1, isLeader:false
 WARN [main-EventThread] - DistributionCheck:EnvCtxtEventChangeCallback. Sending ClusterStatus to funcitons. NodeId:1, LeaderNodeId:1, Participents:1, isLeader:false
 WARN [main-EventThread] - DistributionCheck:EventChangeCallback got new ClusterStatus
 WARN [main-EventThread] - SetClusterStatus - Got updatePartitionsFlag. Waiting for distribution
 WARN [main-EventThread] - DistributionCheck:NodeId:1, IsLeader:false, Leader:1, AllParticipents:{1}, participentsChangedCntr:1
 WARN [main-EventThread] - DistributionCheck:EnvCtxtEventChangeCallback. Exiting from EnvCtxtEventChangeCallback. NodeId:1, LeaderNodeId:1, Participents:1, isLeader:false
 WARN [main-EventThread] - DistributionCheck:EnvCtxtEventChangeCallback. Entered from EnvCtxtEventChangeCallback. Got new ClusterStatus. NodeId:1, LeaderNodeId:1, Participents:1, isLeader:true
 WARN [main-EventThread] - DistributionCheck:EnvCtxtEventChangeCallback. Sending ClusterStatus to funcitons. NodeId:1, LeaderNodeId:1, Participents:1, isLeader:true
 WARN [main-EventThread] - DistributionCheck:EventChangeCallback got new ClusterStatus
 WARN [main-EventThread] - SetClusterStatus - Got updatePartitionsFlag. Waiting for distribution
 WARN [main-EventThread] - DistributionCheck:NodeId:1, IsLeader:true, Leader:1, AllParticipents:{1}, participentsChangedCntr:2
 WARN [main-EventThread] - DistributionCheck:EnvCtxtEventChangeCallback. Exiting from EnvCtxtEventChangeCallback. NodeId:1, LeaderNodeId:1, Participents:1, isLeader:true
 WARN [pool-3-thread-1] - DistributionCheck:Found some change. IsLeaderNode:true, GetUpdatePartitionsFlag:true, distributionExecutor.isShutdown:false, lastParticipentChngCntr:0, curParticipentChngCntr:2
 WARN [pool-3-thread-1] - All Participents are {1} up. Going to distribute the work now
 WARN [pool-3-thread-1] - Distribution NodeId:1, IsLeader:true, Leader:1, AllParticipents:{1}
 WARN [Curator-PathChildrenCache-0] - Partition Distribution: {"action":"distribute","adaptermaxpartitions":[{"Adap":"{\"Name\" : \"testin_1\"}","MaxParts":8},{"Adap":"{\"Name\" : \"financeinput\"}","MaxParts":8},{"Adap":"{\"Name\" : \"helloworldinput\"}","MaxParts":8},{"Adap":"{\"Name\" : \"medicalinput\"}","MaxParts":8},{"Adap":"{\"Name\" : \"telecominput\"}","MaxParts":8}],"distributionmap":[{"Node":"1","Adaps":[{"Adap":"{\"Name\" : \"testin_1\"}","Parts":["{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":7}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":6}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":5}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":4}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":3}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":2}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":1}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":0}"]},{"Adap":"{\"Name\" : \"financeinput\"}","Parts":["{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"financeinput\",\"TopicName\":\"financeinput\",\"PartitionId\":7}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"financeinput\",\"TopicName\":\"financeinput\",\"PartitionId\":6}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"financeinput\",\"TopicName\":\"financeinput\",\"PartitionId\":5}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"financeinput\",\"TopicName\":\"financeinput\",\"PartitionId\":4}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"financeinput\",\"TopicName\":\"financeinput\",\"PartitionId\":3}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"financeinput\",\"TopicName\":\"financeinput\",\"PartitionId\":2}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"financeinput\",\"TopicName\":\"financeinput\",\"PartitionId\":1}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"financeinput\",\"TopicName\":\"financeinput\",\"PartitionId\":0}"]},{"Adap":"{\"Name\" : \"helloworldinput\"}","Parts":["{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"helloworldinput\",\"TopicName\":\"helloworldinput\",\"PartitionId\":7}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"helloworldinput\",\"TopicName\":\"helloworldinput\",\"PartitionId\":6}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"helloworldinput\",\"TopicName\":\"helloworldinput\",\"PartitionId\":5}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"helloworldinput\",\"TopicName\":\"helloworldinput\",\"PartitionId\":4}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"helloworldinput\",\"TopicName\":\"helloworldinput\",\"PartitionId\":3}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"helloworldinput\",\"TopicName\":\"helloworldinput\",\"PartitionId\":2}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"helloworldinput\",\"TopicName\":\"helloworldinput\",\"PartitionId\":1}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"helloworldinput\",\"TopicName\":\"helloworldinput\",\"PartitionId\":0}"]},{"Adap":"{\"Name\" : \"medicalinput\"}","Parts":["{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"medicalinput\",\"TopicName\":\"medicalinput\",\"PartitionId\":7}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"medicalinput\",\"TopicName\":\"medicalinput\",\"PartitionId\":6}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"medicalinput\",\"TopicName\":\"medicalinput\",\"PartitionId\":5}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"medicalinput\",\"TopicName\":\"medicalinput\",\"PartitionId\":4}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"medicalinput\",\"TopicName\":\"medicalinput\",\"PartitionId\":3}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"medicalinput\",\"TopicName\":\"medicalinput\",\"PartitionId\":2}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"medicalinput\",\"TopicName\":\"medicalinput\",\"PartitionId\":1}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"medicalinput\",\"TopicName\":\"medicalinput\",\"PartitionId\":0}"]},{"Adap":"{\"Name\" : \"telecominput\"}","Parts":["{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"telecominput\",\"TopicName\":\"telecominput\",\"PartitionId\":7}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"telecominput\",\"TopicName\":\"telecominput\",\"PartitionId\":6}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"telecominput\",\"TopicName\":\"telecominput\",\"PartitionId\":5}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"telecominput\",\"TopicName\":\"telecominput\",\"PartitionId\":4}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"telecominput\",\"TopicName\":\"telecominput\",\"PartitionId\":3}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"telecominput\",\"TopicName\":\"telecominput\",\"PartitionId\":2}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"telecominput\",\"TopicName\":\"telecominput\",\"PartitionId\":1}","{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"telecominput\",\"TopicName\":\"telecominput\",\"PartitionId\":0}"]}]}]}
Executing COPD Risk Assessment against Beneficiary message:
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 000002F7E0A96C32
	Message Desynpuf ID: 00001C24EE7B06AC
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 00001C24EE7B06AC
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 000002F7E0A96C32
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 000002F7E0A96C32
	
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 000002F7E0A96C32
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 00001C24EE7B06AC
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 00001C24EE7B06AC
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 000002F7E0A96C32
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000001.000000
	Message Desynpuf ID: 00001C24EE7B06AC

**Comment by ligadata-pokuri** [comment]
Hi Alison, if this is not issue, can you close it?

**Comment by ligadata-alison** [comment]
Not an issue
