### ISSUE TITLE
MetadataAPI has 2 main

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1035]
Alternate Cmd Parser in MetadataAPI has a main method. Is that required?

**Comment by ligadata-rich** [comment]
It can be left there i think.  The build.sbt for MetadataAPI should have a command to select the other main...

See line 9 of the MetadataAPI's build.sbt... which looks like this:

mainClass in assembly := Some("com.ligadata.MetadataAPI.StartMetadataAPI")

Otoh, if Pokuri wants it eliminated, eliminate it.

**Comment by ligadata-pokuri** [comment]
I don't think we are using Alt. Cmd parser at all. confirm it once. If we are not really use, comment out the whole code.

**Comment by ligadata-pokuri** [comment]
Comment whole code from Alt. Cmd. Parser

**Comment by ligadata-dhaval** [comment]
AlternateCmdParser.scala commented out. Also, commented the method def AltRoute(origArgs: Array[String]) as it is not being used in the StartMetadataAPI.scala

**Comment by ligadata-dhaval** [comment]
I have created a pull request  #1184 for it.

**Comment by ligadata-pokuri** [comment]
@ligadata-dhaval , assign it to yourself and verify it

**Comment by ligadata-william** [comment]
This has been fixed and verified. Closing.
