### ISSUE TITLE
MetadataAPI to return APIResults for all cases

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1036]
Change all response to API result of MetadataAPI.
E.g.
response = "FUNCTION_FILES_DIR property missing in the metadata API configuration"
This should not be a string but an APIResult.

**Comment by ligadata-dhaval** [comment]
Completed the changes and testing it now.

**Comment by ligadata-dhaval** [comment]
Created a pull request #1423

**Comment by ligadata-william** [comment]
If MESSAGE_FILES_DIR is missing, if i run
```
kamanja add message
```
rather than getting an API Result indicating the config parameter is missing, I am asked to choose a tenantId instead. After I select a tenantId I get the error I'm looking for but I should see the error before tenant selection.

**Comment by ligadata-william** [comment]
If I run
```
kamanja add model pmml
```
without MODEL_FILES_DIR specified, I am prompted to choose a tenant, if I choose a tenant, I get 
```
Result: null
```
instead of an API Result. kpmml, scala and java all give an api result.

**Comment by ligadata-dhaval** [comment]
For PMML, the code is not implemented to return any results. In the code it shows to be implemented. I have created an issue for PMML and assigned it to Hari.

**Comment by ligadata-william** [comment]
I'll close this issue then. @ligadata-dhaval, can you comment the issue number?

**Comment by ligadata-dhaval** [comment]
Issue no is #1418 for pmml returning null.
