### ISSUE TITLE
kamanja update container

### ISSUE THREAD

**Issue by ligadata-yousef** [LigaData/Kamanja#1038]
i am trying to update container by this command :

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties update container $KAMANJA_HOME/input/SampleApplications/metadata/container/CoughCodes_Medical.json TENANTID tenant1

but it failed each time with the below result:

Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddContainer/AddMessage",
    "Result Data" : null,
    "Result Description" : "Tenant ID is required to perform an ADD CONTAINER or an ADD MESSAGE operation"
  }
}

**Comment by ligadata-pokuri** [comment]
Hi dan,

can you take a look at it?

**Comment by ligadata-dan** [comment]
@ligadata-yousef @ligadata-pokuri 

Investigating.

**Comment by ligadata-dan** [comment]
@ligadata-yousef 

Please verify

**Comment by ligadata-yousef** [comment]
fixed
