### ISSUE TITLE
TimePartitionInfo not transforming the input data

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1042]
getTimePartitionData() is returning 0 as setTimePartitionData() is not getting called internally.

**Comment by ligadata-tulasi** [comment]
The updates are in branch 1.4.0.Test, please verify.

**Comment by ligadata-dhaval** [comment]
I have removed setPartition and still got the result instead of 0 as earlier.
e.g. result:

History msg description: In God we trust. All others must bring data._5 and date is 1453766400000

**Comment by ligadata-tulasi** [comment]
Assigning to William for verfication

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
