### ISSUE TITLE
purge tool problem

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1043]
Hi ,

truncate is working fine now select return :

Failed to fetch data from the table testdata:com_ligadata_kamanja_samples_containers_smokecodes

Thanks
Saleh

**Comment by ligadata-saleh** [comment]
after testing the tool again its the truncate and delete is working ,  select is working but writing serialized data into the output file @ligadata-yousef  can u take a look please . 

Thanks
Saleh

**Comment by ligadata-yousef** [comment]
@ligadata-saleh  fixed please verify

**Comment by ligadata-saleh** [comment]
verified
