### ISSUE TITLE
Message binding did not work if added while engine is running

### ISSUE THREAD

**Issue by ligadata-yasser** [LigaData/Kamanja#1049]
i tried the following steps:

- set NOTIFY_ENGINE=YES
- added metadata for almost everything (hello world) except adapters binding
- ran engine
- while engine is running, added the adapter binding. but when pushing data into helloworldinput topic, no output
- shut down engine then start again. then push data into: got output

**Comment by ligadata-rich** [comment]
which adapter or adapters did you not add? input? output? or both?

**Comment by ligadata-yasser** [comment]
i did not add binding for the input nor the output first time.

**Comment by ligadata-pokuri** [comment]
fixed

**Comment by ligadata-yasser** [comment]
verified
