### ISSUE TITLE
Execution DAG documentation is insufficient to guide a user in implementing a DAG in Kamanja

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1052]
The documentation found here:
http://kamanja.org/advanced-developers-guide-1-4/architecture-1-4/engine-1-4/#Execution_DAG

explains at a very high level WHAT a DAG is. However, there is no documentation that will introduce a user on HOW to create a DAG using Kamanja. There needs to be a complete, step-by-step guide using a sample application to show the user how to write an application that leverages a DAG in Kamanja.

**Comment by ligadata-krishna** [comment]
There is no need for user to create dag. If a given model depends on other
model's output, system automatically create execution dag in order to
satisfy dependency requirements.

**Comment by ligadata-william** [comment]
Currently, we do not have the ability to have multiple message definitions exist in a single adapter without being explicitly mapped in a JTM. There is no mention of a concept as a JTM, which as I understand it, is key to getting a DAG to run. So either we are feature incomplete, or we are lacking documentation.

**Comment by ligadata-pokuri** [comment]
William,

Can you provide this documentation for Medical sample?

Medical sample has the following messages in the system:
	com.ligadata.kamanja.samples.messages.COPDInputMessage
	com.ligadata.kamanja.samples.messages.COPDOutputMessage
	com.ligadata.kamanja.samples.messages.Beneficiary
	com.ligadata.kamanja.samples.messages.OutpatientClaim
	com.ligadata.kamanja.samples.messages.InpatientClaim
	com.ligadata.kamanja.samples.messages.HL7

And it has the following models:
	1. com.ligadata.kamanja.samples.models.COPDDataIngest, which consumes "com.ligadata.kamanja.samples.messages.COPDInputMessage" message and produce either "com.ligadata.kamanja.samples.messages.Beneficiary" or "com.ligadata.kamanja.samples.messages.OutpatientClaim" or "com.ligadata.kamanja.samples.messages.InpatientClaim" or "com.ligadata.kamanja.samples.messages.HL7"
	2. com.ligadata.kamanja.samples.models.COPDRiskAssessment consumes "com.ligadata.kamanja.samples.messages.Beneficiary" and produce "com.ligadata.kamanja.samples.messages.COPDOutputMessage" or None

And it has the following message bindings:
	1. From Input Adapter "MedicalInput", message "com.ligadata.kamanja.samples.messages.COPDInputMessage" got deserialized with "com.ligadata.kamanja.serializer.csvserdeser"
	2. "com.ligadata.kamanja.samples.messages.COPDOutputMessage" message serialized with "com.ligadata.kamanja.serializer.csvserdeser" and send to output adatper "testout_1"

DAG is in SimpleMedicalSampleDAG.docx

[SimpleMedicalSampleDAG.docx](https://github.com/LigaData/Kamanja/files/239301/SimpleMedicalSampleDAG.docx)

**Comment by ligadata-pokuri** [comment]
Hi william,

I opened a bug not to allow more than one message binding for input adapter. https://github.com/LigaData/Kamanja/issues/1055

**Comment by ligadata-william** [comment]
The concept of this “JTM model” isn’t really a true model and doesn’t properly represent a DAG. Also, this isn’t documentation by which an individual and can walkthrough and gain an understanding of either a DAG or how to produce a JTM. We need an actualy multi-model (not JTM) DAG both to guide a user through and to actually test ourselves. I don’t think this will cut it as, conceptually, the medical model isn’t truly a DAG.

**Comment by ligadata-pokuri** [comment]
you can write another sample and make the documentation for that.

**Comment by ligadata-pokuri** [comment]
William, you have written another sample with documentation. Can you verify this and close?

**Comment by ligadata-william** [comment]
@ligadata-alison, can you send me the link to the documentation so I can
verify it? Or we can go over it together tomorrow.

**Comment by ligadata-alison** [comment]
Here you go:

http://kamanja.org/qs-1-4/run-samples-1-4/

**Comment by ligadata-william** [comment]
The title "Building a Simple Ensemble Model" should be "Building a Simple Model Ensemble". Once that's fixed, I'll close it.

**Comment by ligadata-alison** [comment]
It's fixed - sorry about that!

**Comment by ligadata-william** [comment]
Verified and closing.
