### ISSUE TITLE
Write documentation on what types we support

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#1053]
At this moment we support only ArrayOf<Type>. And We also have Map<String, <type>> but map is not well tested at this moment. Here <type> means it can be base type like Int, Float, Double, Boolean, Long, String or It can be Container Type or Message Type.

**Comment by ligadata-alison** [comment]
Hi Saaim,
     I added a section to:

http://kamanja.org/qs-1-4/prereq-1-4/

and

http://kamanja.org/advanced-developers-guide-1-4/

about the types that the engine supports.

Are these good locations? Are you able to find them during your development?

Please verify.
alison

**Comment by ligadata-rich** [comment]
For collections, there are ArrayOf... and MapOf...

The collection member type can be a container, a message, or one of the scalars.  The ArrayOf<Msg>, ArrayOf<Container>, MapOf<Int or String><Container>, MapO[<Int or String><Container> are built automatically when you add a message or container.  The ArrayOf<scalar> and various Map<scalar or String><scalar or String> are built-in to the system.

While it is possible to add your own type, this is only useful for kpmml models.  The kpmml models are being de-emphasized for now.  This capability will become more important should we dust off the kpmml, extend jtm to support arbitrary functions, or develop additional domain specific languages that can leverage arbitrary types and functions that use them.

Alison, I believe we have documentation about what arrays and maps are generated when a message or container is added to the Metadata.  Could you locate that and we can review what is said there?

**Comment by ligadata-alison** [comment]
After speaking with Rich, we've decided to have a section on types that can be linked from multiple places - prerequisites, sample applications. Salim, can you please verify

**Comment by ligadata-alison** [comment]
I mean Saaim, not Salim!! Sorry!

**Comment by saaimaslam** [comment]
That would work, thanks!

**Comment by ligadata-william** [comment]
@saaimaslam, if you have verified, can you please close this issue?

**Comment by ligadata-william** [comment]
Closing based on Saaim's comment.
