### ISSUE TITLE
ContainersUtility.sh references incorrect version of a jar

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1058]
Not sure why we reference ...1.4.jar  should be 1.0.jar

KAMANJA_HOME/lib/system/containersutility_2.11-1.4.jar

other jars in the .sh file are similarly wrong, although they don't cause a problem.

**Comment by ligadata-pokuri** [comment]
Hi Dan, we should not have any 1.0.jars anymore. all are now have scala version and kamanja version in jars

**Comment by ligadata-pokuri** [comment]
if this is not real issue can you close it?

**Comment by ligadata-dan** [comment]
ok will close

**Comment by ligadata-dan** [comment]
per our discussion, will not close

**Comment by ligadata-pokuri** [comment]
Hi yousef, the jar should be 1.4.0, not 1.0. Rest of the system has 1.4.0 please fix it.
lib/system/containersutility_2.11-1.0.jar

And also make sure you change the script file where it is refered

**Comment by ligadata-yousef** [comment]
@ligadata-dan fixed please verify

**Comment by ligadata-dhaval** [comment]
Verified
