### ISSUE TITLE
--serializer is not supported, yet documentation mentions it.

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1059]
ERROR [main] - Unknown option --serializer

the doc says that 

--serializer <package>	This is the package that is used to serialize and deserializer data. Mandatory for select operation.

**Comment by ligadata-pokuri** [comment]
yes for get operation --serializer will come by tomorrow morning of PST

**Comment by ligadata-yousef** [comment]
fixed, it is now supported.

**Comment by ligadata-dhaval** [comment]
verified.
