### ISSUE TITLE
Purge tool ContainerUtils filter & tenantId issue

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1060]
1. If filter.json is missing, it gives the error as below:

Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at scala.io.Source$.fromFile(Source.scala:54)
	at com.ligadata.tools.containersutility.ContainersUtility$.main(ContainersUtility.scala:106)
	at com.ligadata.tools.containersutility.ContainersUtility.main(ContainersUtility.scala)

It does not handle the no file condition.

2. I created an empty filter.json and ran it, it gave me the below error:

ERROR [main] - Node 1 not found in metadata
ERROR [main] - Not found tenantInfo for tenantId

**Comment by ligadata-yousef** [comment]
@ligadata-dhaval  
first note fixed and for second note make sure you are upload cluster config before using tool because you should have at least one tenantid on machine

please verify

**Comment by ligadata-dhaval** [comment]
If version of container given, it still gives the error:

ERROR [main] - Not found valid type for com.ligadata.kamanja.samples.containers.accountaggregatedusage.000000000001000000
ERROR [main] - Not found tenantInfo for tenantId

Can we have some APIResult mentioning the above error?

**Comment by ligadata-dan** [comment]
@ligadata-dhaval @ligadata-yousef 

This is more of a doc issue,  this works without version in the TYPE...  We need to make sure the doc reflects that clearly
