### ISSUE TITLE
Container Utilities returns an ERROR message is nothing is found on select

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1062]
ERROR [main] - no data retrieved

This is the return of the SELECT call if there are no containers in the storage.  Don't think that should be an error, and the message is very ambiguous.  I had no idea that it was actual result.  I would add something like "no data retrieved for specified containers"

**Comment by ligadata-yousef** [comment]
now you can see after select data from container with no result:

warn - 0 rows fetched successfully.

**Comment by ligadata-dhaval** [comment]
Closing as it similar to 1074
