### ISSUE TITLE
kamanja stop does not stop kamanja manager 

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1063]
We still see the kamanja manager riunning after executing kamanja stop command. Here is the screenshot 
________________________________________________________________________________

Haris-MacBook-Pro:bin hariramasamy$ jps
62434 
68452 KamanjaManager
71476 Jps
67958 Kafka
67903 QuorumPeerMain
Haris-MacBook-Pro:bin hariramasamy$ kamanja stop
Stopping Kamanja with process id: 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Kamanja successfully stopped
Haris-MacBook-Pro:bin hariramasamy$ jps
71505 Jps
62434 
68452 KamanjaManager
67958 Kafka
67903 QuorumPeerMain
Haris-MacBook-Pro:bin hariramasamy$

**Comment by ligadata-pokuri** [comment]
Fixed in 1.4.0.Test branch & check-in SHA-1: 54521fb7b88263130883b941c35893ff06cbd443

**Comment by ligadata-pokuri** [comment]
Verified by @ligadatahari & @ligadata-dan
