### ISSUE TITLE
adding TenantID to smart adapter json 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1064]
Hi , 
   according to the json i receive i cant see tenantid field . 

Thanks
Saleh

**Comment by ligadata-yasser** [comment]
@ligadata-pokuri 
Alison changed the file adapter samples to have tenant id. 
should the adapter check for it while validating the config, or would that be done on a higher level?

**Comment by ligadata-pokuri** [comment]
Hi yasser,

While uploading configuration, that need to validate for TenantId.

**Comment by ligadata-pokuri** [comment]
Hi dan, can you make sure we validate tenantid exists before save uploaded configuration

**Comment by ligadata-pokuri** [comment]
Make sure Name, TypeString & TenantId are must for adapters

**Comment by ligadata-pokuri** [comment]
Yasser, can you verify whether adapter is enforcing for Name, TypeString & TenantId or not?

**Comment by ligadata-yasser** [comment]
Verified
