### ISSUE TITLE
Kamanja Status Event using JsonSerDeser has an invalid json format

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1066]
When printed out in json format, the format is incorrect:
```
{
	"@@SchemaId": 1000001,
	"statustype": "PD",
	"nodeid": "1",
	"eventtime": 2016 - 04 - 28 13: 34: 32.990 PDT,
	"statusstring": "Output\/testfailedevents_1\/evtCnt->0~Output\/teststatus_1\/evtCnt->181~Output\/testout_1\/evtCnt->0~Input\/financeinput\/evtCnt->0~Input\/testin_1\/evtCnt->1~Input\/telecominput\/evtCnt->0~Input\/helloworldinput\/evtCnt->0~Input\/medicalinput\/evtCnt->0~Storage\/Storage_1\/evtCnt->(0:0)"
}
```
Specifically, "eventtime" needs quotations around the value.

There are also several \/ that make it difficult to read in statusstring, which would be better served as another json map instead of a straight string (not a bad format but really tough on the eyes).

**Comment by ligadata-pokuri** [comment]
Dan,

Can you fix the message proeprly?

**Comment by ligadata-krishna** [comment]
All the times should be in YYYY-MM-DD HH:mm:ss.ms format for easy parsing by consumers (probably convert to GMT time)

 

Thanks

-Krishna

**Comment by ligadata-pokuri** [comment]
william reported it. We can assign it to him. 

Krishna we are printing TimeZone also. Sometimes GMT may be difficult to correlate.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
