### ISSUE TITLE
adapter message binding change requires restart of kamanja to be picked by output queue

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1070]
Steps to reproduce

1. start zookeeper, kafka, hbase 
1.a. jps - make sure zookeepr, kafka, hbase are running
2. kamanja upload cluster config $KAMANJA_HOME/config/Clusterconfig.json 
2.a.   you should see loaded successfully. 
3. kamanja start
3.a jps - check kamanja manger is running
4. cd $KAMANJA_HOME/input/SampleApplication/bin
4.a  ./HelloWorldApp.sh
5. ./PushSampleDataToKafka_HelloWorld.sh
5.a. kamanja watch status queue - make sure input and output message counts shows correct value
5.b kamanja watch output queue - output will show two lines stating count of procesed
6. kamanja list adaptermessagebindings 
6.a kamanja remove adaptermessagebinding KEY "testout_1,com.ligadata.kamanja.samples.messages.outmsg1,com.ligadata.kamanja.serializer.csvserdeser"
7. add new adapter to cluster config connected to different topic queue. as given below 
     {
          "Name": "TestOut_2",
          "TypeString": "Output",
          "TenantId": "tenant1",
          "ClassName": "com.ligadata.OutputAdapters.KafkaProducer$",
          "JarName": "KamanjaInternalDeps_2.11-1.4.0.jar",
          "DependencyJars": [
            "ExtDependencyLibs_2.11-1.4.0.jar",
            "ExtDependencyLibs2_2.11-1.4.0.jar"
          ],
          "AdapterSpecificCfg": {
            "HostList": "localhost:9092",
            "TopicName": "testout_2"
          }
        },

8. kamanja upload cluster config $KAMANJA_HOME/config/ClusterConfig.json
9.  kamanja add adaptermessagebinding FROMSTRING '  {
    "AdapterName": "testout_2",
    "MessageNames": [
      "com.ligadata.kamanja.samples.messages.outmsg1"
    ],
    "Serializer": "com.ligadata.kamanja.serializer.csvserdeser",
    "Options": {
      "alwaysQuoteFields": false,
      "fieldDelimiter": ","
    }
  }'

10, Repeat step 5
11, $KAFKA_HOME/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic testout_2 --from-beginning  - no message will show up.
12. Restart kamanja and repeat step 5.
13. $KAFKA_HOME/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic testout_2 --from-beginning  - and the message will show up

**Comment by ligadata-rich** [comment]
This bug is similar to the #1047 

I used cassandra for that one and am not able to repro. 

Question: when the adapter message binding removed and readded, was the metadata api configuration properities configured with NOTIFY_ENGINE=YES ?

**Comment by ligadata-pokuri** [comment]
Rich, Why is it similar to 1047? The next question is valid, but I don't think this is similar to 1047. If he does not have NOTIFY_ENGINE=YES, that is very valid question.

**Comment by ligadata-pokuri** [comment]
Hari, Provide the contents for MetadataAPIConfig.properties here?

**Comment by ligadata-pokuri** [comment]
Fixed this issue in 1.4.0.Test with check-in aa2c8395cb0bf85f836f6a3c3be9fdfdf8abd768

**Comment by ligadatahari** [comment]
The bug appears to be fixed.
