### ISSUE TITLE
No option to do equivalent of "SELECT *" from the CONTAINER stores.

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1072]
The only way I can think of doing it now is to specify a very large time range.  

If that is a desired behavior, then we should document it.

**Comment by ligadata-yousef** [comment]
till now the timerange is begintime = 0 and endtime = 0 because all data saved in container with this timerange. 
another option is to keep begintime and endtime without value.

**Comment by ligadata-yousef** [comment]
you can now SELECT * from container using the below format in filter file:

[
   {
    "begintime": "-1",
    "endtime": "-1"
   }
]

**Comment by ligadata-dhaval** [comment]
Testing dependent on 1074

**Comment by ligadata-dan** [comment]
@ligadata-yousef 

Ok, can you make sure Alison has this info?

**Comment by ligadata-yousef** [comment]
@ligadata-dan 

it is case 4 in testing select from container.

**Comment by ligadata-dhaval** [comment]
verified.
