### ISSUE TITLE
CONTAINERUTILITY:  Delete results are missing

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1074]
When I do 

./ContainersUtility.sh --containername com.ligadata.kamanja.samples.containers.envcodes --config ~/kamanja13/Kamanja-1.4.0_2.11/config/MetadataAPIConfig.properties --operation delete --filter /tmp/blah1

I don't see anything telling as to the result of the operation.  

I would suggest at the minute a message along this lines:

ContainerUtility removed 49 rows

Or something.

**Comment by ligadata-yousef** [comment]
till now i don't know how we can find the number of rows that deleted because storage adapter does not return this information when you pass keys and/or timeranges to delete. so i add warn to tell you the data deleted successfully after use delete operation. 

note: this a temporary solution till we find a way to count number of deleted rows.

**Comment by ligadata-dhaval** [comment]
I get the results as:
WARN [main] - The data deleted successfully. It is coming as a warning instead of output
I dont get the location of the output file result. I checked /tmp/kamanja and no file is created.
I think if we could get more information of what is deleted, it would be helpful.

**Comment by ligadata-yousef** [comment]
there is no output file for delete data, it just remove data from container. and we cannot get an information of deleted data because storage adapter does not  give that information.

**Comment by ligadata-pokuri** [comment]
Dhaval, We don't want to output all the data deleted at this moment. I don't know whether it is practical and any other tools will do that. As far as I know no databases or tools will dump all deleted rows (may be I am looking at db tools).

**Comment by ligadata-pokuri** [comment]
Yousef, can you also do println() same string what ever you are doing WARN. And move WARN to INFO

**Comment by ligadata-dhaval** [comment]
ok Pokuri. @ligadata-yousef Can we remove the  --outputpath /tmp/kamanja for delete in the documentation?

**Comment by ligadata-pokuri** [comment]
Yes we don't need output file for delete

**Comment by ligadata-yousef** [comment]
if i move WARN to INFO we should change logger level in log4j2.xml from WARN to INFO and in this case we will see a lot of info lines for all process in Kamanja in addition to a lot of INFO lines for ContainerUtility tool.

if you want i can do that.

**Comment by ligadata-pokuri** [comment]
yousef, that's why we are asking you to do println also. That will give on console

**Comment by ligadata-pokuri** [comment]
Just status information

**Comment by ligadata-alison** [comment]
Hi Yousef,
     Please let me know of any documentation updates - as you have been
doing. :)
thanks,
alison

**Comment by ligadata-yousef** [comment]
@ligadata-dan 

fixed

**Comment by ligadata-dhaval** [comment]
Verified the implementation.

**Comment by ligadata-dhaval** [comment]
@ligadata-alison Kindly could you update the documentation. The delete command should not have  --outputpath /tmp/kamanja option.

**Comment by ligadata-alison** [comment]
Hi Dhaval,
     Do you mean that I should remove --outputpath /tmp/kamanja from the
command? Or do I add a note that when you select the delete operation, you
cannot use the --outputpath option?
thanks,
alison

**Comment by ligadata-alison** [comment]
Hi Pokuri,
     Should I remove --outputpath /tmp/kamanja from the command? Or do I
add a note that when you select the delete operation, you cannot use the
--outputpath option?
thanks,
alison

**Comment by ligadata-yousef** [comment]
Hi Alison,

- in EXAMPLES section  note 1 testing truncate from container remove  "--outputpath /tmp/kamanja" from command.

- in EXAMPLES section  note 2 testing delete from container remove  "--outputpath /tmp/kamanja" from command.

- in EXAMPLES section change all "WARN [main]" to "[RESULT]"

Thanks
 Yousef

**Comment by ligadata-alison** [comment]
thanks!

**Comment by ligadata-alison** [comment]
Closing

**Comment by ligadata-alison** [comment]
Fixed and closing
