### ISSUE TITLE
Kamanja watch input queue doesnt show the right queue

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1075]
The KamanjaWatchInputQueue is pointing to testin_1 when it should be pointing to helloworld, medical , finance inputs OR we should have a documentation on it.

**Comment by ligadata-pokuri** [comment]
Added more scripts

Now you will see the following 4 script in bin folder to read input queues
WatchFinanceQueue.sh 
WatchHelloWorldQueue.sh
WatchMedicalQueue.sh
WatchTelecomQueue.sh

**Comment by ligadata-dhaval** [comment]
Verified
