### ISSUE TITLE
When adding a new message def got warning regarding unreachable code

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1078]
/private/tmp/Kamanja/Kamanja-1.4.0_2.11/workingdir/NumberMessage/NumberMessage.scala:68: warning: unreachable code
      case oldVerobj: com.ligadata.automation.test.dag.V1000000.NumberMessage => { return  convertToVer1000000(newVerObj.asInstanceOf[com.ligadata.automation.test.dag.V1000000.NumberMessage], oldVerobj.asInstanceOf[com.ligadata.automation.test.dag.V1000000.NumberMessage]); }

**Comment by ligadata-william** [comment]
[NumberMessage.scala.txt](https://github.com/LigaData/Kamanja/files/243322/NumberMessage.scala.txt)

**Comment by ligadata-william** [comment]
After talking to @ligadata-tulasi and taking a look, it looks like this only occurs when preceding the failure to add due to a message already existing by that name and that version. Closing as not a bug.

**Comment by ligadata-tulasi** [comment]
This particular piece of code gets generated when the same message already exists in metadata, Message already exists error should  also come along with this...
