### ISSUE TITLE
Remove binding that produced results; add binding new ser format to different adapter same msg

### ISSUE THREAD

**Issue by ligadata-rich** [LigaData/Kamanja#1080]
*Scenario:*

An output adapter message binding has been configured for csv on adapter "TestOut_1".  The customer has changed his mind, desiring json serialization. To fix, it is decided to use an unused adapter, "TestOut_2" with a new kafka topic "testout_2".

*Problem:*

The initial configuration produces data in csv.  The change is made to json and bound to the unused adapter.  Nothing is produced on subsequent data pushes.

**Steps to reproduce**

1.  start zookeeper, kafka, hbase (or cassandra), set variables, and _build config files with cassandra references.  Change parameter the storeType value to hbase if desired._

export KAMANJA_HOME=/tmp/drdigital/Kamanja-1.4.0_2.11
export KAMANJA_SRCDIR=~/github/dev/1.4.0.Base/kamanja/trunk
export TestBin=$KAMANJA_SRCDIR/MetadataAPI/src/test/resources/bin
export MetadataDir=$KAMANJA_SRCDIR/MetadataAPI/src/test/resources/Metadata
export apiConfigProperties=$KAMANJA_HOME/config/MetadataAPIConfig.properties

_Configure the cluster configuration json file with cassandra storage values... **NOTE: THE CURRENT ClusterConfig.json is overwritten**_

    setPathsFor.scala --installDir $KAMANJA_HOME --templateFile $MetadataDir/templates/ClusterConfig.1.4.0_Template.json --scalaHome $SCALA_HOME --javaHome $JAVA_HOME --storeType cassandra --schemaName testdata --schemaLocation localhost > $KAMANJA_HOME/config/ClusterConfig.json

_Configure the metadata api config file to use... cassandra in this case.  **NOTE: THE CURRENT MetadataAPIConfig.properties is overwritten**_

    setPathsFor.scala --installDir $KAMANJA_HOME --templateFile $MetadataDir/templates/Cassandra_MetadataAPIConfig_Template.properties --scalaHome $SCALA_HOME --javaHome $JAVA_HOME --storeType cassandra --schemaName metadata --schemaLocation localhost > $KAMANJA_HOME/config/MetadataAPIConfig.properties

_Configure the engine config file to use.  In this case, the cassandra values are used. **NOTE: THE CURRENT Engine1Config.properties is overwritten**_

    setPathsFor.scala --installDir $KAMANJA_HOME --templateFile $MetadataDir/templates/Engine1Config_Template.properties --scalaHome $SCALA_HOME --javaHome $JAVA_HOME --storeType cassandra --schemaName metadata --schemaLocation localhost > $KAMANJA_HOME/config/Engine1Config.properties

2. cluster config modifications
  a. add new output adapter below to the generated cluster config from prior step :
    
    {
      "Name": "TestOut_2",
      "TypeString": "Output",
      "TenantId": "tenant1",
      "ClassName": "com.ligadata.OutputAdapters.KafkaProducer$",
      "JarName": "KamanjaInternalDeps_2.11-1.4.0.jar",
      "DependencyJars": [
        "ExtDependencyLibs_2.11-1.4.0.jar",
        "ExtDependencyLibs2_2.11-1.4.0.jar"
      ],
      "AdapterSpecificCfg": {
        "HostList": "localhost:9092",
        "TopicName": "testout_2"
      }
    }, 

  b. Set the NOTIFY_ENGINE=YES in $KAMANJA_HOME/config/MetadataAPIConfig.properties

  c. initialize cluster configuration

    $KAMANJA_HOME/bin/kamanja $apiConfigProperties upload cluster config $KAMANJA_HOME/config/ClusterConfig.json 

3. Start the engine in another console

    $KAMANJA_HOME/bin/kamanja start -v

4. Check kamanja manger, kafka, zk, and db are running

    jps

5. Install standard Helloworld metadata

    $KAMANJA_HOME/input/SampleApplications/bin/HelloWorldApp.sh
    
6. List the adapter message configurations if desired

    $KAMANJA_HOME/bin/kamanja $apiConfigProperties list adaptermessagebindings

7. Start the WatchOutputQueue in another console window.

    $KAMANJA_HOME/bin/WatchOutputQueue.sh

8. Push the hello world data

    $KAMANJA_HOME/input/SampleApplications/bin/PushSampleDataToKafka_HelloWorld.sh 

    Expectation: data in the WatchOutputQueue window (2 lines)

    This data was processed by testout_1 adapter.

9. Remove the old binding for outmsg1 on testout_1

    $KAMANJA_HOME/bin/kamanja $apiConfigProperties remove adaptermessagebinding KEY "testout_1,com.ligadata.kamanja.samples.messages.outmsg1,com.ligadata.kamanja.serializer.csvserdeser"

10. Create a new binding for "outmsg1" on the second (_unused_) adapter, "TestOut_2"  that was added in step 1 above.  This time generate json.

    $KAMANJA_HOME/bin/kamanja $apiConfigProperties add adaptermessagebinding FROMSTRING ' { "AdapterName": "TestOut_2", "MessageNames": [ "com.ligadata.kamanja.samples.messages.outmsg1" ], "Serializer": "com.ligadata.kamanja.serializer.JsonSerDeser" }'

11. Push the hello world data again.

    $KAMANJA_HOME/input/SampleApplications/bin/PushSampleDataToKafka_HelloWorld.sh 

    Expectation: data in the WatchOutputQueue window (2 lines) formatted in json

    Actual: No data

**Comment by ligadata-rich** [comment]
checking the kafka queue testout_2 shows model produced results and left in queue.

$KAFKA_HOME/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic testout_2 --from-beginning - and the message will show up
{ "@@SchemaId": 2000002, "id": 1,"name": "World" }
{ "@@SchemaId": 2000002, "id": 50,"name": "Hello" }
{ "@@SchemaId": 2000002, "id": 1,"name": "World" }
{ "@@SchemaId": 2000002, "id": 50,"name": "Hello" }

(I ran the "push" twice... hence two sets of results)

**Comment by ligadata-rich** [comment]
I see this in the engine log:

ERROR [pool-25-thread-1] - Did not find/load Serializer for container/message:com.ligadata.kamanja.samples.messages.outmsg1 @Adapter:testout_1
ERROR [pool-25-thread-1] - testout_1 KAFKA PRODUCER: Messages, messages serialized data & serializer names should has same number of elements. Messages:1, Messages Serialized data:0, serializerNames:0
ERROR [pool-25-thread-1] - Failed to commit data for executed message : com.ligadata.kamanja.samples.messages.msg1
java.lang.Exception: testout_1 KAFKA PRODUCER: Messages, messages serialized data & serializer names should has same number of elements. Messages:1, Messages Serialized data:0, serializerNames:0
        at com.ligadata.OutputAdapters.KafkaProducer.send(KafkaProducer.scala:370) ~[KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.KamanjaManager.ExecContextImpl$$anonfun$commitData$3.apply(ExecContext.scala:178) ~[kamanjamanager_2.11-1.4.0.jar:1.4.0]
        at com.ligadata.KamanjaManager.ExecContextImpl$$anonfun$commitData$3.apply(ExecContext.scala:167) ~[kamanjamanager_2.11-1.4.0.jar:1.4.0]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[ExtDependencyLibs2_2.11-1.4.0.jar:1.0]
        at com.ligadata.KamanjaManager.ExecContextImpl.commitData(ExecContext.scala:167) ~[kamanjamanager_2.11-1.4.0.jar:1.4.0]
        at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:273) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:41) [kamanjamanager_2.11-1.4.0.jar:1.4.0]
        at com.ligadata.InputOutputAdapterInfo.ExecContext$class.execute(InputOutputAdapterInfo.scala:311) [KamanjaInternalDeps_2.11-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.KamanjaManager.ExecContextImpl.execute(ExecContext.scala:41) [kamanjamanager_2.11-1.4.0.jar:1.4.0]
        at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(KafkaSimpleConsumer.scala:408
.
.
.

**Comment by ligadata-pokuri** [comment]
Fixed couple of issues. Please check it with latest check-in 17c537da6b6705f18bd937a647fa86c170932c10

**Comment by ligadata-rich** [comment]
This now works.
