### ISSUE TITLE
model not migrated when upgrading from 133 to 140

### ISSUE THREAD

**Issue by ligadata-haitham** [LigaData/Kamanja#1081]
after upgrading from kamanja 133 to 140 , i was able to see messages and containers in metadata, but the Medical model did not get migrated.
i tried the upgrade 3 times with the same result : 

[root@localhost ClusterInstall]# kamanja get all models
Result: Sorry, No models available in the Metadata

... also, i noticed that in hbase has the schema "statusinfo" , i did not delete or empty that schema from previous run ( upgrade 122 to 140) , so that might be related to the issue.

Note : in all upgrade processes i used different schema names for ell config files, like : kamanja & kamanja2 & kamanja3 for upgrade 113 & 122 & 133 respectively.
if someone else found had the same thing maybe its an issue.
upgrade log is attached.
[KamanjaLog.zip](https://github.com/LigaData/Kamanja/files/243779/KamanjaLog.zip)

**Comment by ligadata-pokuri** [comment]
Hi Haitham,

Medical model is Java model or scala model or kPMML model?

**Comment by ligadata-haitham** [comment]
2016-04-28 08:29:26,460 - com.ligadata.Utils.Utils$ [pool-6-thread-1] - ERROR - Jar heartbeat_2.10-0.1.0.jar not found 
2016-04-28 08:29:26,468 - com.ligadata.Utils.KamanjaClassLoader [pool-6-thread-1] - DEBUG - Trying to load class:com.ligadata.kamanja.samples.models.V1.COPDRiskAssessment, resolve:false 
2016-04-28 08:29:26,471 - com.ligadata.MetadataAPI.CompilerProxy [pool-6-thread-1] - ERROR - Failed to load Model class com.ligadata.kamanja.samples.models.V1.COPDRiskAssessment 
java.lang.ClassNotFoundException: com.ligadata.kamanja.samples.models.V1.COPDRiskAssessment

**Comment by ligadata-pokuri** [comment]
Raman, can we get all the jars from 1.1/1.2/1.3 and exclude them (both 2.10 & 2.11 versions)?

**Comment by ligadata-pokuri** [comment]
Hi haitham, can you check them and update the issue

**Comment by ligadata-ramana** [comment]
Haitham, Please check with latest code. I am able to migrate 133_2_10 to 140_2_11  after the fix.

**Comment by ligadata-haitham** [comment]
Issue no longer exists.
i am able to migrate 133_210 to 140_210 and see output at the output queue.

**Comment by ligadata-pokuri** [comment]
Hi haitham, close this issue, if it already fixed
