### ISSUE TITLE
smart input adapter is not reading the file from the target folder 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1083]
Hi , 
  smart input adapter is not reading the file from the target folder am using this configuration : 

 {
  "Name": "TestSmartInput_1",
  "TypeString": "Input",
  "ClassName": "com.ligadata.InputAdapters.SmartFileConsumer$",
  "JarName": "KamanjaInternalDeps_2.11-1.4.0.jar",
  "DependencyJars": [
    "ExtDependencyLibs_2.11-1.4.0.jar",
	"ExtDependencyLibs2_2.11-1.4.0.jar"
  ],
  "AdapterSpecificCfg": {
    "Type": "DAS/NAS",
    "ConnectionConfig": {
    },
    "MonitoringConfig": {
	 "Locations": "/data/input",
	 "TargetMoveDir": "/data/processed",
      "MaxTimeWait": "10000",
	 "MessageSeparator":"10",
	 "WorkerBufferSize":"4",
	 "ConsumersCount":"1"
	}
  }
}

and for the message binding

[
 {
    "AdapterName": "TestSmartInput_1",
    "MessageName": "com.ligadata.kamanja.samples.messages.msg1",
    "Serializer": "com.ligadata.kamanja.serializer.csvserdeser",
    "Options": {
      "produceHeader": true,
      "alwaysQuoteFields": false,
      "fieldDelimiter": ","
    }
  },
  {
    "AdapterName": "testout_1",
    "MessageNames": [
      "com.ligadata.kamanja.samples.messages.outmsg1"
    ],
    "Serializer": "com.ligadata.kamanja.serializer.csvserdeser",
    "Options": {
      "alwaysQuoteFields": false,
      "fieldDelimiter": ","
    }
  }
]

Thanks
Saleh

**Comment by ligadata-yasser** [comment]
@ligadata-saleh 
please verfiy

**Comment by ligadata-saleh** [comment]
verified
