### ISSUE TITLE
Save Cache, SystemCatalog, EnvironmentContext, ZooKeeperInfo, etc  as separate keys in Datastore from Clusterconfig 

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#1084]
Save Cache, SystemCatalog, EnvironmentContext, ZooKeeperInfo, etc  as separate keys in Datastore from Clusterconfig. Otherwise when we add extra adapters without these information it is clearing all these keys.

Also check whether user properties saving them properly or not. At any cost we should not lose configuration while adding incremental configuration.

And while removing we should remove incremental without loosing any other information.

**Comment by ligadata-pokuri** [comment]
original upload cluster config ...

**Comment by ligadatahari** [comment]
It appears fixed.
