### ISSUE TITLE
Remove multiple Adapter message bindings

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#1085]
Hi Rich,

We need to allow users to remove multiple Adapter message bindings.

One of the option is take the same file what we used to add bindings to remove the same. And another option is just consider another file with full binding names.

**Comment by ligadata-rich** [comment]
Maybe we can just supply a json array either on the command line or by file.

**Comment by ligadata-rich** [comment]
_**For example, this array contains four binding keys in it:**_

[
  "kafkaAdapterInput1,com.botanical.json.ordermsg,com.ligadata.kamanja.serializer.JsonSerDeser",
  "kafkaAdapterInput1,com.botanical.json.shippingmsg,com.ligadata.kamanja.serializer.JsonSerDeser",
  "hBaseStore1,com.botanical.json.audit.ordermsg,com.ligadata.kamanja.serializer.JsonSerDeser",
  "hBaseStore1,com.botanical.json.audit.shippingmsg,com.ligadata.kamanja.serializer.JsonSerDeser"
]

_**The from string command:**_

$KAMANJA_HOME/bin/kamanja $apiConfigProperties remove adaptermessagebinding FROMSTRING '["kafkaAdapterInput1,com.botanical.json.ordermsg,com.ligadata.kamanja.serializer.JsonSerDeser", "kafkaAdapterInput1,com.botanical.json.shippingmsg,com.ligadata.kamanja.serializer.JsonSerDeser", "hBaseStore1,com.botanical.json.audit.ordermsg,com.ligadata.kamanja.serializer.JsonSerDeser", "hBaseStore1,com.botanical.json.audit.shippingmsg,com.ligadata.kamanja.serializer.JsonSerDeser"]'

_**The from file command:**_

$KAMANJA_HOME/bin/kamanja $apiConfigProperties remove adaptermessagebinding FROMFILE someFile.path.that.contains.the.array.above.json'

**Comment by ligadata-pokuri** [comment]
ok We can implement these

**Comment by ligadata-pokuri** [comment]
this is one of the test command

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties remove adaptermessagebinding FROMSTRING '["HelloWorldInput,com.ligadata.kamanja.samples.messages.msg1,com.ligadata.kamanja.serializer.csvserdeser", "TestOut_1,com.ligadata.kamanja.samples.messages.outmsg1,com.ligadata.kamanja.serializer.csvserdeser"]'

**Comment by ligadata-yasser** [comment]
Verified both FROMSTRING  and FROMFILE commands
