### ISSUE TITLE
update jtm on COPDDataIngest give helloworldmessage update error

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1090]
I am getting the following when i am updating the jtm model .(Probllem attached() that contains debug output is attached)   Steps to reproduce 

1) Start pre kamanja servers -Zookeeper, Kafka, hbase
2) kamanja upload cluster config $KAMANJA_HOME/config/ClusterConfig.json
3) kamanja start
4) Run  $KAMANJA_HOME/input/SampleApplication/bin/MedicalApp.sh 
5) Run  $KAMANJA_HOME/input/SampleApplication/bin/InitKvStores_Medical.sh
5) Run  $KAMANJA_HOME/input/SampleApplication/bin/PushSampleDataToKafka_Medical.sh
6) change hwlloworldmessage  transform to copddataingestmessage
7) kamanja update model jtm  and select the COPDIngest Model 
8) You will see the error 
INFO [main] - metadatacounters, isMetadata => true
 INFO [main] - metadatacounters, isMetadata => true
DEBUG [main] - model found => com.ligadata.kamanja.samples.models.copddataingest.000000000000000001
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "UpdateModel(type = JTM)",
    "Result Data" : null,
    "Result Description" : "Failed to Update Model. Invalid Version.:com.ligadata.kamanja.samples.models.COPDDataIngest.000000000000000001"
  }
}

**Comment by ligadata-pokuri** [comment]
Some how we made "Failed to Update Model. Invalid Version." for Upgrading the component and "Failed to Add Model. Model with higher version required than any previous version including removed models" for add with lesser and same version in the system.
