### ISSUE TITLE
kamanja dump all cfg objects doesn't display "Tenants" configuration

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1093]
When I add Tenants to my cluster config and I run the command
```
bash kamanja dump all cfg objects
```

The "Tenants" section is not displayed.

**Comment by ligadata-pokuri** [comment]
Without this information we can not see what are the tenants available in the configuration.

**Comment by ligadata-dan** [comment]
@ligadata-william 
Ok, as I said, we did not implement the getting a tenant from the database into the tenant object to be returned to the user.  The Tenant Info is correctly stored.  Please verify that it is being correctly returned

**Comment by ligadata-william** [comment]
Verified and closing.
