### ISSUE TITLE
Get ElementId for Models

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#1095]
Get ElementId for Models in Get function(s)

**Comment by ligadata-dan** [comment]
@ligadata-pokuri 

Models should to show ElementID

**Comment by ligadatahari** [comment]
- kamanja update fails on KPMML Model 
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "UpdateModel(type = KPMML)",
    "Result Data" : null,
    "Result Description" : "Failed to Update Model. Model with higher version required than any previous version including removed models:system.helloworld.000001000005000002"
  }
}


-  kamanja update model java does not keep element ID constant


-   kamanja update model scala does not keep element ID constant


- pmml model update fails

Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "UpdateModel(type = PMML)",
    "Result Data" : null,
    "Result Description" : "The model name and new version was not supplied for this PMML model : name= version=null\nOptionally one should consider supplying the exact version of the model being updated, especially important when you are maintaining multiple versions with the same model name and tweaking versions of same for your 'a/b/c...' score comparisons."
  }
}

**Comment by ligadatahari** [comment]
The bug is broken into different bugs 1110, 1111, and hence closing
