### ISSUE TITLE
get massge , model and container json does not contain tenantid 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1096]
Hi , 
    metadata api , get massge , model and container json does not contain tenantid . 

Thanks
Saleh

**Comment by ligadata-pokuri** [comment]
I think dan already fixed it. Can you verify?

**Comment by ligadata-saleh** [comment]
still can't find the tenant id in the json output from commands : 

kamanja get message 
kamanja get model 
kamanja get container 

Thanks
Saleh

**Comment by ligadata-pokuri** [comment]
dan, can you check this? I thought you fixed this. If not can you check this?

**Comment by ligadata-dan** [comment]
@ligadata-saleh @ligadata-pokuri 

Yep, TenantId was not added with the ElementID and SchemaID.   Added

**Comment by ligadata-pokuri** [comment]
now it is fixed. Saleh, can you test it.

**Comment by ligadata-yousef** [comment]
verified
