### ISSUE TITLE
Fixing a spelling mistake

### ISSUE THREAD

**Issue by JPCreedon** [LigaData/Kamanja#1097]
Added log4j-1.2-api for log4j **backword** compatibility (we support both…

**backward**

**Comment by ligadata-ashish** [comment]
@JPCreedon where is this "typo" issue...in documentation or release notes. Trying to figure out who needs to fix it where.

**Comment by JPCreedon** [comment]
In the github description... another one is here:

"Passing Verion from Top build file to sub projects"

**Comment by ligadata-pokuri** [comment]
@JPCreedon , these are commits history. It is just description of the check-in. There is no documentation or code associated with these typos.

**Comment by JPCreedon** [comment]
I know, it was just a point to paying more attention when doing the check-in.
