### ISSUE TITLE
Mapped message indication not honored... StructTypeDef type created

### ISSUE THREAD

**Issue by ligadata-rich** [LigaData/Kamanja#1100]
For this message:

{
  "Message": {
    "NameSpace": "com.botanical.csv",
    "Name": "mappedemailmsg",
    "Version": "1.00",
    "Description": "email message",
    "Fixed": "false",
    "Elements": [
      {
        "Field": {
          "Name": "From",
          "Type": "System.String"
        }
      },
      {
        "Field": {
          "Name": "To",
          "Type": "System.String"
        }
      },
      {
        "Field": {
          "Name": "Subject",
          "Type": "System.String"
        }
      },
      {
        "Field": {
           "Name": "Message",
          "Type": "System.String"
        }
      }
    ]
  }
}

the message instance returned for a test I want to do about mapped messages for csv serialization is a StructTypeDef.  This can be seen in the debugger.  It should be a MappedMsgDef.

The generated code seems to have the right settings (e.g., function 'override def isFixed: Boolean = false; ' is correct.  What is wrong is msgDef.containerType is a StructTypeDef.

**Comment by ligadata-pokuri** [comment]
Hi tulasi, check with rich once and fix it if he already not fixed it

**Comment by ligadata-pokuri** [comment]
Fixed with checkin SHA-1: ca921336a6c460c5d6836d61e433b5693184de03. Can you verify it?

**Comment by ligadata-rich** [comment]
This now works as evidenced with the following output from tests found in MetadataAPI/src/test/resources/SampleAdapterMessageBindingUnitTests.md : 

Result: 
[
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddAdapterMessageBinding",
    "Result Data" : "All binding additions were rejected!",
    "Result Description" : "One or more issues were encountered processing the input... see following results for the details... "
  }
},
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddAdapterMessageBinding",
    "Result Data" : "Binding could not be created",
    "Result Description" : "and not added...One or more problems detected for binding \"kafkaAdapterOutput2.com.botanical.csv.mappedemailmsg.com.ligadata.kamanja.serializer.csvserdeser\"...; MAPPED messages like com.botanical.csv.mappedemailmsg are not handled by the com.ligadata.kamanja.serializer.csvserdeser serializer at this time...; ; "
  }
}
]
