### ISSUE TITLE
smart input adapter on hdfs 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1101]
Hi , 
 smart input adapter on hdfs is reading the file correctly first time , after copying the same file again to the input folder am getting this massage .    
  
SMART FILE CONSUMER (MonitorController): File on the buffering Q is not found com.ligadata.InputAdapters.hdfs.HdfsFileHandler@7c75df55

*looking for the file its already exists 

hadoop dfs -cp /tmp/processed/Input_Data_HelloWorld.csv.gz /tmp/input
DEPRECATED: Use of this script to execute hdfs command is deprecated.
Instead use the hdfs command for it.

cp: `/tmp/input/Input_Data_HelloWorld.csv.gz': File exists

Thanks
Saleh

**Comment by ligadata-yasser** [comment]
@ligadata-saleh 
please verify

**Comment by ligadata-saleh** [comment]
verified
