### ISSUE TITLE
MetadataAPI : removing a non-existing adapterBinding

### ISSUE THREAD

**Issue by ligadata-haitham** [LigaData/Kamanja#1102]
when trying to remove an adapter binding that doesnt exist, i get the following message :
 ( assuming copdriskassessment_outputmsg is not the correct message name )

kamanja remove adaptermessagebinding KEY "testout_1,com.ligadata.kamanja.samples.models.copdriskassessment_outputmsg,com.ligadata.kamanja.serializer.csvserdeser"

Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "Remove AdapterMessageBinding",
    "Result Data" : null,
    "Result Description" : "Failed to add adapter message binding : testout_1,com.ligadata.kamanja.samples.models.copdriskassessment_outputmsg,com.ligadata.kamanja.serializer.csvserdeser"
  }
}

...... message should be : " Failed to remove adapter message binding...."

**Comment by ligadata-pokuri** [comment]
rich we should give status code is -1

**Comment by ligadata-rich** [comment]
whoops!

**Comment by ligadata-haitham** [comment]
issue is fixed.
