### ISSUE TITLE
Java/Scala model update does not keep element id constant

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1111]
kamanja update model java does not keep element ID constant

kamanja update model scala does not keep element ID constant

**Comment by ligadata-dan** [comment]
@ligadata-pokuri 

Ok, the issue here is the package name in the Java/Scala classes don't match the Model Name specified in the GetModelName() method of the model

For example (COPD.java model

package com.ligadata.kamanja.samples.models;

vs.

        public String getModelName() {
            return "com.ligadata.models.samples.models.COPDRiskAssessment";
        }


We need to talk about how to fix it.

**Comment by ligadata-dan** [comment]
Please verify

**Comment by ligadatahari** [comment]
The element id's are constant, but both java and scala have the same element id. Two models scala/java have the same element id

**Comment by ligadata-dan** [comment]
@ligadata-pokuri @ligadatahari 

I am closing this issue, this is going to be fixed in the next few weeks.. its related to Package Name vs Model Name inconsistency that we have.  Not a show stopper since I don't think people will be creating java and scala models by the same name
