### ISSUE TITLE
Migrate 113 to 140 : failed to migrate model

### ISSUE THREAD

**Issue by ligadata-haitham** [LigaData/Kamanja#1115]
when migrating 113 to 140, i use the Java_ModelConfig_Medical.json compile config as it is, and model fails to migrate .
the upgrade log is attached , please search for "ERROR" to get to the stack trace.
[KamanjaLog_113_To_140_Upgrade.zip](https://github.com/LigaData/Kamanja/files/248462/KamanjaLog_113_To_140_Upgrade.zip)

**Comment by ligadata-pokuri** [comment]
Fixed MAP from mutable to immutable.

**Comment by ligadata-haitham** [comment]
Migration is successful with no issue to report
