### ISSUE TITLE
cannot update on a non existiing object - should throw not exist error

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1118]
When you try to update the model when it does not exist, kamanja should throw the error as object does not exist, not version error. 

Try to select a model for update without adding it  is the step to reproduce. Error may be generic on Kamanja objects (message, container ... etc)

**Comment by ligadata-pokuri** [comment]
1. We should reject add if we already have an element for any type (model, message, container, etc) https://github.com/LigaData/Kamanja/issues/1119
2. We should reject update if we don't have an element for any type (model, message, container, etc)

**Comment by ligadatahari** [comment]
The following things are currently looked at for this bug 

1) Message
2) Function
3) AdapterMessageBinding
4) Container
5) Model (java, scala, kpmml, pmml, jam)

**Comment by ligadata-pokuri** [comment]
@ligadatahari as far as I know we are already rejecting Adapter Bindings. Functions are not so important at this moment. We mainly need it for Containers, Messages & Models.

**Comment by ligadatahari** [comment]
waiting on Dan Code acceptance

**Comment by ligadata-dan** [comment]
merged the code.  Go ahead and close

@ligadatahari

**Comment by ligadatahari** [comment]
closed
