### ISSUE TITLE
add objects and adding them again with different version adds object without giving duplicate error

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1119]
When on object is added in Kamanja using Kamanja add and adding them again changing the version adds the object in Kamanja instead of giving error. for example

kamanja add message $KAMANJA_HOME/input/SampleApplication/metadata/message/Message_Definition_HelloWorld.json TENATID tenant1 

and repeat add again after updating the message version. 

Kamanja says added successfully when it should throw error.

**Comment by ligadata-pokuri** [comment]
1. We should reject add if we already have an element for any type (model, message, container, etc)
2. We should reject update if we don't have an element for any type (model, message, container, etc)

**Comment by ligadatahari** [comment]
1) Message
2) Function
3) AdapterMessageBinding
4) Container
5) Model (java, scala, kpmml, pmml, jam)

**Comment by ligadata-pokuri** [comment]
@ligadatahari as far as I know we are already rejecting Adapter Bindings. Functions are not so important at this moment. We mainly need it for Containers, Messages & Models.

**Comment by ligadatahari** [comment]
Waiting on Dan Code acceptance

**Comment by ligadatahari** [comment]
Code merged
