### ISSUE TITLE
ClusterDriverInstall for 1.4 lists tenantId in usage text as optional when it is mandatory

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1124]
When running upgrade to Kamanja 1.4, the usage for ClusterDriverInstall shows that tenantId is a completely optional parameter but not specifying it produces an error message indicating it is required.

**Comment by ligadata-pokuri** [comment]
TenantId is not optional in upgrade. So, we need to change the documentation & usage

**Comment by ligadata-pokuri** [comment]
Check the existing stuff  (released in 1.4.0.) and let us know whether you need more information?

**Comment by ligadata-william** [comment]
verified fixed. closing.
