### ISSUE TITLE
SmartFileProcessor gives misleading error when input directory does not exist

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1137]
When I configure Kamanja to use SmartFileProcessor as my input adapter and give it a directory that doesn't exist, it gives the following error:
```
com.ligadata.Exceptions.KamanjaException: Smart File Consumer - Dir to watch /tmp/Kamanja/data/input is not accessible. It must be readable and writable
```
This needs to first check to see if the directory exists and, if not, give an error message indicating that the directory does not exist.

**Comment by ligadata-pokuri** [comment]
We can make it as P2.

**Comment by ligadata-yasser** [comment]
Fixed, please verify

**Comment by ligadata-william** [comment]
@ligadata-yasser can you create a pull request for this fix

**Comment by ligadata-yasser** [comment]
pull request is https://github.com/LigaData/Kamanja/pull/1134

**Comment by ligadata-william** [comment]
verified fixed. closing.
