### ISSUE TITLE
RestAPI services crash after the second add model call 

### ISSUE THREAD

**Issue by ligadata-baraa** [LigaData/Kamanja#1146]
Kamanja Version : 1.3.3

How to Reproduce:
Add a model, then after it has been added successfully try to add another one 

Actual Results:
Rest services crash, and you have to restart it to proceed 

Expected Results:
Adding the 2nd model successfully or getting an 'already exist' message if it's already been added

**Comment by ligadata-baraa** [comment]
Kamanja Version : 1.3.3

**Comment by ligadata-majali** [comment]
Kaman Version: 1.3.3

How to Reproduce:
Add message definition, then try upload config file 

Actual Results:
Rest services crash, and you have to restart it to proceed

Expected Results:
After adding the message definition, we should be able to upload config file and model without the need to restart the service.

**Comment by ligadata-pokuri** [comment]
Upload config file means is it Upload Model Config file?

**Comment by ligadata-dan** [comment]
@ligadata-baraa @ligadata-majali @ligadata-pokuri 

So, I ran the steps,

1. Add a message 

dankozin$ curl -X POST -d "@/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/input/SampleApplications/metadata/message/Message_Definition_HelloWorld.json" -k https://localhost:8081/api/message --header "tenantid:tenant1"
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.samples.messages.msg1.000000000001000000"
  }
}

dankozin$ curl -X POST -d "@/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/input/SampeApplications/metadata/message/OutMessage_Definition_HelloWorld.json" -k https://localhost:8081/api/message --header "tenantid:tenant1"
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.samples.messages.outmsg1.000000000001000000"
  }



2. Upload model config (actually a few times)
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "UploadModelsConfig",
    "Result Data" : null,
    "Result Description" : "Upload of model config successful"
  }
}Dans-MacBook-Pro-2:bin dankozin$ curl -X PUT -d "@/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/config/Mode_Config_HelloWorld.json" -k https://localhost:8081/api/uploadmodelconfig
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "UploadModelsConfig",
    "Result Data" : null,
    "Result Description" : "Upload of model config successful"
  }
}Dans-MacBook-Pro-2:bin dankozin$ curl -X PUT -d "@/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/config/Mode_Config_HelloWorld.json" -k https://localhost:8081/api/uploadmodelconfig
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "UploadModelsConfig",
    "Result Data" : null,
    "Result Description" : "Upload of model config successful"
  }
}

**Comment by ligadata-pokuri** [comment]
@ligadata-baraa, @ligadata-majali & @ligadata-alaa 
@ligadata-dan verified this in 1.4.1 and he did not find any issue. Can you go ahead and try in 1.4.0/1.4.1 (mostly releasing today) and let us know if you find any issues.

**Comment by ligadata-dan** [comment]
@ligadata-baraa @ligadata-majali @ligadata-pokuri 

Also, verified that Update and Add of the model is working ok

curl -X POST --data-binary "@/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/input/SampleApplications/metadata/model/HelloWorld.java" -k https://localhost:8081/api/model/java --header "tenantid:tenant1" --header "modelconfig:HelloWorldModel"



{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001"
  }



The Update is

curl -X PUT --data-binary "@/Users/dankozin/kamanja13/Kamanja-1.4.0_2.11/input/SampleApplications/metadata/model/HelloWorld.java" -k https://localhost:8081/api/model/java --header "tenantid:tenant1" --header "modelconfig:HelloWorldModel"


{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000002"
  }
}

**Comment by ligadata-dan** [comment]
@ligadata-baraa @ligadata-majali 

FYI.. the doc is wrong on this issue:

When uploading source code (java or scala) instead of -d option, use --data-binary otherwise you may get corrupted characters

**Comment by ligadata-dan** [comment]
@ligadata-baraa @ligadata-majali @ligadata-pokuri 

Also, we are detecting existing version during an update

{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "\"UpdateModel(type = java)\"",
    "Result Data" : null,
    "Result Description" : "Error :com.ligadata.Exceptions.AlreadyExistsException: Model com.ligadata.kamanja.samples.models.HelloWorldModel version should be higher than existing Models.Failed to Update Model"
  }
}
