### ISSUE TITLE
SmartFileProcessor has no implementation for getComponentSimpleStats

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1158]
There is an override for getComponentSimpleStats, however, rather than returning statistics for monitoring purposes, it returns an empty string, as shown below. Found on line 1112 in SmartFileConsumer.scala.
```
override def getComponentSimpleStats: String = {
   ""
  }
```

This needs to be implemented in order to properly monitor the adapter.

**Comment by ligadata-yasser** [comment]
please verify. it is fixed on branch 1.5.2

**Comment by ligadata-william** [comment]
Verified fixed. Closing.
