### ISSUE TITLE
kamanja start fails when a custom configuration file is passed in

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1159]
If you attempt to start the engine with a properties file other than the default, the engine fails to start.

Command run:
```
MacBook-Pro-2:Kamanja-1.4.0_2.11 william$ bash bin/kamanja ~/testresources/MetadataAPIConfig.properties start
```

Output Received:
```
ERROR [main] - Route not found
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "StartMetadataAPI",
    "Result Data" : null,
    "Result Description" : "No value found for 'start'"
  }
}
```

**Comment by ligadata-william** [comment]
The workaround is to backup the default Engine1Config.properties in <KamanjaInstallDirectory>/config and add your custom config with the name Engine1Config.properties.

**Comment by ligadata-dhaval** [comment]
Created a pull request #1428

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
