### ISSUE TITLE
Support Cluster Install for the same version when HOTFIX is released

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#1174]
Support Cluster Install for the same version when HOTFIX is release. Like when 1.4.1 is released we should allow ClusterInstall from 1.4.0. That way user can simply use ClusterInstall to use new software on all nodes with in the cluster.

**Comment by ligadata-william** [comment]
@ligadata-ramana this is only specific to 1.5.x, correct?

**Comment by ligadata-ramana** [comment]
I have incorporated all those changes I have done in 1.5.x into 1.6.0. Please use the pull request #1438 to test 1.5.x to 1.6.0 upgrade.

**Comment by ligadata-william** [comment]
This feature request is specific to micro version upgrades. So the user should be able to upgrade from 1.4.1 to 1.4.2 or 1.5.2 to 1.5.3 for example.

**Comment by ligadata-ramana** [comment]
Had a skype chat with william regarding his queries. William going to verify 1.5.3 to 1.6.0 upgrade whenever he is freed up.

**Comment by ligadata-william** [comment]
While upgrading from 1.5.3 to 1.6.0 is working fine, there isn't a micro-version upgrade scenario available that is supported yet. I'm pushing the milestone to 1.6.1 so that I may verify this once we have a 1.6.1 to test against.

**Comment by ligadata-william** [comment]
Verified as fixed in branch 1.6.1. Closing.
