### ISSUE TITLE
pmml models are not using "outmessage" value from kamanja command line

### ISSUE THREAD

**Issue by ligadata-rich** [LigaData/Kamanja#1192]
The value given for the "outmessage" parameter is not being sent down to the MetadataAPIImpl.  As such, the post that is desired to the community forum cannot be made.

**Comment by ligadata-rich** [comment]
In the following zip file are some test files and the text for the forum post that should be made after it is the steps mentioned therein are tested with the other files in the zip....

The zip file: 
[KamanjaSourceTestFiles.zip](https://github.com/LigaData/Kamanja/files/283428/KamanjaSourceTestFiles.zip)

**Comment by ligadata-pokuri** [comment]
@ligadata-ramana, the code for this issue is https://github.com/LigaData/Kamanja/tree/issue1192. can you verify whether we are taking the proper output msg or not for PMML.

**Comment by ligadata-rich** [comment]
@ligadata-yousef, there is a branch for this issue that is needed to fully test the pmml message generation tool.  It is branch "issue1192".

**Comment by ligadata-pokuri** [comment]
@ligadata-ramana also fixed and merged to 1.5.0.

**Comment by ligadata-pokuri** [comment]
Verified in 1.5.0.Test branch.
