### ISSUE TITLE
Documentation - List of All Errors

### ISSUE THREAD

**Issue by JPCreedon** [LigaData/Kamanja#1199]
There is no list of documentation for all errors.

See thread:

http://kamanja.org/forums/topic/doc-enhancement-cover-all-error-messages/

**Comment by ligadata-alison** [comment]
Have created an Error Message section - currently containing 9 errors. It will be released with 1.5 - http://www.kamanja.org/error-messages-1-5

**Comment by ligadata-alison** [comment]
Fixed on 1.5.x on old and new websites

**Comment by ligadata-alison** [comment]
JP, please verify
