### ISSUE TITLE
kamanja update message tries to compile every model it is associated with

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1203]
kamanja update message ../metadata/message/OutMessage_Definition_HelloWorld.json  TENANTID hello Properties '{ "description" : "first updated \n change", "comment" : "hopefully it works", "tag" : "okokokok", "Updatedby" : "Who knows"}'

updates all models

....

...
added manifest
adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V1/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V1/COPDDataIngest$$anonfun$1.class(in = 2025) (out= 846)(deflated 58%)
adding: com/ligadata/kamanja/samples/models/V1/COPDDataIngest$$anonfun$2.class(in = 1232) (out= 596)(deflated 51%)
adding: com/ligadata/kamanja/samples/models/V1/COPDDataIngest$$anonfun$execute$1.class(in = 2560) (out= 1148)(deflated 55%)
adding: com/ligadata/kamanja/samples/models/V1/COPDDataIngest$$anonfun$execute$2.class(in = 2553) (out= 1157)(deflated 54%)
adding: com/ligadata/kamanja/samples/models/V1/COPDDataIngest.class(in = 16962) (out= 7488)(deflated 55%)
adding: com/ligadata/kamanja/samples/models/V1/COPDDataIngestFactory.class(in = 2027) (out= 1151)(deflated 43%)
adding: COPDDataIngest.scala(in = 15932) (out= 3351)(deflated 78%)
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.samples.messages.outmsg1.000000000001000009"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.copdriskassessment.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001"
  }
}
RecompileModel results for com.ligadata.models.samples.models.lowbalancealert.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.models.samples.models.lowbalancealert.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.models.samples.models.lowbalancealert.000000000000000001"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.helloworldmodel.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.copddataingest.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.copddataingest.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.COPDDataIngest.000000000000000001"
  }
}

**Comment by ligadata-william** [comment]
From what I understand, you're updating a message called "outmsg1" that most of the models that are recompiled do not have as a dependency but they are being recompiled anyway. Is this correct?
What branch did this occur on? I'm not able to reproduce on the dev branch.

**Comment by ligadatahari** [comment]
fixed in 646 merge
