### ISSUE TITLE
Hello World KPMML doesn't produce output (Kamanja Version 1.4.1)

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1211]
In version 1.4.1 of Kamanja, the HelloWorld KPMML model doesn't produce any output. The java model outputs as expected.

**Comment by ligadata-pokuri** [comment]
Hi william,
Did you make sure you added adapter bindings?

**Comment by ligadata-william** [comment]
Yes, I double checked that and tried again and still got no output. Only after adding the java model did I get output.

**Comment by ligadata-pokuri** [comment]
Hi william,

We need to bind the message created while adding the model to output adapter. In our sample it will be like this system.helloworld_outputmsg. Here system.helloworld is model name and we generate default message called <ModelFullName>_outputmsg for KPMML models. In this case it will be system.helloworld_outputmsg

**Comment by ligadata-pokuri** [comment]
Hi william, can you verify and assign back to me if it does not work.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
