### ISSUE TITLE
StartEngine.sh is not working 

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1225]
Hi Dan , 
     StartEngine.sh is not running fine looking at the script the if statement condition is missing : 

if 
  JAAS_CONFIG_OPT="-Djava.security.auth.login.config="$KAMANJA_SEC_CONFIG
fi

i change it locally  to 

if [ "$KAMANJA_SEC_CONFIG" ]; then
  JAAS_CONFIG_OPT="-Djava.security.auth.login.config="$KAMANJA_SEC_CONFIG
fi

Thanks
Saleh

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Did you install the product using the EasyInstall?  Which script are you using for installation????

 I  know that the missing stuff should be there for sure...  I may have missed some other scripts.  

See below

#!/bin/sh
KAMANJA_HOME={InstallDirectory}

# Start the engine with hashdb backed metadata configuration.  The zookeeper and your queue software should be running
ipport="8998"

#-Djava.security.auth.login.config=/tmp/kerberos/jaas-client.conf
if
  JAAS_CONFIG_OPT="-Djava.security.auth.login.config="$KAMANJA_SEC_CONFIG
fi

# -Djava.security.krb5.conf=/etc/krb5.conf
if [ "$KAMANJA_KERBEROS_CONFIG" ]; then
  KERBEROS_CONFIG_OPT="-Djava.security.auth.login.config="$KAMANJA_KERBEROS_CONFIG
fi

if [ "$1" != "debug" ]; then
    java  $JAAS_CONFIG_OPT $KERBEROS_CONFIG_OPT -Dlog4j.configurationFile=file:{InstallDirectory}/config/log4j2.xml -cp {InstallDirectory}/lib/system/ExtDependencyLibs2_2.10-1.4.1.jar:{InstallDirectory}/lib/system/ExtDependencyLibs_2.10-1.4.1.jar:{InstallDirectory}/lib/system/KamanjaInternalDeps_2.10-1.4.1.jar:{InstallDirectory}/lib/system/kamanjamanager_2.10-1.4.1.jar com.ligadata.KamanjaManager.KamanjaManager --config {InstallDirectory}/config/Engine1Config.properties
else
	java  $JAAS_CONFIG_OPT $KERBEROS_CONFIG_OPT -Xdebug -Xrunjdwp:transport=dt_socket,address="$ipport",server=y -Dlog4j.configurationFile=file:{InstallDirectory}/config/log4j2.xml -cp {InstallDirectory}/lib/system/ExtDependencyLibs2_2.10-1.4.1.jar:{InstallDirectory}/lib/system/ExtDependencyLibs_2.10-1.4.1.jar:{InstallDirectory}/lib/system/KamanjaInternalDeps_2.10-1.4.1.jar:{InstallDirectory}/lib/system/kamanjamanager_2.10-1.4.1.jar com.ligadata.KamanjaManager.KamanjaManager --config {InstallDirectory}/config/Engine1Config.properties
fi

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

Sorry, I misunderstood..  I see  fixing now

**Comment by ligadata-saleh** [comment]
verified
