### ISSUE TITLE
SetPaths.sh script fails to find kafka-topics.sh when kafka version is 0.9 or greater

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1232]
When $KAFKA_HOME points to a version of kafka version 0.9 or greater, it fails to find kafka-topics.sh when looking for it in $KAFKA_HOME/bin/kafka-topics.sh. The result of this is that none of the kafka related scripts are created. (See SetPaths.sh lines 104-124).

The reason this is occurring is due to the fact that in kafka 0.9+ all script names have had the '.sh' extension removed. The SetPaths.sh script should be updated to check for either kafka-topics.sh or kafka-topics (without the '.sh').

**Comment by ligadata-pokuri** [comment]
Fixed in this branch https://github.com/LigaData/Kamanja/tree/issue1232

**Comment by ligadata-pokuri** [comment]
pull request # https://github.com/LigaData/Kamanja/pull/1242

**Comment by ligadata-william** [comment]
The fix for this has been checked in. Closing.
