### ISSUE TITLE
H2DBAdapter does not implement storage statistics

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1243]
Looks like the data is not being collected in the new adapter imply..

**Comment by ligadata-pokuri** [comment]
We will fix this in next version if not fixed in 1.5.0. And I am moving the priority to P2.

**Comment by ligadata-ramana** [comment]
Created pull request

**Comment by ligadata-ramana** [comment]
pull request #1300

**Comment by ligadata-william** [comment]
I've verified this as fixed. However, there are two issues related to the statistics, #1244 and #1357.
