### ISSUE TITLE
Description in "Storage_Adapter" statistics is very vague.

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1244]
Can we make the description a bit more meaningful, how about "Hbase", or "Cassandra"? 

{
      "Type": "Storage_Adapter",
      "Name": "Storage_1",
      **"Description": "Storage_1",**
      "LastSeen": "2016-06-24 21:19:57",
      "StartTime": "2016-06-24 21:16:03",
      "Metrics": "{}"
    }

**Comment by ligadata-ramana** [comment]
Issue #1357 address the issue of producing more readable statistics as a json string

**Comment by ligadata-william** [comment]
Closing this as a duplicate
