### ISSUE TITLE
Datastore Adapter stats are not updated

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1248]
{"Type":"Storage_Adapter","Name":"Storage_1","Description":"Storage_1","LastSeen":"2016-06-24 20:38:16","StartTime":"2016-06-24 20:36:45","Metrics":"{}"}]}

{"Type":"Storage_Adapter","Name":"Storage_1","Description":"Storage_1","LastSeen":"2016-06-24 20:40:31","StartTime":"2016-06-24 20:36:45","Metrics":"{}"}]}

I can see the timer moving....

I am also pushing a bunch of data ... 

PD,1,2016-06-24 20:41:17.793 PDT,Output/testfailedevents_1/evtCnt->0~Output/teststatus_1/evtCnt->229~Output/testmessageevents_1/evtCnt->102~Output/testout_1/evtCnt->4~Input/financeinput/evtCnt->0~Input/testin_1/evtCnt->0~Input/telecominput/evtCnt->0~Input/helloworldinput/evtCnt->102~Input/medicalinput/evtCnt->0~

...

PD,1,2016-06-24 20:41:59.926 PDT,Output/testfailedevents_1/evtCnt->0~Output/teststatus_1/evtCnt->271~Output/testmessageevents_1/evtCnt->153~Output/testout_1/evtCnt->6~Input/financeinput/evtCnt->0~Input/testin_1/evtCnt->0~Input/telecominput/evtCnt->0~Input/helloworldinput/evtCnt->153~Input/medicalinput/evtCnt->0

But I don't see stats being incremented.  I saw the stats being incremented using the debugger, but When the timer calls to collect them they are all empty.

**Comment by ligadata-ramana** [comment]
I have used Telecom application to reproduce the problem. Since StorageAdapterStatistics will be included in KamanjaStatisticsEvent, I tried to setup another kafka queue for StatisticsEvent and monitor that queue.  See the steps below

create a kafka topic for statistics events

$KAFKA_HOME/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions "8" --topic teststatevents_1

Add the following adapter to ClusterConfig.json and uploadConfig

        {
          "Name": "TestStatEvents_1",
          "TypeString": "Output",
          "TenantId": "tenant1",
          "ClassName": "com.ligadata.OutputAdapters.KafkaProducer$",
          "JarName": "KamanjaInternalDeps_2.11-1.5.0.jar",
          "DependencyJars": [
            "ExtDependencyLibs_2.11-1.5.0.jar",
            "ExtDependencyLibs2_2.11-1.5.0.jar"
          ],
          "AdapterSpecificCfg": {
            "HostList": "localhost:9092",
            "TopicName": "teststatevents_1"
          }
        },

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties upload cluster config $KAMANJA_HOME/config/ClusterConfig.json

Add a MessageBinding between TestStatEvents_1 and KamanjaStatisticsEvent

copy the following into /tmp/Telecom_Adapter_Bindings2.json

[
  {
    "AdapterName": "TestStatEvents_1",
    "MessageNames": [
      "com.ligadata.KamanjaBase.KamanjaStatisticsEvent"
    ],
    "Serializer": "com.ligadata.kamanja.serializer.jsonserdeser",
    "Options": {
      "alwaysQuoteFields": false,
      "fieldDelimiter": ","
    }
  }
]

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add adaptermessagebinding FROMFILE /tmp/Telecom_Adapter_Bindings2.json


Add another Binding from the following contents
[
  {
    "AdapterName": "Storage_1",
    "MessageNames": [
      "com.ligadata.KamanjaBase.KamanjaStatisticsEvent"
    ],
    "Serializer": "com.ligadata.kamanja.serializer.jsonserdeser",
    "Options": {
    }
  }
]

Create a new "Watch" script called WatchStatisticsEvent.sh


#!/bin/sh
if [ "$KAFKA_HOME" = "" ]; then
    echo "Please set KAFKA_HOME"
    exit 1
fi
$KAFKA_HOME/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic teststatevents_1

**Comment by ligadata-ramana** [comment]
I see the following in the console where I started WatchStatisticsEvent.sh

{ "@@SchemaId": 1000002, "@@TransactionId": 300842, "@@TimePartitionValue": 0, "@@RowNumber": 0, "statistics": "{\"Name\":\"1\",\"Version\":\"1.5.0.0\",\"UniqueId\":124,\"Metrics\":\"{\\\"UsedMemory\\\":\\\"24 MB\\\",\\\"FreeMomory\\\":\\\"22 MB\\\",\\\"TotalMemory\\\":\\\"47 MB\\\",\\\"MaxMemory\\\":\\\"3545 MB\\\"}\\\", \",\"LastSeen\":\"2016-06-30 17:34:35\",\"StartTime\":\"2016-06-30 17:24:12\",\"Components\":[{\"Type\":\"Input_Adapter\",\"Name\":\"financeinput\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:34\",\"StartTime\":\"2016-06-30 17:24:13\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Input_Adapter\",\"Name\":\"testin_1\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:30\",\"StartTime\":\"2016-06-30 17:24:13\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Input_Adapter\",\"Name\":\"telecominput\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:34\",\"StartTime\":\"2016-06-30 17:24:13\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":22,\\\"7\\\":20,\\\"1\\\":0,\\\"4\\\":20,\\\"6\\\":20,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Input_Adapter\",\"Name\":\"helloworldinput\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:31\",\"StartTime\":\"2016-06-30 17:24:13\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Input_Adapter\",\"Name\":\"medicalinput\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:31\",\"StartTime\":\"2016-06-30 17:24:14\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":45,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":45,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"teststatevents_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:32\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":122,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":122}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"testfailedevents_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:34\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":90,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":90}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"teststatus_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:34\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":745,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":745}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"testmessageevents_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:35\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":82,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":82}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"testout_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:35\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":82,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":82}\"},{\"Type\":\"Storage_Adapter\",\"Name\":\"Storage_1\",\"Description\":\"Storage_1\",\"LastSeen\":\"2016-06-30 17:34:35\",\"StartTime\":\"2016-06-30 17:24:08\",\"Metrics\":\"{Storage\/Storage_1\/putOps->(testdata:com_ligadata_kamanjabase_kamanjastatisticsevent:122),Storage\/Storage_1\/putObjs->(testdata:com_ligadata_kamanjabase_kamanjastatisticsevent:122),Storage\/Storage_1\/putBytes->(testdata:com_ligadata_kamanjabase_kamanjastatisticsevent:977366)}\"}]}" }
{ "@@SchemaId": 1000002, "@@TransactionId": 300848, "@@TimePartitionValue": 0, "@@RowNumber": 0, "statistics": "{\"Name\":\"1\",\"Version\":\"1.5.0.0\",\"UniqueId\":125,\"Metrics\":\"{\\\"UsedMemory\\\":\\\"31 MB\\\",\\\"FreeMomory\\\":\\\"16 MB\\\",\\\"TotalMemory\\\":\\\"47 MB\\\",\\\"MaxMemory\\\":\\\"3545 MB\\\"}\\\", \",\"LastSeen\":\"2016-06-30 17:34:40\",\"StartTime\":\"2016-06-30 17:24:12\",\"Components\":[{\"Type\":\"Input_Adapter\",\"Name\":\"financeinput\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:39\",\"StartTime\":\"2016-06-30 17:24:13\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Input_Adapter\",\"Name\":\"testin_1\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:35\",\"StartTime\":\"2016-06-30 17:24:13\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Input_Adapter\",\"Name\":\"telecominput\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:39\",\"StartTime\":\"2016-06-30 17:24:13\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":22,\\\"7\\\":20,\\\"1\\\":0,\\\"4\\\":20,\\\"6\\\":20,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Input_Adapter\",\"Name\":\"helloworldinput\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:36\",\"StartTime\":\"2016-06-30 17:24:13\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Input_Adapter\",\"Name\":\"medicalinput\",\"Description\":\"Kafka 0.8.2.2 Client\",\"LastSeen\":\"2016-06-30 17:34:36\",\"StartTime\":\"2016-06-30 17:24:14\",\"Metrics\":\"{\\\"Exception Summary\\\":{\\\"2\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"5\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"7\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"1\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"4\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"6\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"0\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"},\\\"3\\\":{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Last_Recovery\\\":\\\"n\/a\\\"}},\\\"Partition Counts\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":45,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":45,\\\"0\\\":0,\\\"3\\\":0},\\\"Partition Depths\\\":{\\\"2\\\":0,\\\"5\\\":0,\\\"7\\\":0,\\\"1\\\":0,\\\"4\\\":0,\\\"6\\\":0,\\\"0\\\":0,\\\"3\\\":0}}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"teststatevents_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:37\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":123,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":123}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"testfailedevents_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:39\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":90,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":90}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"teststatus_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:39\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":751,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":751}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"testmessageevents_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:40\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":82,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":82}\"},{\"Type\":\"Output_Adapter\",\"Name\":\"testout_1\",\"Description\":\"Kafka 0.9.0.x+ Client\",\"LastSeen\":\"2016-06-30 17:34:40\",\"StartTime\":\"2016-06-30 17:24:09\",\"Metrics\":\"{\\\"Last_Failure\\\":\\\"n\/a\\\",\\\"Messages Sent\\\":82,\\\"Last_Recovery\\\":\\\"n\/a\\\",\\\"Send Call Count\\\":82}\"},{\"Type\":\"Storage_Adapter\",\"Name\":\"Storage_1\",\"Description\":\"Storage_1\",\"LastSeen\":\"2016-06-30 17:34:40\",\"StartTime\":\"2016-06-30 17:24:08\",\"Metrics\":\"{Storage\/Storage_1\/putOps->(testdata:com_ligadata_kamanjabase_kamanjastatisticsevent:123),Storage\/Storage_1\/putObjs->(testdata:com_ligadata_kamanjabase_kamanjastatisticsevent:123),Storage\/Storage_1\/putBytes->(testdata:com_ligadata_kamanjabase_kamanjastatisticsevent:985425)}\"}]}" }
 
The storage adapter statistics related to kamanjastatisticsevent are being included. As per pokuri, we are not including storage adapter statistics related to model specific containes/messages are not included at this moment.

**Comment by ligadata-dan** [comment]
Ok, this works.. closing
