### ISSUE TITLE
File Producer is not implementing method getComponentSimpleStats( )

### ISSUE THREAD

**Issue by ligadata-yasser** [LigaData/Kamanja#1249]
method getComponentSimpleStats() is empty so adapter is not shown in status queue

**Comment by ligadata-pokuri** [comment]
Fixed in branch issue_1249 and opened pull request https://github.com/LigaData/Kamanja/pull/1264

**Comment by ligadata-yasser** [comment]
Verified

**Comment by ligadata-yasser** [comment]
Merged, Closing
