### ISSUE TITLE
PushSampleDataToKafka_XXXXX is too slow and not pushing any data using sasl_plaintext

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1252]
Hi
    PushSampleDataToKafka_XXXXX is too slow and not pushing any data using sasl_plaintext , i push data using the command console it worked fine  

Thanks
Saleh

**Comment by ligadata-dan** [comment]
@ligadata-saleh 

I saw this when I had 2 ports open (1 for SSL and one for SASL_PLAINTEXT)...  Once I just specified a single "listener"  in the KAFKA_HOME/conf/server.properties  it started working

**Comment by ligadata-saleh** [comment]
verified
