### ISSUE TITLE
DB Connections are not closed properly 

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1254]
When kamanaja stop/ start, clean up is done, db connects are still open to the h2 db and not closed even after kamanja exit 

tcp4       0      0  192.168.1.9.9092       192.168.1.9.59347      ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59345      ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59344      ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59343      ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59346      ESTABLISHED
tcp4       0      0  192.168.1.9.59344      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  192.168.1.9.59346      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  192.168.1.9.59347      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  192.168.1.9.59343      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  192.168.1.9.59345      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59304      ESTABLISHED
tcp4       0      0  192.168.1.9.59304      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  127.0.0.1.9092         127.0.0.1.59303        ESTABLISHED
tcp4       0      0  127.0.0.1.59303        127.0.0.1.9092         ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59302      ESTABLISHED
tcp4       0      0  192.168.1.9.59302      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  127.0.0.1.9092         127.0.0.1.59301        ESTABLISHED
tcp4       0      0  127.0.0.1.59301        127.0.0.1.9092         ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59300      ESTABLISHED
tcp4       0      0  192.168.1.9.59300      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  127.0.0.1.9092         127.0.0.1.59299        ESTABLISHED
tcp4       0      0  127.0.0.1.59299        127.0.0.1.9092         ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59298      ESTABLISHED
tcp4       0      0  192.168.1.9.59298      192.168.1.9.9092       ESTABLISHED
tcp4       0      0  127.0.0.1.9092         127.0.0.1.59297        ESTABLISHED
tcp4       0      0  127.0.0.1.59297        127.0.0.1.9092         ESTABLISHED
tcp4       0      0  192.168.1.9.9092       192.168.1.9.59277      ESTABLISHED
tcp4       0      0  192.168.1.9.59277      192.168.1.9.9092       ESTABLISHED
tcp46      0      0  *.9092                 *.*                    LISTEN

**Comment by ligadata-pokuri** [comment]
Hi hari,

By default 9092 is Kafka port. Can you change the port for H2DB and see whether we are still listening it or not?
