### ISSUE TITLE
DB Connections are not closed properly 

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1255]
When kamanaja stop/ start, clean up is done, db connects are still open to the h2 db and not closed even after kamanja exit 

I stopped the h2db server, I still get this.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/hariramasamy/mykamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/hariramasamy/mykamanja/Kamanja-1.5.0_2.11/lib/system/ExtDependencyLibs_2.11-1.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
ERROR [main] - Message:Cannot create PoolableConnectionFactory (Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-192])
java.sql.SQLException: Cannot create PoolableConnectionFactory (Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-192])
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2291) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2038) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533) ~[ExtDependencyLibs2_2.11-1.5.0.jar:1.0]

**Comment by ligadatahari** [comment]
tcp4       0      0  127.0.0.1.9100         127.0.0.1.50590        ESTABLISHED
tcp4       0      0  127.0.0.1.50590        127.0.0.1.9100         ESTABLISHED
tcp46      0      0  *.9100                 *.*                    LISTEN     
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63523        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63523        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63522        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63522        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63521        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63521        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63519        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63519        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63518        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63518        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63517        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63517        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63516        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63516        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63515        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63515        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63514        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63514        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63513        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63513        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63444        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63444        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63443        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63443        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63442        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63442        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63441        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63441        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63440        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63440        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63439        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63439        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63438        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63438        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63437        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63437        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63436        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63436        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63435        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63435        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63431        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63431        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63430        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63430        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63429        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63429        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63428        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63428        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63427        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63427        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63426        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63426        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63425        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63425        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63424        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63424        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63423        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63423        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63422        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63422        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63409        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63409        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63408        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63408        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63407        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63407        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63406        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63406        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63405        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63405        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63404        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63404        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63403        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63403        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63402        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63402        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63401        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63401        127.0.0.1.9100         CLOSE_WAIT 
tcp4       0      0  127.0.0.1.9100         127.0.0.1.63400        FIN_WAIT_2 
tcp4       0      0  127.0.0.1.63400        127.0.0.1.9100         CLOSE_WAIT

**Comment by ligadatahari** [comment]
Steps to reproduce 

1. Upload Cluster Config, using tcp mode for h2.
2. Start Kamanja
3. Run helloWorldApp.sh
4. Repeat Push hello ten times by wrapping in a script 
5. Stop and restart h2 when step 4 is in progress
6. Run Medical App.sh - u will see db errors. 
7 execute netstat -an | grep 9100 to see number of open connections
8. Stop H2.
9. Repeat 7 and u will see the count still remaining

**Comment by ligadata-haitham** [comment]
I am unable to reproduce this issue.
i will communicate with Hari to see if we can reproduce it together.

**Comment by ligadata-haitham** [comment]
according to the documentation, this error code is thrown in case of multiple connections in embedded H2db mode : 
http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90020

**Comment by ligadatahari** [comment]
I had a chat with Haitam. It happens in one rare condition. When u start in server mode, switch to embedded mode without closing kaman manager, the old connections are left open. Once the Kamanja is restarted, the connections are gone. 

Only small issue is kamanja is not detecting the h2 server down and closed all connections, requires manual correction

Lowering the issue to P3, Pokuri might decide otherwise.

**Comment by ligadata-haitham** [comment]
in short, to avoid this issue, when switching from server to embedded mode,we should turn off KamanjaManager, upload the ClusterConfig.json, and then start KamanjaManager again.

**Comment by ligadata-pokuri** [comment]
@ligadata-haitham , If you want, can you ask alison to add this to her documentation as NOTE

**Comment by ligadata-alison** [comment]
It's ok Haitham. I have added the note.
