### ISSUE TITLE
Push producer script defaults to localhost:9092; needs option to change

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1257]
I have an environment where I have 3 kafka brokers, indicated by node01:9092,node02:9092,node03:9092 (all on separate machines). When set to localhost:9092, it fails to push to kafka. There needs to be an option to replace the broker-list.

**Comment by ligadata-dan** [comment]
@ligadata-william @ligadata-pokuri @ligadata-alison 

Adding a --kafkahosts option to our Push scripts.. probably need it for the watcher scripts as well

**Comment by ligadata-dan** [comment]
@ligadata-william 

Please verify

**Comment by ligadata-william** [comment]
Verified and closing.
