### ISSUE TITLE
Kafka consumer failed to connect to 0.8.x kafka

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#1265]
WARN [pool-21-thread-5] - KAFKA ADAPTER: Error fetching topic financeinput, partition 1, recreating kafka leader for this partition
 WARN [pool-21-thread-7] - KAFKA ADAPTER: Failure fetching topic financeinput, partition 6, retrying
 WARN [pool-21-thread-3] - KAFKA ADAPTER: Failure fetching topic financeinput, partition 4, retrying
 WARN [pool-21-thread-7] - KAFKA ADAPTER: Error fetching topic financeinput, partition 6, recreating kafka leader for this partition
 WARN [pool-21-thread-3] - KAFKA ADAPTER: Error fetching topic financeinput, partition 4, recreating kafka leader for this partition
 WARN [pool-21-thread-6] - KAFKA ADAPTER: Failure fetching topic financeinput, partition 3, retrying
 WARN [pool-21-thread-6] - KAFKA ADAPTER: Error fetching topic financeinput, partition 3, recreating kafka leader for this partition
 WARN [pool-21-thread-4] - KAFKA ADAPTER: Failure fetching topic financeinput, partition 7, retrying
 WARN [pool-21-thread-4] - KAFKA ADAPTER: Error fetching topic financeinput, partition 7, recreating kafka leader for this partition
 WARN [pool-21-thread-1] - KAFKA ADAPTER: Failure fetching topic financeinput, partition 2, retrying
 WARN [pool-21-thread-1] - KAFKA ADAPTER: Error fetching topic financeinput, partition 2, recreating kafka leader for this partition
 WARN [pool-21-thread-2] - KAFKA ADAPTER: Failure fetching topic financeinput, partition 5, retrying
 WARN [pool-21-thread-2] - KAFKA ADAPTER: Error fetching topic financeinput, partition 5, recreating kafka leader for this partition
 WARN [pool-21-thread-8] - KAFKA ADAPTER: Failure fetching topic financeinput, partition 0, retrying
 WARN [pool-22-thread-7] - KAFKA ADAPTER: Failure fetching topic testin_1, partition 6, retrying
 WARN [pool-22-thread-7] - KAFKA ADAPTER: Error fetching topic testin_1, partition 6, recreating kafka leader for this partition
 WARN [pool-21-thread-8] - KAFKA ADAPTER: Error fetching topic financeinput, partition 0, recreating kafka leader for this partition
 WARN [pool-22-thread-5] - KAFKA ADAPTER: Failure fetching topic testin_1, partition 1, retrying
 WARN [pool-22-thread-5] - KAFKA ADAPTER: Error fetching topic testin_1, partition 1, recreating kafka leader for this partition

**Comment by ligadata-pokuri** [comment]
May be producer also not working.

**Comment by ligadata-dan** [comment]
is this New Stuff connecting to 0.8?

**Comment by ligadata-pokuri** [comment]
[KamanjaLog.zip](https://github.com/LigaData/Kamanja/files/339900/KamanjaLog.zip)

**Comment by ligadata-pokuri** [comment]
that is full log

**Comment by ligadata-william** [comment]
I am able to reproduce this with KafkaSimpleConsumer$. The I am able to use the kafka-console-consumer.sh script to see that messages are in the input topic and I can see that status messages are being properly produces, however, Kamanja appears unable to connect to kafka 0.8.2.x to read messages. I haven't seen this in the new KamanjaKafkaConsumer$.

**Comment by ligadata-dan** [comment]
kafka has backward compatibility issue at this moment. will fix at later date.

**Comment by ligadata-dan** [comment]
@ligadata-haitham 

kafkaV10 branch has the code that will compile with 0.10 dependency.

**Comment by ligadata-dan** [comment]
Handled under branch

KafkaCompatibility
https://github.com/LigaData/Kamanja/tree/KafkaCompatibility

**Comment by ligadata-william** [comment]
Verified fixed. Closing.
