### ISSUE TITLE
Failed to stop KamanjaManager if Kafka is not connectable

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#1266]
WARN [pool-24-thread-3] - KAFKA ADAPTER: Error fetching topic helloworldinput, partition 4, recreating kafka leader for this partition
 WARN [pool-25-thread-6] - KAFKA ADAPTER: Failure fetching topic medicalinput, partition 3, retrying
 WARN [pool-25-thread-6] - KAFKA ADAPTER: Error fetching topic medicalinput, partition 3, recreating kafka leader for this partition
 WARN [pool-21-thread-5] - KAFKA ADAPTER: Recovered from error fetching financeinput, partition 1, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:13 & failed messages:0
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
Exception in thread "pool-21-thread-4" Exception in thread "pool-21-thread-5" java.lang.Error: java.lang.InterruptedException: sleep interrupted
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1066)
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:370)
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060)
	... 2 more
Exception in thread "pool-21-thread-6" java.lang.Error: java.lang.InterruptedException: sleep interrupted
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1066)
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:370)
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060)
	... 2 more
Exception in thread "pool-21-thread-7" java.lang.Error: java.lang.InterruptedException: sleep interrupted
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1066)
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:370)
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060)
	... 2 more
java.lang.Error: java.lang.InterruptedException: sleep interrupted
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1066)
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.ligadata.InputAdapters.KafkaSimpleConsumer$$anonfun$StartProcessing$3$$anon$1.run(KafkaSimpleConsumer.scala:370)
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060)
	... 2 more
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0

 WARN [pool-22-thread-6] - KAFKA ADAPTER: Failure fetching topic testin_1, partition 3, retrying
 WARN [pool-22-thread-6] - KAFKA ADAPTER: Error fetching topic testin_1, partition 3, recreating kafka leader for this partition
 WARN [pool-23-thread-7] - KAFKA ADAPTER: Failure fetching topic telecominput, partition 6, retrying
 WARN [pool-23-thread-7] - KAFKA ADAPTER: Error fetching topic telecominput, partition 6, recreating kafka leader for this partition
 WARN [pool-24-thread-1] - KAFKA ADAPTER: Failure fetching topic helloworldinput, partition 2, retrying
 WARN [pool-24-thread-1] - KAFKA ADAPTER: Error fetching topic helloworldinput, partition 2, recreating kafka leader for this partition
 WARN [pool-25-thread-5] - KAFKA ADAPTER: Failure fetching topic medicalinput, partition 1, retrying
 WARN [pool-25-thread-5] - KAFKA ADAPTER: Error fetching topic medicalinput, partition 1, recreating kafka leader for this partition

 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process

 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-24-thread-8] - KAFKA ADAPTER: Failure fetching topic helloworldinput, partition 0, retrying
 WARN [pool-24-thread-8] - KAFKA ADAPTER: Error fetching topic helloworldinput, partition 0, recreating kafka leader for this partition
 WARN [pool-25-thread-7] - KAFKA ADAPTER: Failure fetching topic medicalinput, partition 6, retrying
 WARN [pool-25-thread-7] - KAFKA ADAPTER: Error fetching topic medicalinput, partition 6, recreating kafka leader for this partition
 WARN [pool-22-thread-3] - KAFKA ADAPTER: Failure fetching topic testin_1, partition 4, retrying
 WARN [pool-22-thread-3] - KAFKA ADAPTER: Error fetching topic testin_1, partition 4, recreating kafka leader for this partition
 WARN [pool-23-thread-6] - KAFKA ADAPTER: Failure fetching topic telecominput, partition 3, retrying
 WARN [pool-23-thread-6] - KAFKA ADAPTER: Error fetching topic telecominput, partition 3, recreating kafka leader for this partition
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process

 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process

 WARN [pool-7-thread-1] - KAFKA PRODUCER: Topic: testfailedevents_1 - current outstanding messages:0 & failed messages:0
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-11-thread-1] - KAFKA PRODUCER: Topic: testmessageevents_1 - current outstanding messages:0 & failed messages:0
 WARN [pool-13-thread-1] - KAFKA PRODUCER: Topic: testout_1 - current outstanding messages:0 & failed messages:0
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-25-thread-8] - KAFKA ADAPTER: Failure fetching topic medicalinput, partition 0, retrying
 WARN [pool-25-thread-8] - KAFKA ADAPTER: Error fetching topic medicalinput, partition 0, recreating kafka leader for this partition
 WARN [pool-22-thread-2] - KAFKA ADAPTER: Failure fetching topic testin_1, partition 5, retrying
 WARN [pool-22-thread-2] - KAFKA ADAPTER: Error fetching topic testin_1, partition 5, recreating kafka leader for this partition
 WARN [pool-22-thread-8] - KAFKA ADAPTER: Failure fetching topic testin_1, partition 0, retrying
 WARN [pool-22-thread-8] - KAFKA ADAPTER: Error fetching topic testin_1, partition 0, recreating kafka leader for this partition
 WARN [pool-23-thread-3] - KAFKA ADAPTER: Failure fetching topic telecominput, partition 4, retrying
 WARN [pool-23-thread-3] - KAFKA ADAPTER: Error fetching topic telecominput, partition 4, recreating kafka leader for this partition
 WARN [pool-24-thread-6] - KAFKA ADAPTER: Failure fetching topic helloworldinput, partition 3, retrying
 WARN [pool-24-thread-6] - KAFKA ADAPTER: Error fetching topic helloworldinput, partition 3, recreating kafka leader for this partition
 WARN [pool-25-thread-2] - KAFKA ADAPTER: Failure fetching topic medicalinput, partition 5, retrying
 WARN [pool-25-thread-2] - KAFKA ADAPTER: Error fetching topic medicalinput, partition 5, recreating kafka leader for this partition
 WARN [pool-24-thread-2] - KAFKA ADAPTER: Failure fetching topic helloworldinput, partition 5, retrying
 WARN [pool-24-thread-2] - KAFKA ADAPTER: Error fetching topic helloworldinput, partition 5, recreating kafka leader for this partition
 WARN [pool-25-thread-4] - KAFKA ADAPTER: Failure fetching topic medicalinput, partition 7, retrying
 WARN [pool-25-thread-4] - KAFKA ADAPTER: Error fetching topic medicalinput, partition 7, recreating kafka leader for this partition
 WARN [pool-22-thread-7] - KAFKA ADAPTER: Recovered from error fetching testin_1, partition 6, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-23-thread-1] - KAFKA ADAPTER: Recovered from error fetching telecominput, partition 2, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-24-thread-7] - KAFKA ADAPTER: Recovered from error fetching helloworldinput, partition 6, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-23-thread-2] - KAFKA ADAPTER: Failure fetching topic telecominput, partition 5, retrying
 WARN [pool-23-thread-2] - KAFKA ADAPTER: Error fetching topic telecominput, partition 5, recreating kafka leader for this partition
 WARN [pool-22-thread-5] - KAFKA ADAPTER: Recovered from error fetching testin_1, partition 1, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-23-thread-5] - KAFKA ADAPTER: Recovered from error fetching telecominput, partition 1, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-24-thread-5] - KAFKA ADAPTER: Recovered from error fetching helloworldinput, partition 1, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-25-thread-3] - KAFKA ADAPTER: Recovered from error fetching medicalinput, partition 4, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-22-thread-4] - KAFKA ADAPTER: Recovered from error fetching testin_1, partition 7, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-23-thread-4] - KAFKA ADAPTER: Recovered from error fetching telecominput, partition 7, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-24-thread-4] - KAFKA ADAPTER: Recovered from error fetching helloworldinput, partition 7, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-25-thread-1] - KAFKA ADAPTER: Recovered from error fetching medicalinput, partition 2, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-22-thread-1] - KAFKA ADAPTER: Recovered from error fetching testin_1, partition 2, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-23-thread-8] - KAFKA ADAPTER: Recovered from error fetching telecominput, partition 0, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-24-thread-3] - KAFKA ADAPTER: Recovered from error fetching helloworldinput, partition 4, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-25-thread-6] - KAFKA ADAPTER: Recovered from error fetching medicalinput, partition 3, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-22-thread-6] - KAFKA ADAPTER: Recovered from error fetching testin_1, partition 3, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-23-thread-7] - KAFKA ADAPTER: Recovered from error fetching telecominput, partition 6, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-25-thread-5] - KAFKA ADAPTER: Recovered from error fetching medicalinput, partition 1, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-24-thread-1] - KAFKA ADAPTER: Recovered from error fetching helloworldinput, partition 2, failing over to the new leader vm002.ligadata.com:9092
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0
 WARN [pool-9-thread-1] - KAFKA PRODUCER: Topic: teststatus_1 - current outstanding messages:15 & failed messages:0

**Comment by ligadata-pokuri** [comment]
WARN [pool-24-thread-5] - KAFKA ADAPTER: Error fetching topic helloworldinput, partition 1, recreating kafka leader for this partition
 WARN [pool-25-thread-3] - KAFKA ADAPTER: Failure fetching topic medicalinput, partition 4, retrying
 WARN [pool-25-thread-3] - KAFKA ADAPTER: Error fetching topic medicalinput, partition 4, recreating kafka leader for this partition
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process
^C WARN [SIGINT handler] - Got SIGINT signal. Shutting down the process

**Comment by ligadata-dan** [comment]
@ligadata-william 

Willie, to report this you need to start v0.8 broker, and use kamanja 1.5 connection... you will go into a fetch fail loop and CtrcC should break you out.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
