### ISSUE TITLE
PMML compiler: If() function not properly generated (optional else)

### ISSUE THREAD

**Issue by edifecs-pradeep** [LigaData/Kamanja#127]
The following supposedly valid usage of 'If' function fails:
```xml
  <DerivedField name="CAT1_Rule1a1b" dataType="boolean" optype="categorical">
      <Apply function="if">
        <Constant dataType="boolean">true</Constant>
        <Constant dataType="boolean">true</Constant>
      </Apply>
    </DerivedField>
```

/home/le/dev/OnLEPInstall/workingdir/COPD_CAT1_RiskAssessment
/COPD_CAT1_RiskAssessment.scala:328: error: overloaded method value If with alternatives:
  (boolexprs: scala.collection.mutable.ArrayBuffer[Boolean])Boolean <and>
  (boolexpr: Boolean,boolexpr1: Boolean,boolexpr2: Boolean,boolexpr3: Boolean)Boolean <and>
  (boolexpr: Boolean,boolexpr1: Boolean,boolexpr2: Boolean)Boolean <and>
  (boolexpr: Boolean,boolexpr1: Boolean)Boolean <and>
  (boolexpr: Boolean)Boolean
 cannot be applied to ()
        val CAT1_Rule1a1b = If()

**Comment by ligadata-william** [comment]
Closing due to age.
