### ISSUE TITLE
ClusterInstall will not account for new Kafka security

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1274]
When validating Kafka during a migrate script we need to parse and use the security variables in the cluster config.

**Comment by ligadata-pokuri** [comment]
@ligadata-dan , may be we need to fix this in 1.5.0.

**Comment by ligadata-pokuri** [comment]
This can happen for fresh installation also. This is mainly to validate the components while doing Cluster Install.

**Comment by ligadata-dan** [comment]
@ligadata-saleh @ligadata-william 

Hi Saleh, can you try to install Kamanja with Kerberos enabled Kafka , from branch  issue1274 (https://github.com/LigaData/Kamanja/pull/1304)

**Comment by ligadata-dan** [comment]
@ligadata-saleh @ligadata-william 

FYI, the doc for this that we have is here

http://kamanja.org/cluster-installation-1-5/#When_Migrating_Old_Content_to_a_New_Installation

**Comment by ligadata-dan** [comment]
@ligadata-dhaval 

Dhaval tested the install path.. tested the SSL path.
