### ISSUE TITLE
Failed to update kpmml model 

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1281]
Steps to reproduce :

1. Add helloworld message
2. Add KPMML_Model_HelloWorld.xml
3. Change model version from source file from version="00.01.00"  to version="00.02.00"
4. Update model ( ./kamanja update model kpmml Kamanja/input/SampleApplications/metadata/model/KPMML_Model_HelloWorld.xml TENANTID tenant1)

Expected : 
Update model successfully

Actual result :

Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "UpdateKPMMLModel",
    "Result Data" : null,
    "Result Description" : "KPMML model must exist to perform update"
  }
}

**Comment by ligadata-ahmad** [comment]
@ligadatahari  I found the same issue with java model

**Comment by ligadata-ahmad** [comment]
The update operations failed in both MetadataAPIService and MetadataAPI

**Comment by ligadata-ahmad** [comment]
same thing with scala model

**Comment by ligadata-ahmad** [comment]
I think here is the problem 

lets say we have  kpmmlhelloworld v1 already loaded  and we are trying to update to v2

if you look at Kamanja/trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ModelUtils.scala
line number 1583 

`if (modDef == null || DoesModelAlreadyExist(modDef) == false) {
        return (new ApiResult(ErrorCodeConstants.Failure, "UpdateKPMMLModel", null, s"KPMML model must exist to perform update")).toString
      }`

we are checking if model v2 exists before updating the model . and  here it fails because at this moment  v1 is in the system not v2

**Comment by ligadata-pokuri** [comment]
Verified and merged to 1.5.0.Test
