### ISSUE TITLE
 Tenant id is missed in jtm commands in documentation 

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1284]
In this webpage :
http://kamanja.org/advanced-developers-guide-1-5/models-1-5/jtm-1-5/#How_JTM_Works

The tenant id is missed in the following commands :
kamanja < metadata api properties file > add model jtm < jtm spec file >
kamanja < metadata api properties file > update model jtm < jtm spec file >

The following are the correct commands :

kamanja add model jtm input(optional) TENANTID <tenantId>
kamanja update model jtm input(optional) TENANTID <tenantId>

**Comment by ligadata-alison** [comment]
Fixed - thanks!

**Comment by ligadata-ahmad** [comment]
Verified , Thanks Alison
