### ISSUE TITLE
activate and deactivate don't work using kamanja commands

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1287]
Steps to reproduce :

1. add copd model 
2. ./kamanja deactivate  model com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001 

Expected : model deactivated successfully 
Actual : 
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "StartMetadataAPI",
    "Result Data" : null,
    "Result Description" : "No value found for 'deactivatemodelcom.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001'"
  }

**Comment by ligadata-pokuri** [comment]
Verified and merged to 1.5.0.Test
