### ISSUE TITLE
sasl_ssl kamanja consumer group id is empty  

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1289]
- producer adapters works fine consumers on the other hand send these warning :

 WARN [pool-20-thread-1] - KamanjaKafkaConsumer Exception during Kafka Queue processing medicalinput, cause:
org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group:
 WARN [pool-18-thread-1] - KamanjaKafkaConsumer Exception during Kafka Queue processing telecominput, cause:
org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group:
 WARN [pool-19-thread-1] - KamanjaKafkaConsumer Exception during Kafka Queue processing helloworldinput, cause:
org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group:
 WARN [pool-17-thread-1] - KamanjaKafkaConsumer Exception during Kafka Queue processing testin_1, cause:
org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group:

- we need to set "props.setProperty(ConsumerConfig.GROUP_ID_CONFIG, "securing-kafka-group")" in the consumer code , otherwise i cant give the consumers any authentication using the kafaka-acls command , the consumer console  is working fine for sasl_ssl on my machine . 

Thanks
Saleh

**Comment by ligadata-dan** [comment]
@ligadata-saleh 
 Fixing

**Comment by ligadata-dan** [comment]
@ligadata-saleh @ligadata-pokuri 

Had a chat with Saleh, and the concern with adding a group id to the consumer is forcing the consumer into using Groups.  which will probably not work with our Consumer implementation.  We will loose control of our offsets.  I will test if the presence of this field will cause problems....

Saleh will also test the code with the fix (only exists in the SASL_SSL path).

**Comment by ligadata-dan** [comment]
@ligadata-saleh @ligadata-pokuri @ligadatahari 

Hi, checked in the code that will set the group.ids in our consumer/producers.

In the ClusterConfig add this for each (if you don't, it will default to "kamanja-kafka-group"....  Then use this group ID for the ACL operations.

          "AdapterSpecificCfg": {
            "HostList": "localhost:9093",
            **"kafka.group":"big1",**
            "TopicName": "testmessageevents_1",
            "security.protocol":"SSL",

**Comment by ligadata-saleh** [comment]
@ligadata-dan i have to create the group manually for the adapters to work fine , i think more testing is needed here , but for the sasl_ssl its working fine now .

verified
