### ISSUE TITLE
General fixes on CreateMessage tool

### ISSUE THREAD

**Issue by ligadata-haitham** [LigaData/Kamanja#1291]
here are some small issues to be fixed:

1) when providing a wrong delimitor , the error message is not clear. ( maybe check for existance of the delimitor before using it).

2) when outputPath path ends with "/" (example: /opt/) , the result message path has extra "/" :
you can find the file in this path /opt//message_20160703051505.json .
(WORKS BUT DOES NOT LOOK PRETTY, maybe check for "/" at the end of the path and remove it)

3) namespace should be validated , for example we cant have it ending in a ."
example ->  "nameSpace": "com.ligadata.",    >>>>>> should not be allowed.

**Comment by ligadata-yousef** [comment]
i am working on it @ligadata-haitham

**Comment by ligadata-yousef** [comment]
fixed.

i added a pull request with this id #1314. @ligadata-haitham please verify after @ligadata-pokuri or @ligadata-william merged to 1.5.0.Test or you can test it in "GenerateMessageFile-Kamanja-640" branch.

**Comment by ligadata-haitham** [comment]
all these issues are fixed in branch "GenerateMessageFile-Kamanja-640"

**Comment by ligadata-dhaval** [comment]
re-verified for the 1.5.2-alpha release
