### ISSUE TITLE
We need to remove all commands related to "types" from kamanja help 

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1292]
These commands need to be removed from kamanja help since we are no longer support types  :

IV. Type operations
kamanja get type input(optional)
kamanja get all types
kamanja dump all types

**Comment by ligadata-alison** [comment]
Please let me know when the type commands have been removed from the help
menu. Then I can update the documentation.

**Comment by ligadata-dhaval** [comment]
Hi,

I have made the changes for types in the help menu in 1.5.0.Test.

Regards,
Dhaval Kolapkar

Best Regards,
Dhaval Kolapkar
Platform Engineer Intern | LigaDATA

**Comment by ligadata-alison** [comment]
Documentation updated
