### ISSUE TITLE
easyInstallKamanja.sh fails if wget is not installed

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1293]
There is an error that occurs when running easyInstallKamanja.sh (usually on mac) where if wget is not installed, the installation fails when attempting to run wget. A check should be done at the beginning of the install script to determine if wget is installed (or can be found on the $PATH).

**Comment by ligadata-pokuri** [comment]
We need to change wget to any download. We need to download jar here. We don't want to check in jdbc jars in our repository. We will fix this in 1.5.1

**Comment by ligadata-pokuri** [comment]
In documentation we have to say wget is our PreReq for easyInstall script(s)

**Comment by ligadata-alison** [comment]
I have added it to 1.5.2.

**Comment by ligadata-alison** [comment]
Added to 1.5.2 on old and new websites

**Comment by ligadata-alison** [comment]
william, please verify

**Comment by ligadata-william** [comment]
@ligadata-alison I don't see a mention of wget as a pre-requisite. I've looked at both http://kamanja.org/wiki/installation-steps-for-advanced-developers-guide/ and http://kamanja.org/wiki/run-easyinstallkamanja-sh/ and I'm unable to find it.

Can you please send me the link where that documentation exists?

**Comment by ligadata-alison** [comment]
http://kamanja.org/learn/advanced-developers-guide/preparing-the-development-environment/

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
