### ISSUE TITLE
we need to keep only one command to add function instead of two

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1295]
Currently we have two commands to add function :
1.add function input(optional) 
2.kamanja load functions from a file

we need to keep only one of them .

**Comment by ligadata-alison** [comment]
Please let me know when one of the commands is removed. Then I can update
the documentation.

**Comment by ligadatahari** [comment]
fixed verify

Removed Load Functions from a file

**Comment by ligadata-alison** [comment]
Once Dhaval has removed this command from the help menu, then I will update
the documentation.

**Comment by ligadata-dhaval** [comment]
It is removed from the help menu.

**Comment by ligadata-william** [comment]
@ligadata-dhaval, if you've verified this issue is fixed, please close the issue.

**Comment by ligadata-dhaval** [comment]
Verified.

Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "StartMetadataAPI/route",
    "Result Data" : null,
    "Result Description" : "The action = loadfunctionsfromafile is no longer supported, please use add function"
  }
}
