### ISSUE TITLE
CreateMessage should check for timePartition value to be in the message fields

### ISSUE THREAD

**Issue by ligadata-haitham** [LigaData/Kamanja#1297]
timePartition value should be checked to be one of the message fields, see below example : 
(asdasd is not a valid message field)

{
  "Message":{
    "NameSpace":"com.ligadata.kamanja",
    "Name":"testmessage",
    "Version":"00.01.00",
    "Description":"",
    "Fixed":"false",
    "Persist":"false",
    "Fields":[{
      "Name":"Sepal_Length",
      "Type":"System.Double"
    },{
      "Name":"Sepal_Width",
      "Type":"System.Double"
    },{
      "Name":"Petal_Length",
      "Type":"System.Double"
    },{
      "Name":"Petal_Width",
      "Type":"System.Double"
    }],
    "TimePartitionInfo":{
      "Key":"asdasd",
      "Format":"epochtime",
      "Type":"Daily"
    }
  }
}

**Comment by ligadata-yousef** [comment]
i am working on it @ligadata-haitham

**Comment by ligadata-yousef** [comment]
fixed.

i added a pull request with this id #1314.  @ligadata-haitham  please verify after @ligadata-pokuri or @ligadata-william  merged to 1.5.0.Test or you can test it in "GenerateMessageFile-Kamanja-640" branch.

**Comment by ligadata-haitham** [comment]
this issue is fixed in "GenerateMessageFile-Kamanja-640" branch.

**Comment by ligadata-dhaval** [comment]
re-verified for the 1.5.2-alpha release
