### ISSUE TITLE
Adding a message via the MetadataAPIService causes zookeeper notification error

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1303]
When I add the Hello World message definition using the REST Service, the message is added properly, but there is an error indicating objectType TenantDef is unknown:
```
ERROR [main-EventThread] - Unknown objectType TenantDef in zookeeper notification, notification is not processed ..
```

**Comment by ligadata-ramana** [comment]
created a pull request #1424

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
