### ISSUE TITLE
Cluster install fails if the install directory is already present even though it is empty

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1306]
I performed cluster install and while replacing the <InstallDirectory> paths in ClusterCfgMetadataAPIConfig.properties and ClusterConfig.json I gave the path /tmp/KamanjaCluster. In the tmp folder the KamanjaCluster is present and is empty. When I ran the cluster install, it gave the error - For fresh install, found valid directory/link at  <InstallDirectory>  at least on one node.
This error occurs when there is a directory created. In my case it is the KamanjaCluster. Maybe we can add an error mentioning that the directory is already present. Please delete it and try again.
Also the logs created for the install script start with the name UpgradeLog.log, which could be generic to cluster install or specific to install or upgrade.

**Comment by ligadata-alison** [comment]
Hi Dhaval,
      I added a note regarding your issue in the documentation.
thanks,
alison

**Comment by ligadata-alison** [comment]
Dhaval, please verify

**Comment by ligadata-william** [comment]
@ligadata-dhaval what is the status on this issue?

**Comment by DhavalKolapkar** [comment]
@ligadata-alison I am not able to find cluster install on the new kamanja site. http://kamanja.org/learn/advanced-developers-guide. Also there is no search option, so couldn't try out that option. Could you share the link of the page, where you made the changes?

Thank you.

**Comment by ligadata-alison** [comment]
Hi Dhaval,
      I'll talk with Ashish about a search option - it is so important!
Here is the page:

http://kamanja.org/learn/multi-node-installation-guide/

Please take a look at the left for the 3 sections.
thanks,
alison

**Comment by ligadata-alison** [comment]
Hi Dhaval,
    I have added a note in step 4 of cluster install. If it is ok, please verify and close the bug.
thanks,
alison

**Comment by ligadata-dhaval** [comment]
Thank you Alison. Verified and closing it.
