### ISSUE TITLE
GenerateAdapterBindings: serializer is defaulting to csvserdeser eventhough dataformat is json

### ISSUE THREAD

**Issue by ligadata-ramana** [LigaData/Kamanja#1307]

**Comment by ligadata-ramana** [comment]
new pull request is #1310

**Comment by ligadata-william** [comment]
@ligadata-ramana has the code for this already been merged? I'm going to test on dev to see if it's no longer an issue.

**Comment by ligadata-pokuri** [comment]
@ligadata-william , Yes william this code is merged in 1.5.1. You can verify in 1.5.3 and close it

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
