### ISSUE TITLE
Update Help to reflect 646 feature and 1302  issues

### ISSUE THREAD

**Issue by ligadatahari** [LigaData/Kamanja#1312]
Update Help accordingly

**Comment by ligadatahari** [comment]
Fixed

**Comment by ligadata-alison** [comment]
Hi Hari,
    What commands did you remove from the Help menu?
thanks,
alison

**Comment by ligadata-william** [comment]
Please add detail to this issue as it isn't exactly obvious what I should be looking for.

**Comment by ligadatahari** [comment]
Kamanja add function is there
Kamanja load function from a file  (is removed)

------------------------------ Please look at kamanja help output below  for 646 features ------------------------------------------- (Tenant id filter, Properties/PropertiesFile)

******************** Help Menu ****************************
I. Message operations
kamanja add message input(optional) TENANTID <tenantId>  Properties/PropertiesFile(optional) <Json String/Filename>
kamanja update message input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja get message input(optional) TENANTID(optional) <tenantId>
kamanja get all messages TENANTID(optional) <tenantId>
kamanja remove message input(optional)
II. Model operations
kamanja add model kpmml input(optional) TENANTID <tenantId>  Properties/PropertiesFile(optional) <Json String/Filename>
kamanja add model pmml input MODELNAME namespace.name MODELVERSION nn.nn.nn MESSAGENAME namespace.name TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja add model java input(optional)  TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja add model scala input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja add model jtm input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja get model input(optional) TENANTID(optional) <tenantId>
kamanja get all models TENANTID(optional) <tenantId>
kamanja remove model input(optional)
kamanja update model kpmml input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja update model pmml input MODELNAME namespace.name MODELVERSION nn.nn.nn TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja update model scala input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja update model java input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja update model jtm input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja deactivate model input(optional)
kamanja activate model input(optional)
III. Container operations
kamanja add container input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja update container input(optional) TENANTID <tenantId> Properties/PropertiesFile(optional) <Json String/Filename>
kamanja get container input(optional) TENANTID(optional) <tenantId>
kamanja get all containers TENANTID(optional) <tenantId>
kamanja remove container input(optional)
IV. Function operations
kamanja add function input(optional)
kamanja get function input(optional)
kamanja remove function input(optional)
kamanja update function input(optional)
kamanja dump all functions
V. Congurations operations
kamanja upload cluster config input(optional)
kamanja upload compile config input(optional)
kamanja dump all cfg objects
kamanja remove engine config
VI. Jar operations
kamanja upload jar
VII. Cluster, metadata and adapter operations
kamanja dump metadata
kamanja dump all nodes
kamanja dump all clusters
kamanja dump all cluster cfgs
kamanja dump all adapters
VIII. Kamanja engine operations
kamanja start
kamanja start -v (for verbose)
IX. Topic operations
kamanja watch status queue
kamanja push data
kamanja create queues
X. Web service
kamanja start webservice
XI. Adapter Message Bindings
kamanja add adaptermessagebinding FROMFILE input
kamanja add adaptermessagebinding FROMSTRING input
kamanja remove adaptermessagebinding KEY '<adapter name>,<namespace.msgname>,<namespace.serializername>'
kamanja list adaptermessagebindings
kamanja list adaptermessagebindings ADAPTERFILTER <adatper name>
kamanja list adaptermessagebindings MESSAGEFILTER <namespace.msgname>
kamanja list adaptermessagebindings SERIALIZERFILTER <namespace.serializername>
kamanja get typebyschemaid SCHEMAID <schemaid>
kamanja get typebyelementid ELEMENTID <elementid>
XII. General operations

**Comment by ligadata-dhaval** [comment]
I have verified this. Will close it


Best Regards,
Dhaval Kolapkar
Platform Engineer | LigaDATA
