### ISSUE TITLE
SAS Model Validation : TypeCheckException encountered while running SAS Models on Kamanja 1.5RC1

### ISSUE THREAD

**Issue by ligadata-shilpa** [LigaData/Kamanja#1313]
The SAS PMML models are storing the data in string format using the "Best Format" conversions. They probably are assuming that our pmml consumer will do the necessary type coercion where required. JPMML lib however is missing the conversion from string to integer which is why the jpmml evaluator is throwing a Type Check Exception when it encounters strings where it is expecting numbers.

**Error Message** :

.
.
.
ERROR [pool-17-thread-1] - Attempting to process
inputs = 'Message com.ligadata.kamanja.HMEQSASData values: DEBTINC = 34.57151913...not mapped... isA(DOUBLE), DELINQ = 0.0...not mapped... isA(DOUBLE), VALUE = 88934.0...not mapped... isA(DOUBLE), CLAGE = 219.6010022...not mapped... isA(DOUBLE), YOJ = 15.0...not mapped... isA(DOUBLE), CLNO = 16.0...not mapped... isA(DOUBLE), JOB = Other...not mapped... isA(STRING), DEROG = 0.0...not mapped... isA(DOUBLE), NINQ = 0.0...not mapped... isA(DOUBLE)',
the following exception was encountered: org.jpmml.evaluator.TypeCheckException (at or around line 30): Expected INTEGER, but got STRING (FMTWIDTH)
ERROR [pool-17-thread-1] - No score produced.
.
.
.

You can find the function definition for Best Format functions under the Transformation Dictionary tag n the PMML models (code snippet attached below).

**Function Definitions**:
`<TransformationDictionary>`
      `<DefineFunction name="SAS-EM-String-Normalize" optype="categorical" dataType="string">`
        `<ParameterField name="FMTWIDTH" optype="continuous"/>`
        `<ParameterField name="AnyCInput" optype="categorical"/>`
        `<Apply function="trimBlanks">`
          `<Apply function="uppercase">`
            `<Apply function="substring">`
              `<FieldRef field="AnyCInput"/>`
             ` <Constant>1</Constant>`
             ` <Constant>FMTWIDTH</Constant>`
            `</Apply>`
          `</Apply>`
        `</Apply>`
      `</DefineFunction>`
     ` <DefineFunction name="SAS-FORMAT-BESTw" optype="categorical" dataType="string">`
        `<ParameterField name="FMTWIDTH" optype="continuous"/>`
        `<ParameterField name="AnyNInput" optype="continuous"/>`
       ` <Apply function="formatNumber">`
          `<FieldRef field="AnyNInput"/>`
          `<Constant>FMTWIDTH</Constant>`
        `</Apply>`
      `</DefineFunction>`
      `<DefineFunction name="SAS-FORMAT-$CHARw" optype="categorical" dataType="string">`
        `<ParameterField name="FMTWIDTH" optype="continuous"/>`
        `<ParameterField name="AnyCInput" optype="continuous"/>`
        `<Apply function="substring">`
          `<FieldRef field="AnyCInput"/>`
          `<Constant>1</Constant>`
          `<Constant>FMTWIDTH</Constant>`
        `</Apply>`
      `</DefineFunction>`
   ` </TransformationDictionary>`

There are different ways we can handle this, listing a few based on discussions with the team:

1. Report this issue to Villu (jpmml author) and wait for them to fix this - which may take months.
2. Edit the PMML models and remove the function calls to the Best Format conversion functions.
3. Fix the jpmml evaluator and make a fix contribution to jpmml.
4. Contact the SAS model author, David and request him to send us new models without these conversions.
  
The validation is being done on Kamanja 1.5RC1 (installed using binaries) and Kafka version being used is 0.9. The following files are attached:
- HMEQ Dataset
- Input Message Definition
- 3 SAS Models
- Adapter Binding
- Scores files in csv format sent by SAS
- PushSampleDatatoKafka.sh script for pushing HMEQ dataset

**FILES:**

[HMEQ_SAS_Files.zip](https://github.com/LigaData/Kamanja/files/354849/HMEQ_SAS_Files.zip)

**Comment by vruusmann** [comment]
The expression `<Constant>FMTWIDTH</Constant>` cannot be coerced to integer. It's an invalid field value reference.

Please see the following SO thread for extended discussion:
https://stackoverflow.com/questions/33003359/fmtwidth-error-while-using-jpmml-to-evaluate-a-sas-produced-pmml-file

Also, the JPMML library contains a visitor class that can locate and fix such expressions:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-sas/src/main/java/org/jpmml/sas/visitors/ExpressionCorrector.java

**Comment by ligadata-pokuri** [comment]
Fixed in branch 1.5.1.1320

**Comment by ligadata-pokuri** [comment]
Shilpa can you please verify it in 1.5.2?

**Comment by ligadata-greg** [comment]
Hello,
The SAS best format adapts to the number of needed numeric bytes per field,
not between numeric and character.
http://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a000184495.htm

SAS character formats start with "$" as in
$ASCIIw.
$EBCDICw.     where "w" is a parameter for the number of bytes.

Yes, please verify.

**Comment by ligadata-dhaval** [comment]
Verified by myself and Shilpa. Closing this issue.
