### ISSUE TITLE
 ClusterConfig for smart file output adapter

### ISSUE THREAD

**Issue by ligadata-yousef** [LigaData/Kamanja#1315]
Hi 
Alison,

in this link http://kamanja.org/advanced-developers-guide-1-5/adapters-1-5/sfoa-1-5/
in the ClusterConfig.json please change:

1- com.ligadata.InputAdapters.SmartFileProducer$    to      com.ligadata.OutputAdapters.SmartFileProducer$

2- smartfileinputoutputadapters_2.10-1.0.jar    to      KamanjaInternalDeps_2.10-1.5.0.jar   because smartfileinputoutputadapters_2.10-1.0.jar not in $KAMANAJA_HOME/lib/system

**Comment by ligadata-alison** [comment]
Done
