### ISSUE TITLE
Kafka install from homebrew affects CreateQueues.sh and WatchQueues.sh scripts

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1318]
New kafka versions when downloaded from homebrew do not have .sh extensions for their scripts while those from the kafka binaries have. This is an inconsistency which is affecting kamanja scripts WatchQueues and CreateQueues and similar related to kafka queues. @ligadata-alison, kindly could you add it in the website, if we have a section for known issues. I am posting on the forum in the meantime.

**Comment by ligadata-alison** [comment]
Done
