### ISSUE TITLE
Kamanja quickstart and developer guide minor documentation issues

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1321]
Documentation questions:

1. Output Adapter Message Binding example has only one messageName and document says there are 2.
2.  CleanUtil-1.0 tool  not in bin folder
3.  Jason Transformation Model should be JSON in Add a JTM model.

**Comment by ligadata-alison** [comment]
Fixed Jason to JSON but the other 2 issues need input from Rich and William.
RIch - would you please resolve the issue that Dhaval discovered in the Message Bindings documentation and then let me know the update?
William - what do I put for the missing CleanUtil-1.0 tool?

**Comment by ligadata-alison** [comment]
Fixed all issues on all Kamanja versions on old and new websites

**Comment by ligadata-alison** [comment]
Dhaval, please verify

**Comment by ligadata-william** [comment]
@ligadata-dhaval, can you verify this?

**Comment by ligadata-dhaval** [comment]
Verified and closing this issue.
