### ISSUE TITLE
Updating Tenant fails for SQL adapter.

### ISSUE THREAD

**Issue by ligadata-dan** [LigaData/Kamanja#1351]
Primary Data source in the tenant is expected to have "Location", but sql storage config does not have it, therefore fails to update.

**Comment by ligadata-dan** [comment]
https://github.com/LigaData/Kamanja/pull/1353

**Comment by ligadata-william** [comment]
Verified as fixed.

**Comment by ligadata-dhaval** [comment]
re-verified for 1.5.2-alpha
