### ISSUE TITLE
SmartFileAdapter process files only on the leader node 

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1352]
When running SmartFileAdapter with kamanja installed on cluster (3 nodes ) only the leader node is processing files .

**Comment by ligadata-pokuri** [comment]
Fixed in branch 1.5.1.1352. Will merge to new releases.

**Comment by ligadata-pokuri** [comment]
this is in 1.5.2

**Comment by ligadata-ahmad** [comment]
verified
