### ISSUE TITLE
Failure to write scala files when compiling messages/containers gives misleading error

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1355]
When adding messages or containers, if Metadata API fails to write a scala file to the workingdir, it simply states a FileNotFoundException like the one found at http://kamanja.org/forums/topic/failed-to-add-containermessage/

A FileNotFoundException should not be displayed to the user in APIResults but a clean error message indicating that Metadata API failed to write a file to the target directory. There should also be a check if that directory exists and if appropriate read/write permissions exist (Appropriate error messages for each are necessary and should be specific).

**Comment by ligadata-ramana** [comment]
Created a pull request #1425

**Comment by ligadata-william** [comment]
The compiler work directory is created when it doesn't exist and when it can't be created, there is a clear message indicating that there was a failure to create the directory. Verified as fixed.
