### ISSUE TITLE
issue when using multiple outputAdatper

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1358]
The issue is that when using multiple outputAdapter and one of them fail , the other adapter will not emit the message  to the destination

**Comment by ligadata-krishna** [comment]
we need to fix this asap possible as it is critical path in some customer deployment.

**Comment by ligadata-pokuri** [comment]
This is fixed in branch 1.5.1.1358

**Comment by ligadata-pokuri** [comment]
This is in 1.5.2

**Comment by ligadata-ahmad** [comment]
verified.
