### ISSUE TITLE
Failed to append to file in HDFS  using HDFS output adapter

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1375]
exception (attached) from the adapter when pushing 2 messages sequentially to the engine  in a 
very short time.

[Exceptions.txt](https://github.com/LigaData/Kamanja/files/391620/Exceptions.txt)

**Comment by ligadata-sridhar** [comment]
Fixed on 1.5.1-phoenix branch

**Comment by ligadata-ahmad** [comment]
verified
