### ISSUE TITLE
Doc bug with SBT supported version

### ISSUE THREAD

**Issue by ligadata-ashish** [LigaData/Kamanja#1381]
http://kamanja.org/advanced-developers-guide-1-5/dev-env-1-5/

We only support SBT v0.13.7 not "+". Pleae highlight and make absolutely clear in the docs.

**Comment by ligadata-alison** [comment]
Fixed on all Kamanja versions on old and new website.

**Comment by ligadata-alison** [comment]
Ashish - please verify

**Comment by ligadata-william** [comment]
This issue cannot be verified as the link is now broken. @ligadata-alison can you please update with the proper link?

**Comment by ligadata-alison** [comment]
Hi William,
     The new link is

http://kamanja.org/learn/advanced-developers-guide/preparing-the-development-environment/

Please verify.
thanks,
alison

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
