### ISSUE TITLE
primary key doesn't work as expected in message

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1394]
same key is inserted multiple times into storage

**Comment by ligadata-pokuri** [comment]
Sample Message 

{
  "Message": {
    "NameSpace": "com.abc.containers",
    "Name": "WindowAlertThresholds",
    "Version": "00.01.00",
    "Description": "WindowAlertThresholds",
    "Fixed": "true",
    "Persist": "true" ,
    "Fields": [
      {
        "Name": "windowSizeInMins",
        "Type": "System.int"
      },
      {
        "Name": "uniqueCallsThreshold",
        "Type": "System.int"
      },
      {
        "Name": "NumOfCallsThreshold",
        "Type": "System.int"
      },
      {
        "Name": "incomingDurationThreshold",
        "Type": "System.int"
      }
    ],
    "PartitionKey" :[
     "windowSizeInMins"
     ],
     "PrimaryKey": [
          "windowSizeInMins"
        ]
  }
}

=========================

Sample Data

15, 5, 10,  3
30, 8, 15,  3
60, 12, 25,  3

**Comment by ligadata-pokuri** [comment]
use this to extract message/container data

$KAMANJA_HOME/bin/ContainersUtility.sh --config $KAMANJA_HOME/config/Engine1Config.properties --containername "com.abc.containers.windowalertthresholds" --operation "select" --filter /tmp/filter.json --outputpath /tmp --serializer "com.ligadata.kamanja.serializer.csvserdeser" --serializeroptionsjson "{ \"alwaysQuoteFields\": false,\"fieldDelimiter\": \",\" ,\"valueDelimiter\":\"~\" }" --compressionstring "gz"

**Comment by ligadata-pokuri** [comment]
Integrated fix in branch 1.5.1-phoenix

**Comment by ligadata-pokuri** [comment]
ahmed can you verify the bug.

**Comment by ligadata-ahmad** [comment]
closing as verified .
