### ISSUE TITLE
Kafka input adapters fail to start without any messages (ERROR or otherwise)

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1401]
When starting Kamanja, if the cluster configuration only contains the ExtDependencyLibs for the kafka input adapters and is missing the KamanjaInternalDeps and kafka-clients jar as described in http://kamanja.org/kafka-adapters-shipped/, then Kamanja continues to run and the adapters have not started.

If the adapters fail to start, Kamanja should fail with an error.

**Comment by ligadata-ashish** [comment]
Kamanja can run with other adapters even without Kafka being configured to run. So at a min an error needs to be reported.

**Comment by ligadata-tulasi** [comment]
Assigning back to William to repro the issue with latest ExtDependencyLibs

**Comment by ligadata-william** [comment]
As of 1.6.1 this is a non-issue. It may very well never have been an issue at all. When I remove all the dependencyJars from the input adapter configuration, the adapters appear to start just fine and process messages normally.
