### ISSUE TITLE
StartMetadata catch exceptions not in order of their subclasses

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1407]
In StartMetadataAPI, the catch block has Throwable first, then Exceptions and then RuntimeException. The order should be RuntimeException, Exception and Throwable.

**Comment by ligadata-dhaval** [comment]
@ligadata-pokuri I think we should not be handling Runtime exception in the catch block?

**Comment by ligadata-dhaval** [comment]
Created a pull request #1410

**Comment by ligadata-william** [comment]
Hey Pokuri,

I have created branch Berkley_1.5.3 based off tag v1.5.3 and and push the new branch into the repository. I have also merged the changes into the dev branch and the 1.6.0 branch.

I haven’t merged into master nor have I created any new tags. Let me know if this is something you want me to do as well.

-William

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
