### ISSUE TITLE
Kamanja does not check if the user defined message definition file is present for updateMessage

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1413]
Kamanja does not check if the user defined message definition file is present for updateMessage.

**Comment by ligadata-dhaval** [comment]
Resolving as a part of the branch github1036

**Comment by ligadata-dhaval** [comment]
Created a pull request #1423

**Comment by ligadata-william** [comment]
This is fixed but I won't close it until #1036 is fixed since they share a pull request.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
