### ISSUE TITLE
If incorrect choice give while choosing the message to be removed arrayindexoutofbound exception

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1414]
Instead of invalid choice an exception of arrayindex out of bound is thrown while remove message

**Comment by ligadata-dhaval** [comment]
The code change will be a part of the git branch github1036

**Comment by ligadata-dhaval** [comment]
Created a pull request #1423

**Comment by ligadata-william** [comment]
This is fixed but I won't close it until #1036 is fixed since they share a pull request.

**Comment by ligadata-william** [comment]
Verified as fixed, closing.
