### ISSUE TITLE
PMML and Python models returns null is returned instead of meaningful message to the user.

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1418]
For add PMML, Python and Jthyon, we are returning null instead of a string or APIResult. It says TO BE IMPLEMENTED. 
Code: null /// FIXME : we will return null for now and complain with first failure.
Also, "PMML models are only ingested with command line arguments.. default directory selection is deprecated" Are we going to resolve it? as it does not match our standard practice.

**Comment by ligadata-dhaval** [comment]
Created a pull request #1439

**Comment by ligadata-dhaval** [comment]
Just to make a note: Discussed with Hari on this and as informed, returning the messages which were logged as  debug or error as APIResult now. @ligadata-tulasi and @ligadatahari, please could you check if 'PMML models are only ingested with command line arguments' needs to be fixed.

**Comment by ligadata-william** [comment]
I've verified this as fixed. Closing.
