### ISSUE TITLE
kamanja script not updated with guava-19 for the 2.10 version of the script

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1429]
On branch FC-37, the elasticsearch storage adapter requires guava-19.0 on the classpath for kamanja to start properly. This was done for Utils/Script/scala-2.11/kamanja but not for Utils/Script/scala-2.10/kamanja.

**Comment by ligadata-haitham** [comment]
fix is provided in the same branch.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
