### ISSUE TITLE
Documentation required for GenerateMessage.sh to indicate quotation marks should be excluded from file header

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1431]
When running GenerateMessage.sh, if the --inputfile contains headers with quotation marks (") around each column name, fields will not be generated. Documentation is needed to indicate quotation marks should not be a part of the headers.

**Comment by ligadata-william** [comment]
This is related to #1398

**Comment by ligadata-alison** [comment]
Hi William,
      Please verify:

http://kamanja.org/learn/tools-guide/tool-to-generate-a-message-definition/

thanks,
alison

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
