### ISSUE TITLE
When using Elasticsearch with a non-default cluster name, metadata API and kamanja are unable to connect

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1432]
In my elasticsearch.yml, I set cluster.name: elasticsearch_william and when attempting to upload cluster config, it failed to connect. When I changed it back to the default "elasticsearch", I was able to connect.

We need to allow an elasticsearch cluster name to be passed in via configuration.

**Comment by ligadata-haitham** [comment]
an optional key can now be added to DataStore called "clusterName".
the default value is "elasticsearch" if not specified otherwise.
changes r in FC-37 branch.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
