### ISSUE TITLE
Updating a container in medical sample fails to recompile copdriskassessment model

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1433]
When I update a container (in the medical app for example), the JTM is not being recompiled (which is good) but the copdriskassessment model, which is dependent on it, isn't being recompiled (which is bad).

**Comment by ligadata-william** [comment]
This is a blocker.

**Comment by ligadata-ramana** [comment]
A pull request #1436 created.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
