### ISSUE TITLE
In the medical app, when updating a message such as HL7,Beneficiary,etc. we are recompiling the JTM instead of copdriskassessment

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1434]
Updating a message (such as hl7) is causing the COPDDataIngest JTM to be recompiled (BAD) instead of its actual dependent model copdriskassessment.

**Comment by ligadata-william** [comment]
Observed also is updating a the hello world message definition does not recompile it's model either.

**Comment by ligadata-william** [comment]
This is a blocker.

**Comment by ligadata-ramana** [comment]
A pull request #1436 is created

**Comment by ligadata-william** [comment]
hl7 is listed under MessageAndContainers and is therefore a dependency. InputTypesSets should not be the sole definer of dependency on a type. The COPDRiskAssessment model still requires knowledge of hl7 and if the model is not recompiled with the proper jar after update, errors will occur in the model.

Conversely, COPDDataIngest lists none of the messages as dependencies, yet it is the one recompiling.

These are both issues still present in #1434 as of this morning and should be fixed.

**Comment by ligadata-ramana** [comment]
Fixed the issue. Please use the same pull request #1436 (branch Issue1434) to verify the fix

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
