### ISSUE TITLE
Cluster configs in cluster install do not have generic paths

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1453]
For ClusterConfig_kafka_v(8 | 9 | 10).json, some of the paths are not generic paths.
1.   "Location": "/media/home2/installKamanja160/Kamanja-1.6.0_2.11/storage/syscatalog",
2."JarPaths": [
            "/media/home2/installKamanja160/Kamanja-1.6.0_2.11/lib/system",
            "/media/home2/installKamanja160/Kamanja-1.6.0_2.11/lib/application"
          ]
3. "Scala_home": "/home/vmandava/scala-2.11.7",
4.  "Java_home": "/home/vmandava/jdk1.8.0_05",

Also, the MetadataDataStore in ClusterCfgMetadataAPI.properties points to hbase but in cluster configs it points to h2db. We may have a common config so it will be easier for the user.

**Comment by ligadata-ramana** [comment]
Used the same branch update160Issues for the fix.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
