### ISSUE TITLE
Divide python model fails to compile

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#1454]
When adding divide.py, it fails to compile:
DEBUG [main] - python file cleanup of /tmp/programs/Kamanja/python/tmp/divide.py following compile = 0
ERROR [main] - The supplied python text failed to compile... model name = DivideTuple... model catalog fails
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Failed to Add Model : (python model - compile failed).000000000000000000000)"
  }
}

**Comment by ligadatahari** [comment]
verify

**Comment by ligadata-dhaval** [comment]
Verified and closing.
