### ISSUE TITLE
sample application install script Python_Simple.sh uploads incorrect cluster configuration

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1463]
The script uploads ClusterConfig.json, which is invalid. By default, our app install scripts are uploading ClusterConfig_kafka_v10.json. Currently, running the script as is causes Kamanja to fail to start due to incorrect class names for the kafka input/output adapters that are contained in the old ClusterConfig.json.

**Comment by ligadatahari** [comment]
Please verify

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
