### ISSUE TITLE
Regression Issue with simplification of APIProperties file

### ISSUE THREAD

**Issue by ligadata-ramana** [LigaData/Kamanja#1465]
One of the issue we worked on is simplification of MetadataAPIProperties file. 
Due to this improvement, MetadataAPIConfig.properties is required to contain
only the following three properties
#MetadataStore information
NodeId=1
MetadataDataStore={"StoreType": "h2db","connectionMode": "embedded","SchemaName": "kamanja","Location": "/media/home2/installKamanja160/Kamanja-1.6.0_2.11/storage","portnumber": "9100","user": "test","password": "test"}
ROOT_DIR=/media/home2/installKamanja160/Kamanja-1.6.0_2.11
==========
I have mistakenly added the same requirement to Engine1Config.properties
Engine1Config.properties is used to KamanjaEngine and derives the necessary 
information from cluster config file.
We need to remove the requirement of "ROOT_DIR" from Engine1Config.properties
(It is optional for Kamanja Engine and other Utilities such as InitKvStore)

During upgrade, we don't update Engine1Config.properties. So Engine fails to start because 
of missing property "ROOT_DIR".

**Comment by ligadata-william** [comment]
@ligadata-ramana I see the pull request is available with the fix, so I'm assigning this issue to myself to verify.

**Comment by ligadata-william** [comment]
I've verified after a cluster upgrade from 1.5.3 to 1.6.0 that all nodeN.cfg files are without the ROOT_DIR specification but StartKamanjaCluster.sh works as expected. All nodes are up and running.

Verified as fixed. Closing.
