### ISSUE TITLE
Deliver tests to validate PMML 4.2 built-in Functions

### ISSUE THREAD

**Issue by edifecs-pradeep** [LigaData/Kamanja#147]
Please provide test that we can use to verify that the 4.2 built-in functions are implemented and correct.

    +, -, * and /
    min, max, sum, avg, median, product
    log10, ln, sqrt, abs, exp, pow, threshold, floor, ceil, round
    isMissing, isNotMissing
    equal, notEqual, lessThan, lessOrEqual, greaterThan, greaterOrEqual
    and, or
    not
    isIn, isNotIn
    if
    uppercase
    lowercase
    substring
    trimBlanks
    concat
    replace
    matches
    formatNumber
    formatDatetime
    dateDaysSinceYear
    dateSecondsSinceYear
    dateSecondsSinceMidnight

**Comment by ligadata-william** [comment]
This is an ongoing effort. Closing as this is part of our sprint to sprint.
