### ISSUE TITLE
Deliver tests to validate provided user defined functions - UDFs

### ISSUE THREAD

**Issue by edifecs-pradeep** [LigaData/Kamanja#148]
Please deliver tests to validate the UDF's are implemented and functioning properly.
abs 
AgeCalc 
And 
AnyBetween 
AsCompressedDate 
AsSeconds 
Avg 
Between
ceil 
CollectionLength 
CompressedTimeHHMMSSCC2Secs 
ContainerFilter
ContainerMap 
Contains 
ContainsAll 
ContainsAny 
Count 
dateDaysSinceYear
dateMilliSecondsSinceMidnight 
dateSecondsSinceMidnight
dateSecondsSinceYear 
Divide 
endsWith 
Equal 
exp 
First 
floor 
Get
GetArray 
GreaterOrEqual 
GreaterThan 
If 
incrementBy 
Intersect 
IsIn
IsNotIn 
Last 
LessOrEqual 
LessThan 
ln 
log10 
lowercase 
MakeOrderedPairs
MakePairs 
MakeStrings 
Max 
Median 
Min 
Minus 
Multiply 
MultiSet 
Not
NotAnyBetween 
NotEqual 
Now 
Or 
Plus 
pow 
Product 
Put 
round 
sqrt
startsWith 
substring 
Sum 
threshold 
Timenow 
ToArray 
ToSet 
trimBlanks
Union 
uppercase 
YearsAgo

**Comment by ligadata-william** [comment]
As with #147.
