### ISSUE TITLE
kamanja 1.6.1 webservice is broken

### ISSUE THREAD

**Issue by asfour75** [LigaData/Kamanja#1498]
When try to start the kamanja webservice (kamanja start webservice) .. I get the following error:
> ./kamanja start webservice
Error: Could not find or load main class com.ligadata.metadataapiservice.APIService

The code source code shows the file (APIService) does exist, but the generated jar file ($KAMANJA_HOME/lib/system/metadataapi_2.11-1.6.1.jar) seems not showing any !

> jar tvf $KAMANJA_HOME/lib/system/metadataapi_2.11-1.6.1.jar

**Comment by ligadata-william** [comment]
There was an issue where easyInstallKamanjaExperimental.sh wasn't copying over the proper jar, which is actually metadataapiserver_2.11-{KamanjaVersion}.jar. This has been fixed. The binaries distributed should be good for 1.6.2 on. If this is an issue for 1.6.1 binaries and you didn't build it, then please reopen this issue and I can ensure the correct jars exist in the 1.6.1 binaries.
