### ISSUE TITLE
Multi-cluster: Failed to add the model

### ISSUE THREAD

**Issue by edifecs-pradeep** [LigaData/Kamanja#151]
When I removed a model from running engine and tried to add it back, I got an error messages that says "Fail to add the model"

Repro Steps:
 1. Start le3 and le5 engine as cluster
 2. while both engine are running remove Model (COPDv1)  using le5
 3. System will display (Model was removed successfully) 
 4. Add the model again to the metadaAPI

Expected:
    Model was added successfully to the MetadataAPI

Actual:

ERROR [main] - While processing Apply function 'if' found in DerivedField 'CATI_Rule1b'...
ERROR [main] - if statement encountered that does not have 3 parts... a predicate, a true action and a false action.
ERROR [main] - only functional form ('if (predicate) trueAction else falseAction') supported.

TRACE [main] - Failed to compile the model definition com.ligadata.olep.metadata.AlreadyExistsException: Model System.COPDRiskAssessment already exists.
Results as json string =>
{
  "APIResults" : {
    "statusCode" : -1,
    "statusDescription" : "Failed to add the model:",
    "resultData" : "Error in producing scala file or Jar file.."
  }

To verify model already exist as message suggested, 
I did the following:

1. From the MetadataAPI 
   a) select get all models 3
   b) check if COPDv1.xml model already exist

Actual Message:
     Enter your choice: 3
      Sorry, No models available in the Metadata

**Comment by ligadata-william** [comment]
Closing due to age and a lack of response.
