### ISSUE TITLE
When Kamanja runs using the Elasticsearch output adapter, the process hangs when trying to kill

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1510]
After using ctrl+c, kill and kill -9 on the KamanjaManager process, it hangs, failing to shut down if it is configured to use the Elasticsearch output adapter.

**Comment by ligadata-saleh** [comment]
We already told them CDA team to use only crt-c or kill -15 to stop the engine , kill-9  cuz the lose of some data .

**Comment by ligadata-pokuri** [comment]
@ligadata-saleh , when we give bad data (bad json data) to ES, it keeps on retrying that to write & fails. If we stop the engine ES does not go down and keep on retrying to write. We have to break from that infinite loop.

**Comment by ligadata-saleh** [comment]
What will happen to the data if we exit the loop , should we write it somewhere ? To kafka and read them from there or but them on disk , also right now am just sending a message if fail , did we add retry method to the output adapter ?

**Comment by ligadata-pokuri** [comment]
@ligadata-saleh , if the data itself is wrong, you can never add it to ES. do we keep on retrying forever?

**Comment by ligadata-pokuri** [comment]
We have plan to add failover stuff for output adapters. At this moment we will lose the data if anyone does kill -9

**Comment by ligadata-saleh** [comment]
@ligadata-pokuri we dont retry at all rigt now , i didnt add a retry method tell this moment , we only return a message failer to the logs .

**Comment by ligadata-saleh** [comment]
fixed in https://github.com/LigaData/Kamanja/pull/1511

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
