### ISSUE TITLE
Daas API Input isn't installed by default with Kamanja. Only exists in source.

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#1554]
In order to enable the Daas API Input feature for Kamanja, the message definition, model definition and configuration need to be added as a normal application. However, these files are not available in a Kamanja installation by default. They can only be found by going to the source code. This isn't a valid use-case for any user.

**Comment by ligadata-pokuri** [comment]
Fixed it in https://github.com/LigaData/Kamanja/pull/1559 pull request. Now we are creating DaaS directory under Kamanja-{KamanjaVersion}_{ScalaVersion} and copying all contents from trunk/MetadataAPI/src/main/resources/daas in the package.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
