### ISSUE TITLE
add 5 missing PMML functions 

### ISSUE THREAD

**Issue by ligadata-greg** [LigaData/Kamanja#212]
In this Google worksheet, 
https://docs.google.com/a/ligadata.com/spreadsheets/d/11N0pinrUPBTEzsLXmIk2SMAF43CmGEtHluxhholXebs/edit?usp=sharing

I made a list of PMML and Fatafat functions, showing Fatafat gaps:
* concat
* formatDatetime
* formatNumber
* matches      (i.e. regular expressions)
* replace        (i.e. regular expressions)

We are moving to being compatible.  All functions will need to be implemented.

--------------------------------------------------------------------------------
email from Rich, sent 2/23 in email "Fatafat Q&A that may help in pre-sales" 

c) We also have several forms of concatenation of strings and it is trivial to add others.  At the moment 'def Plus(str: String, str: String)' and 'def Plus(exprs : Array[String])' are available.  With the recent extension to support indefinite arity functions, it will be easy to add Plus(str : String*) which would allow any number of string arguments to be supplied to Plus.  The mapping of 'concat' to Plus is a one line change inside the compiler.

We have not implemented regular expressions (PRE or otherwise).  Regular expressions are builtin to Scala.  It would not be difficult to add this functionality if there was a business case for it.  I suggest we take the opportunity to add these features when such a case presents itself.

d) The formatting functions for date are trivial to add.  There is extensive Date and Time support in the core udf lib via the 'joda' libs. See http://www.joda.org/joda-time/apidocs/ for what can be done.  The c-type format strings are generally supported in Scala as well.  Someone has to write the "print" functions.

--------------------------------------------------------------------------------
http://www.dmg.org/v4-2-1/BuiltinFunctions.html#concat
concat

Returns a string as a result of the concatenation of two or more parameters.
Pseudo-declaration of PMML built-in function concat:

  <DefineFunction name="concat" dataType="string">
    <ParameterField name="x"/>
    <ParameterField name="y"/>
    ...
    See XQuery fn:concat
    ...
  </DefineFunction>
Example: Concatenates field month, constant value "-" and field year.

<Apply function="concat">
  <FieldRef field="month"/>
  <Constant>-</Constant>  
  <FieldRef field="year"/>  
</Apply>
Assuming month="2" and year="2000" the result corresponding to this Apply element is "2-2000".

--------------------------------------------------------------------------------
http://www.dmg.org/v4-2-1/BuiltinFunctions.html#formatnumber

formatNumber

Formats numbers according to a pattern. The pattern uses the Posix descriptors as used, e.g., in the C function printf.
Pseudo-declaration of PMML built-in function formatNumber:

  <DefineFunction name="formatNumber" dataType="string">
    <ParameterField name="input" optype="continuous"/>
    <ParameterField name="pattern" dataType="string"/>
    ... implementation built-in ...
  </DefineFunction>
Example: Convert a number in the field Num into a string of length 3 with leading blanks.

<Apply function="formatNumber">
  <FieldRef field="Num"/>
  <Constant>%3d</Constant>
</Apply>
Assuming Num=2 the result corresponding to this Apply element is the string " 2".

--------------------------------------------------------------------------------
http://www.dmg.org/v4-2-1/BuiltinFunctions.html#formatdatetime

formatDatetime

Formats date and time value according to a pattern. The pattern is a Posix descriptors as used, e.g., in the C function strftime or the Unix command date.
Pseudo-declaration of PMML built-in function formatDatetime:

  <DefineFunction name="formatDatetime" optype="categorical"> 

    <ParameterField name="input" optype="ordinal"/> 

    <ParameterField name="pattern" dataType="string"/>
    ... implementation built-in ...
  </DefineFunction>
input must be a date or time or dateTime.

Example: Format a date value as 'Month/Day/Year'.

<DerivedField name="StartDateUS" dataType="string" optype="categorical">
  <Apply function="formatDatetime">
    <FieldRef field="StartDate"/>
    <Constant>%m/%d/%y</Constant>
  </Apply>
</DerivedField>
With StartDate being the date August 20th, 2004 the result is StartDateUS="08/20/04".

--------------------------------------------------------------------------------
http://www.dmg.org/v4-2-1/BuiltinFunctions.html#replace

--------------------------------------------------------------------------------
http://www.dmg.org/v4-2-1/BuiltinFunctions.html#matches

--------------------------------------------------------------------------------

**Comment by ligadata-william** [comment]
Functionality has been added. Closing due to age and lack of response.
