### ISSUE TITLE
Failed to down load jar fo the object(pmml.booleanblock.100)

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#223]
Getting below error messages when I start engine. 

ERROR [main] - Failed to download the Jar of the object(pmml.booleanblock.100): Key Not found
ERROR [main] - Failed to download the Jar of the object(pmml.dateminus.100): Key Not found
ERROR [main] - Failed to download the Jar of the object(pmml.longblock.100): Key Not found

**Comment by ligadata-william** [comment]
The fix has been in for several months. Closing due to age and lack of response.
