### ISSUE TITLE
PMML UDF - random()

### ISSUE THREAD

**Issue by ligadata-greg** [LigaData/Kamanja#230]
This is a new feature, but one I know would be used and should be simple to implement.  The priority is consistency with other PMML functions with respect to syntax or other functionality.  Keep the implementation simple, parameters can map to the Java function or library definition used.

USE:
Bringing new models into production gradually (i.e. first 0.1%, then 1%, then 5%, then 100% replacing the old model).  Especially when going from top-down rules to the first bottom up model (i.e. neural net), this can be very important.

if (0.01 < random()) then
   output_score = new_model_score
else
   output_score = old_model_score

SPECIFICATION:
- uniform random distribution - there is an equal probability to generate a number from 0.0-0.1, 0.2-0.3, 0.9-1.0.   http://en.wikipedia.org/wiki/Uniform_distribution_(continuous)    This is in contrast with other kinds of distributions (not requested) such as Gaussian

(pseudo-code suggestion)
- random() - generate a uniform random number from 0.0 - 1.0
- random(seed=10) - given this random number seed, always generate the same list of random numbers
- random(min=10, max=100) - generate a random number in the range of 10 to 100 (including each end point).

**Comment by ligadata-william** [comment]
@ligadata-greg is this still a desired feature for KPMML or should I close it?

**Comment by ligadata-damian** [comment]
@ligadata-greg Can we close this ticket?

**Comment by ligadata-greg** [comment]
we can close it
