### ISSUE TITLE
Unknown objectType SortedSetTypeDef in zookeeper notification, notification is not processed ..

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#240]
Repro-steps

1. Start kafka, zoookeeper
2. Start engine,
3. Start MetadataAPIService
3. Push data through kafka queue

Expected:
No error 

Actual:
 Engine show bellow error messages

INFO [main-EventThread] - A jar file already exists, and it's size (218675)  matches with the size of the existing Jar (metadata_2.10-1.0.jar,218675) of the object(system.demo03_05_1713_visit_wrapper.1692140), no need to download.
ERROR [main-EventThread] - Unknown objectType ArrayTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType ArrayBufTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType SortedSetTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType ImmutableMapTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType ImmutableMapTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType ArrayTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType MapTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType MapTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType SetTypeDef in zookeeper notification, notification is not processed ..
ERROR [main-EventThread] - Unknown objectType TreeSetTypeDef in zookeeper notification, notification is not processed ..
 INFO [main-EventThread] - Processing Jar /home/le/dev/OnLEPInstall/lib/application/system_demo03_05_1713_visit_message_1692140.jar
 INFO [main-EventThread] - Jar /home/le/dev/OnLEPInstall/lib/application/system_demo03_05_1713_visit_message_1692140.jar added to class path.
 INFO [main-EventThread] - Processing Jar /home/le/dev/OnLEPInstall/lib/system/basetypes_2.10-0.1.0.jar
 INFO [main-EventThread] - Jar /home/le/dev/OnLEPInstall/lib/system/basetypes_2.10-0.1.0.jar added to class path.

**Comment by ligadata-william** [comment]
The fix has been available for several months. Closing due to age and lack of response.
