### ISSUE TITLE
[Engine - Hbase] Failed to remove type since the type is not found in the cache - the list should display the existing types only

### ISSUE THREAD

**Issue by ligadata-omar** [LigaData/Kamanja#251]
Steps to Reproduce:
- run the API
- select the option [21] Remove Type
- Select any type from the list  to remove it. ex : 66

Expected Result:
If the type does not  exist, the API should not show it in the list to remove it.

Actual result:
An error is displayed and says: TRACE [main] - Type system.arrayofhl7.100 is not found in the cache 
Result as Json String => 
{
  "APIResults" : {
    "statusCode" : -1,
    "statusDescription" : "Failed to find type",
    "resultData" : "system.arrayofhl7.100"
  }
}

**Comment by ligadata-william** [comment]
Closing due to age. If this is still an issue, it can be reopened.
