### ISSUE TITLE
Support of embedded API Service for integration test

### ISSUE THREAD

**Issue by edifecs-hongyan** [LigaData/Kamanja#270]
During our last integration effort, we spent a lot of time tracking down the failed requests to the API service. The time we spent in which could have been reduced significantly if we had the ability to write some junit to test against the calls. Adding this capability also makes it possible to automate such integration tests in our build process which saves time spent in future integration efforts. Note, I suppose that the same is true if the engine can be easily embedded too.

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
