### ISSUE TITLE
[Enhancement] MetaDataAPI: Main menu option is not displayed on some lists such as Delete

### ISSUE THREAD

**Issue by ligadata-omar** [LigaData/Kamanja#271]
- Run the API and make sure that you have some containers that are added or any other object
- Select Delete container 
- Observe the list 

Expected Result:
Sometimes the User may change his mind to delete an object or he used this list by mistake so it is preferable to add an option to return to main menu instead typing anything to return to main menu . so he will not get confused what to do to return to main menu.

Actual Result:
The user has no any option to return to the main menu so he may get confused to how to return to the main menu in case he changed his mind about deletion an object

Note: this is just an enhancement and would be good to apply it on all other objects with all type of actions (lists)

**Comment by ligadata-william** [comment]
This is no longer valid. All metadata commands may now be run in a single-line. Closing.
