### ISSUE TITLE
How can we decipher Model result sections?

### ISSUE THREAD

**Issue by edifecs-pankaj** [LigaData/Kamanja#280]
How can we decipher Model result section as below, rather than iterating over and removing elements.

Is there documentation to explain what this is and how to influence how it’s being created?

I saw this JSON structure is being created in ModelResult class in the engine

"ExecutionTime":"2015-01-26T16:53:42.656-08:00",
         "EventDate":1422259242656,
         "TxnId":100000000000021,
         "ModelName":"com.ligadata.pmml.System_COPDRiskAssessment_100",
         "uniqKey":"{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":0}",
         "uniqVal":"{\"Version\":1,\"Offset\":1393}",
         "ModelVersion":"100",
         "DataReadTime":"2015-01-26 16:53:42.620",
         "xformCntr":1,
         "ElapsedTimeFromDataRead":35994
      }

**Comment by ligadata-william** [comment]
This issue is no longer valid. Closing.
