### ISSUE TITLE
MetadataAPIService: Failed to download ar pmmludfs_2.10-1.0.jar of the object(pmml.dateblock.100)

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#297]
Repro Steps:
Start zookeeper 
cd ~/dev/Fatafat/trun
sbt
project MetadataAPIService
run --config /home/le/EngineCassConfigs/config/MetadataAPIConfig.properties

Expected;
All jars downloaded successfull

Actual:
Failed to download the Jar of the object(pmml.dateblock.100's dep jar pmmludfs_2.10-1.0.jar)

ERROR [metadata-api-service-akka.actor.default-dispatcher-2] - Failed to download the Jar of the object(pmml.dateblock.100's dep jar pmmludfs_2.10-1.0.jar): Failed to verify whether a download is required for the jar pmmludfs_2.10-1.0.jar of the object(pmml.dateblock.100): Key Not found

**Comment by ligadata-william** [comment]
Fixed for months. Closing.
