### ISSUE TITLE
MetadataAPIService still shows messages when removed thru UI API Command Line

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#308]
Repro Steps:
1. Add HL7 thru UI API Command Line
2. Open Postman
3. Get: http://10.30.51.14:8081/api/keys/Message
4. Message is added to MetadataAPIService 
5. Thru command line remove HL7 message (Message removed successfully from UI)
6. Go back to postman and Get: http://10.30.51.14:8081/api/keys/Message

Expected
HL7 should be removed from MetadataAPIService 

Actual:
MetadataAPIService result data contains HL7 message

{
  "APIResults" : {
    "statusCode" : 0,
    "statusDescription" : "Object Keys",
    "resultData" : "system.demo03_06_1327_visit_wrapper.140331,system.hl7.100,system.demo03_06_1327_visit_message.140331,system.demo03_06_1327_visit_asserts.140331"
  }
}

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
