### ISSUE TITLE
Need the ability to set a Value to 'NULL' in mapped messages

### ISSUE THREAD

**Issue by edifecs-pradeep** [LigaData/Kamanja#319]
If you recall our 3 messages, ‘data’, ‘wrapper’ and ‘assert’ - the former 2 are incoming data and ‘assert’ is a synthetic one maintained by the rule.

We need a way to set a value from PMML such that the field is empty  (equivalent to scala None or SQL's NULL)

**Comment by ligadata-william** [comment]
This has been available for months. Closing due to age and lack of response.
