### ISSUE TITLE
 Model result returns empty value "" when At_High_Risk_for_COPD is false 

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#333]
Repro Steps: (Rule 1a)
Patient age > 40         |    48
Chronic Cough =        |      1

Set all other field to false (0)

Expected: 
Execute Rule 1a and model result should contain following:

At risk for copd = true 
At high risk for copd = false 

{
     "Name": "At_Risk_for_COPD",
    "Type": "Supplementary",
    "Value": "true"
},

{
	"Name": "At_High_Risk_for_COPD",
	"Type": "Supplementary",
	"Value": "false"
},

Actual: 
Model Result returns empty value "" for at high risk for copd 

{
     "Name": "At_Risk_for_COPD",
    "Type": "Supplementary",
    "Value": "true"
},

{
	"Name": "At_High_Risk_for_COPD",
	"Type": "Supplementary",
	"Value": ""
},

Here is mining schema for At high risk for COPD

<MiningSchema>
        <MiningField name="At_High_Risk_for_COPD" usageType="supplementary" optype="categorical" missingValueReplacement="false"/><MiningField>

**Comment by ligadata-william** [comment]
This has been available for several months. Closing due to age and lack of response.
