### ISSUE TITLE
Metadata/REST API section of Dev Guide needs to be explained more completely

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#334]
Hi Dan,
     The following Metadata/REST API needs a fuller explanation:

https://github.com/ligaDATA/Kamanja/wiki/Developer%27s-Guide#k-metadatarest-api

You had researched other sites and found that you liked the way they explained their API.

Please take a look and let me know revised content.
thanks,
alison

**Comment by ligadata-william** [comment]
Closing as verified.
