### ISSUE TITLE
Document how to implement a "CompoundStatement" in PMML

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#351]
Greg has the following suggestion:

"I would suggest this get added to the documentation somewhere.  I am very tight on time this week, but I could have more time next week.  Can you help track adding this to the docs, and remind me?  This would help people used to procedural programming better understand functional programming like Scala.

------------------------------------------------------------------------------
I wanted a PMML structure like:
<CompoundStatement>
    :
</CompoundStatement>
to implement a compound statement to more easily match "procedural" pseudo code, for situations like:

if (conditionA) then
   <CompoundStatement1>
   </CompoundStatement1>
else
   <CompoundStatement2>

   if (conditionB) then
       <CompoundStatement3>
       </CompoundStatement3>

   </CompoundStatement2>

My understanding is that the following structure is how to implement my objective:

Use the following as a way to implement a compound statement, and never use the boolean variable "CompoundStatement".  However, that naming would make code readability MUCH BETTER, in my humble opinion, to read and interpret the logic.

<DerivedField name="CompoundStatementN" dataType="boolean" optype="categorical">
   <Apply function="and">
       :
   </Apply>
</DerivedField>

NOTE:  it is the last statement in the block that can be used to determine the return value.  Returning a value for the "and" function needs to be boolean.  The "and" function is just used as a function which supports an arbitrary number of slots (or statements in this case).  The "or" function would be equivalent, but not "exp" "

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
