### ISSUE TITLE
Pass MetadataAPICofig.properties config file as command line argument error

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#384]
Repro Steps:
1. Start zookeeper, kafka and cassandra
2. Run MetadataAPIService 

Expected:
if we don't passed config file as command line argument then config file defaults to /home/le/MetadataAPIConfig.properties

Actual:

ERROR [run-main-0] - Config File defaults to /home/le/MetadataAPIConfig.properties
ERROR [run-main-0] - One Could optionally pass a config file as a command line argument:  --config myConfig.properties
ERROR [run-main-0] - The config file supplied is a complete path name of a  json file similar to one in github/Fatafat/trunk/MetadataAPI/src/main/resources/MetadataAPIConfig.properties

**Comment by ligadata-william** [comment]
This issue isn't valid anymore as this piece has been rewritten. Closing until it re-emerges.
