### ISSUE TITLE
better naming & doc for Put() and setField()

### ISSUE THREAD

**Issue by ligadata-greg** [LigaData/Kamanja#404]
Put is used for updating either a field in the transaction or data dictionaries.  There is also a version that updates some kv store through the EnvContext by specifying container key, item key, and some MessageContainerBase derivative (i.e., a message or container).

The setField updates fields in the container or message.  It may be that Put can be used for that as well.. I don't remember.   More meaningful macro/function names and/or some clear documentation on these elements seems appropriate.  Why don't we open a bug on this and we will try to address this. - Rich

(I logged this bug at Rich's suggestion)

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
