### ISSUE TITLE
Review adapters section of wiki

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#434]
Please review the 3 adapters section of wiki

Extending Input and Output Adapters
https://github.com/ligaDATA/Fatafat/wiki/Developer%27s-Guide#h-extending-input-and-output-adapters

Extending Storage Adapters
https://github.com/ligaDATA/Fatafat/wiki/Developer%27s-Guide#i-extending-storage-adapters

Extending Types
https://github.com/ligaDATA/Fatafat/wiki/Developer%27s-Guide#j-extending-types

**Comment by ligadata-william** [comment]
This is no longer valid. Closing.
