### ISSUE TITLE
Failed to save a model

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#458]
Repro Steps:
1. Add messages, model and function
2. Start engine 

Expected 
No errors 

Actual 
Failed to save Model 

ERROR [main-EventThread] - Failed to Save the object(system.demo05_06_1131_visit.000002000066000933): Model system.demo05_06_1131_visit  should be higher than existing models.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
