### ISSUE TITLE
Get All Functions is not showing all functions 

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#463]
Precondition

Pull ligadata code drop 

Assumption 
Zookeeper, kafka and cassandra are already running 

Repro Steps 

1. Upload engine configurations, messages, function, and model 
2. Start engine 
3. Run ApplicationMetadata.sh
4. Select 23: Get all functions 

Expected 
Show all functions 

Actual
Enter your choice: 23
Invalid choice 23,start with main menu...

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
