### ISSUE TITLE
Add Concept failed

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#464]
Precondition

Pull ligadata code drop

Assumption
Zookeeper, kafka and cassandra are already running

Repro Steps

   1. Upload engine configurations, messages, function, and model
   2.  Start engine
   3. Run ApplicationMetadata.sh
   4.  Select 26: Add Concept 

Expected
Show concept menu 

Actual
Enter your choice: 26
Result as Json String =>
{
  "APIResults" : {
    "statusCode" : 0,
    "functionName" : "AddConcepts",
    "resultData" : null,
    "status/error Description" : "Concept Added Successfully:\n  {\"Concepts\" : [\n  {\"NameSpace\":\"Ligadata\",\n  \"Name\":\"ProviderId\",\n  \"TypeNameSpace\":\"System\",\n  \"TypeName\" : \"String\",\n  \"Version\"  : \"100\"} ]\n  }\n"
  }
}

**Comment by ligadata-william** [comment]
Add concept is currently unsupported. Closing as invalid.
