### ISSUE TITLE
Update concept failed 

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#465]
Precondition

Pull ligadata code drop

Assumption
Zookeeper, kafka and cassandra are already running

Repro Steps

    Upload engine configurations, messages, function, and model
    Start engine
    Run ApplicationMetadata.sh
    Select 28: Update Concept

Expected
Show concept menu

Actual
Enter your choice: 28
Result as Json String =>
{
  "APIResults" : {
    "statusCode" : 0,
    "functionName" : "UpdateConcepts",
    "resultData" : null,
    "status/error Description" : "Concept Updated Successfully:\n  {\"Concepts\" : [\n  {\"NameSpace\":\"Ligadata\",\n  \"Name\":\"ProviderId\",\n  \"TypeNameSpace\":\"System\",\n  \"TypeName\" : \"String\",\n  \"Version\"  : \"100\"} ]\n  }\n"
  }
}

**Comment by ligadata-william** [comment]
Concepts are currently unsupported. Closing as invalid.
