### ISSUE TITLE
MetadataAPIService activate model is not working

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#469]
Precondition:
Engine is running and messages, functions and models are already uploaded

Assumption:
Model is uploaded to the engine and deactivated 

Repro-Steps

1. Run MetadataAPIService
2. Open Chrome
3. Enter http://10.30.00.00:8081/api/activate/Model/system.demo05_06_1131_visit.000002000066000933

Expected Result:
Model is activated successfully

Actual:
APIResults: {
statusCode: -1,
functionName: "MetadataAPIService",
resultData: null,
status/error Description: "Invalid key: model"
}
}

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
