### ISSUE TITLE
Storage documentation

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#473]
Hi Pokuri,
    On the wiki at:

https://github.com/ligaDATA/Kamanja/wiki/Administration-and-Monitoring#common-issues

The 7th bullet down talks about the distinctions between Cassandra/HBase and the TreeMap/HashMap. I would like to add a short section about our storage and the kv stores. I understand that the Metadata API and the engine use kv stores a lot. 

My question is:

1) Would it be possible to provide me with a short paragraph about storage and kv stores?

2) Do you think this is important to write about? 

thanks,
alison

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
