### ISSUE TITLE
Installation documentation issues

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#476]
1) Ahmed Sarie says that as an installer, he doesn't know the definition of a container, message, or model  in:

https://github.com/ligaDATA/Fatafat/wiki/Installing-and-Running-Fatafat#e-running-sample-applications

2) We should add what happens after applying the steps, whether they are created in the background in one of the previous scripts. We should add more explanation of the expected result like Cloudera does. He wants to know when each of the created components is doing in the engine.

3) Furthermore, Java command did not work for him so he thinks it is worth mentioning that the commands depend on the Linux repository and we can never sync our wiki with it (not sure what this means). Maybe a step to check the installed Java will be useful for people who aren't familiar with Java-based systems. In his case, he installed Java 8 because the command on the wiki was getting him java 1.7 jre and he needed the "openjdk development" not the runtime, so when he ran the bash <InstallDirectoryPath>/bin/SetPaths.sh <kafkaDirectoryPath> command he was getting an error.

4) Also, in running sample applications, after running bash ClusterMetadata.sh comand in STEP #1, he gets a list with numbers, and on the wiki, it says we should enter 36, but 36 doesn’t do anything.  He asked Saleh and he told him it is 37 so he chose that and then he got 2 options to choose, and there is nothing mentioned on the wiki about this telling which option we should select (he assumed it is the first option but nothing happened after, and then he pressed 44 to exit) going to step 2.

5) Also, in running sample applications, in STEP #2 after step (a, b and c) he gets 2 options like the previous point and he chose 1 again - this needs to be mentioned.

6) In running sample applications, in STEP #2, the sub-steps inside this section are the steps to run the application number 2 not 1, as in the last step he was supposed to run the shell script (bash <InstallDirectoryPath>/input/<application-name>/bin/InitKvStores.sh) and application number 1 doesn't have that file.

7) After selection, the healthcare sample application, when we start creating the container, message, and model, we are getting some options, personally he was choosing option number 1, but there is nothing mentioned regarding these options or at least the difference between each.

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
