### ISSUE TITLE
Replace "What is the Mechanism to Suppress or Emit an Output Record".

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#479]
Replace "What is the Mechanism to Suppress or Emit an Output Record" with:

Choosing Model Results

In order for Fatafat to emit output, one of the rules in the RuleSet must
return its "score" value as opposed to the "defaultScore" value given on
the RuleSet. When this is accomplished, all of the fields described in the
MiningSchema section that have a usageType of either "predicted" or
"supplementary" are sent to the engine for further processing, including
the formation of any output messages that have been associated with the
model. (Alison, ask Tulasi exactly how this association is made... it may
not be with the model but with the incoming message... correct that as
needed).

If you would always like to emit output, make sure that at least one of the
rules is satisfied. This could be a faux rule that always returns its
score. Use the "firstHit" criterion on the RuleSetSelectionMethod and make
that faux "always true" rule the last one in the RuleSet. The other
approach is to set your predictions by putting them into a DataField
designed for this purpose; then it is just a matter of setting your
SimplePredicate up to fire in a postive way, producing the non-default
score.

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
