### ISSUE TITLE
Container System.EnvCodes exists in both the hello world and healthcare model apps

### ISSUE THREAD

**Issue by ligadata-rich** [LigaData/Kamanja#486]
From my post to vexing  Ahmed Sarie and Ahmed Y AlSarie who are trying to install and run the Fatafat sample applications:

The issue you are experiencing is that the name of the container chosen for the "hello world" application - namely EnvCodes - is the very same name as one of the containers used in the medical application model app. This causes a message like "AlreadyExistsException: Higher active version of Container System.EnvCodes already exists in the system"

This is unfortunate.  These names should not be the same.  Since the containers have the same namespace and name, only one can be fruitfully used at any one time.  To test both applications, test them one at a time.  After testing hello world, use the metadata api to delete the container EnvContext.  Then proceed to load the containers, messages and model for the medical model app.

You have found a good bug, and illustrate a short coming in our current implementation.  We need to support user defined namespaces so that there are no name clashes.  I will add this to our Issues.  Something will be done about this before the release of the product to the open source community.

**Comment by ligadata-william** [comment]
This has been fixed for some time. Closing.
