### ISSUE TITLE
New Creating UDFs section

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#493]
Hi Rich,
     Here are some of your comments:

1) I will send you a full replacement for the "Creating User-Defined Functions" portion soon. 

2) There is nothing more to say about the macros at this time. It will be revised when we eliminate some of the macros by introducing an alternative way to access system state... a few weeks from now I think. 

3) Same with constants. A new feature will be added to the Constants that will replace the need for 75% of the macros currently defined.

Please send me info on these 3 points.

thanks,
alison

**Comment by ligadata-william** [comment]
Closing as verified.
