### ISSUE TITLE
Provide a feature to be able to clean all databases

### ISSUE THREAD

**Issue by ligadata-danielramos** [LigaData/Kamanja#497]
Provide a feature to be able to clean all databases without having to restart the engine or the MetadataAPIService. A DB tool might be able to do this, but it’d have to extract all the metadata from the database first, then set all the paths on zookeeper to properly update all engine’s and rest servers of the delete prior to deletion of kafka and zookeeper data directories.

That being said, an api to cleanse metadata and update running services might not be a bad idea for testing purposes and zookeeper data can be cleaned programmatically as well by deleting and recreating the base nodes. The version of Kafka we currently use doesn’t possess the capability to delete topics (which are not held in the message directories) and messages can only be removed from said topics by deleting the data directories.

**Comment by ligadata-william** [comment]
This has been implemented as part of the CleanUtil tool. Closing.
