### ISSUE TITLE
Blocking : Master branch / Tag v1.0.4 does deploy properly due to joda-time-2.7.jar missing jar copy issues.

### ISSUE THREAD

**Issue by edifecs-pankaj** [ligaDATA/Kamanja#521]
1. Run easyInstall script with required parameters

2. Script stops with error:

![easyinstallscripterror](https://cloud.githubusercontent.com/assets/9060906/8125135/8f5b45b4-1100-11e5-87d4-f831d207b3ee.jpg)

I checked the .ivy2 folder and there are two other versions of jar available but not this one.

joda-time2.8.jar and joda-time2.3.jar

This is blocking us on clean deploy of the engine.

**Comment by ligadata-william** [comment]
T
