### ISSUE TITLE
POST After POST doesnt update Message but works fine with Models

### ISSUE THREAD

**Issue by edifecs-pankaj** [LigaData/Kamanja#535]
1/. Deploy Rule abc, using POST call to MetadataAPIService:
 i) deploys Messages and deploys PMML Model

Verify deployed Messages n Models

1)) http://{ip}:8081/api/keys/Messages:
{
  "APIResults" : {
    "statusCode" : 0,
    "functionName" : "GetAllObjectKeys",
    "resultData" : "Object Keys:system.{rulename}_visit_message.000006000088000883,system.{rulename}_visit_asserts.000006000088000883",
    "status/error Description" : "Successfully fetched all object keys"
  }
}

2)). http://{ip}:8081/api/keys/Messages: 
{
  "APIResults" : {
    "statusCode" : 0,
    "functionName" : "GetAllObjectKeys",
    "resultData" : "Object Keys:system.{rulename}_visit.000006000088000883",
    "status/error Description" : "Successfully fetched all object keys"
  }
}

2/. Deploy Same rule again with updated version using POST call to MetadataAPIService
   It should update both Messages and Models with updated version but Messages are not updated but Model gets deployed

Verify deployed messages n models

1)) http://{ip}:8081/api/keys/Messages:
{
  "APIResults" : {
    "statusCode" : 0,
    "functionName" : "GetAllObjectKeys",
    "resultData" : "Object Keys:system.{rulename}_visit_message.000006000088000883,system.{rulename}_visit_asserts.000006000088000883",
    "status/error Description" : "Successfully fetched all object keys"
  }
}

2)). http://{ip}:8081/api/keys/Messages: 
{
  "APIResults" : {
    "statusCode" : 0,
    "functionName" : "GetAllObjectKeys",
    "resultData" : "Object Keys:system.{rulename}_visit.000006000089000042",
    "status/error Description" : "Successfully fetched all object keys"
  }
}
Errors in MetadataAPISerive logs while updating Messages

![image](https://cloud.githubusercontent.com/assets/9060906/8302285/e86e2a1c-19b2-11e5-836a-5915958c1229.png)

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
