### ISSUE TITLE
New section on real-time data streaming

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#538]
Eshan writes:

In the wiki we do have a topic on how to load data into Fafafat using custom producer.
Its not real time. The sample applications too I believe show how to load data in offline mode in the form of data files.
I did see a post in user forum that says we need to support streaming real time data, the Twitter one. I guess work is on-going on the twitter one and is yet to be included in the sample applications though.
It would be great if we have a section for real time data streaming in the Fatafat wiki.

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
