### ISSUE TITLE
Support for using Apache Flume as the producer for Apache Kafka.

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#539]
Eshan writes:

Hi,
Apache Flume is data aggregation tool and supports many of the standard datasources like logs.
Extending Fatafat to support Flume will (in general for many standard sources) eliminate the need to write custom producer for Kafka.
The dev will only need to make changes in the configuration file for Flume to define the input to flume and link output of Flume to Kafka which easy than writing a custom producer.
I am thinking that the architecture with Flume would be like a flume agent on every data source machine which sends data to a single or multiple Kafka brokers.

For your reference:
https://flume.apache.org

If Flume is adopted, I will need to update the documentation

**Comment by ligadata-william** [comment]
Closing due to age and lack of response. If there is a desire for Apache Flume support in the future a feature request may be added.
