### ISSUE TITLE
Array of objects (data types) in the incoming JSON message (Heman Duraiswamy)

### ISSUE THREAD

**Issue by ligadata-danielramos** [LigaData/Kamanja#545]
Heman Duraiswamy: I have an array of objects in my incoming JSON type and wondering if there is a way we can handle this:

For example, one of the indicators has the following structure
{
                                "stixCommon" : "http://stix.mitre.org/common-1",
                                "simpleMarking" : "http://data-marking.mitre.org/extensions/MarkingStructure#Simple-1",
                                "stixVocabs" : "http://stix.mitre.org/default_vocabularies-1",
                                "cybox_major_version" : 2,
                                "opensource" : "http://hailataxii.com",
                                "type" : "cyboxVocabs:HashNameVocab-1.0",
                                "File_Name" : "config.jpg",
                                "version" : "1.1.1",
                                "id" : "edge:Package-2e494ff7-af02-4bec-a0ad-b790a8cc122f",
                                "timestamp" : "2015-06-15T12:51:35.709629+00:00",
                                "taxii" : "http://taxii.mitre.org/messages/taxii_xml_binding-1",
                                "FileObj" : "http://cybox.mitre.org/objects#FileObject-2",
                                "TOUMarking" : "http://data-marking.mitre.org/extensions/MarkingStructure#Terms_Of_Use-1",
                                "Marking_Structure" : [{
                                                                "color" : "WHITE",
                                                                "xsi:type" : "tlpMarking:TLPMarkingStructureType"
                                                }, {
                                                                "TOUMarking:Terms_Of_Use" : "zeustracker.abuse.ch | Abuse source[https://sslbl.abuse.ch/blacklist/] - As for all abuse.ch projects, the use of the SSL Blacklist is free for both commercial and non-commercial usage without any limitation. However, if you are a commercial vendor of security software/services and you want to integrate data from the SSL Blacklist into your products / services, you will have to ask for permission first by contacting me using the contact form [http://www.abuse.ch/?page_id=4727].'",
                                                                "xsi:type" : "TOUMarking:TermsOfUseMarkingStructureType"
                                                }, {
                                                                "simpleMarking:Statement" : "Unclassified (Public)",
                                                                "xsi:type" : "simpleMarking:SimpleMarkingStructureType"
                                                }
                                ],
                                "sighting_count" : 1,
                                "marking" : "http://data-marking.mitre.org/Marking-1",
                                "File_Format" : "jpg",
                                "tdq" : "http://taxii.mitre.org/query/taxii_default_query-1",
                                "cyboxCommon" : "http://cybox.mitre.org/common-2",
                                "cybox" : "http://cybox.mitre.org/cybox-2",
                                "tlpMarking" : "http://data-marking.mitre.org/extensions/MarkingStructure#TLP-1",
                                "Description" : "FileName: config.jpg | FileHash: c75c95b2caafcd5e03271cec085d21a7 |",
                                "edge" : "http://soltra.com/",
                                "condition" : "Equals",
                                "cybox_minor_version" : 1,
                                "Controlled_Structure" : "../../../../descendant-or-self::node()",
                                "Title" : "File: config.jpg",
                                "cyboxVocabs" : "http://cybox.mitre.org/default_vocabularies-2",
                                "content" : "c75c95b2caafcd5e03271cec085d21a7",
                                "cybox_update_version" : 0,
                                "stix" : "http://stix.mitre.org/stix-1",
                                "xsi" : "http://www.w3.org/2001/XMLSchema-instance"
                }

As you may see, the "marking_structure" is an array of filed types - how is this handled in our message definition?

Rich Johnson: Heman,

ArrayBuffers of containers can be represented in the messages.  It looks like you have heterogeneous elements in that marking structure, however.  It may be possible to prepare a container type for each variant and then in the message have an array of their Base Types... for example,

     {
           "Field" : {
                 "Name" : "Marking_Structure",
                 "Type"  :  "System.ArrayBufferOfBaseContainer"
            }
    },
    .
    .
    .

I may have the syntax wrong.  Tulasi, please chime in.

Regards,
Rich

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
