### ISSUE TITLE
Document how to set up Kerberos

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#558]
How it is used. How to config.

**Comment by ligadata-william** [comment]
This should still be documented. I'll assign this to myself to make a write-up.

**Comment by ligadata-alison** [comment]
William, we have a Kafka Kerberos section now. Is this sufficient?

**Comment by ligadata-alison** [comment]
William says the documentation is sufficient. Pokuri, please verify...

**Comment by ligadata-alison** [comment]
Pokuri, please verify that I can close?

**Comment by ligadata-pokuri** [comment]
@ligadata-william , close this if you are verified

**Comment by ligadata-william** [comment]
Closing as verified.
