### ISSUE TITLE
When MetadataAPIService fails process doesn't exit completely

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#567]
Whenever there is a failure that causes the APIService to fail, the process is still running but the service cannot be contacted, indicating it is not running. 

You can tell the process is still running by the repeated logging of a line that looks like this:

```
DEBUG [run-main-0-SendThread(localhost:2181)] - Got ping response for sessionid: 0x14eb7d99913003e after 0ms
```

**Comment by ligadata-yasser** [comment]
@ligadata-william 
please verify, pull request is #1195

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
