### ISSUE TITLE
Engine is not picking up new model if version doesn't change

### ISSUE THREAD

**Issue by ligadata-ramana** [ligaDATA/Kamanja#577]
Steps to reproduce
1. You could use HelloWorld example, add containers, messages and corresponding scala model
2. Run the engine
3. Using MetadataAPI menu, remove the model
4. update the scala file to include more log messages
5. Add the model again without changing version, it will go through
6. Engine notice both Remove and Add operations, but doesn't execute the new model

Pokuri is aware of what might be going wrong.

**Comment by ligadata-william** [comment]
Verified and closing.
