### ISSUE TITLE
MetadataAPIService (http://xx.xx.50.72:8081/) is not available after installing v1.0.5 release

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#583]
Pre-request 

Start zk, kafka, cassandra and engine
Run metadataAPIService
Started successfully 

Open browser 
Enter http://xx.xx.50.72:8081/

Expected:
API Results displayed

Actual 
This webpage is not available
Connection refused

**Comment by ligadata-william** [comment]
@ligadata-dan last I saw this was still an issue.

**Comment by ligadata-pokuri** [comment]
This is duplicate of https://github.com/LigaData/Kamanja/issues/723

**Comment by ligadata-yasser** [comment]
@ligadata-william 
please verify, pull request is #1195

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
