### ISSUE TITLE
Start Engine errors: Unable to load Status Info

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#586]
Pre-request
Install v1.0.5 release 

Start zk, kafka, cassandra and engine
Start Engine 

Expected:
Load status info successfully

Actual:
ERROR [main-EventThread] - getIntermediateStatusInfo() -- Unable to load Status Info

 WARN [main] - Cannot find LZ4 class, you should make sure the LZ4 library is in the classpath if you intend to use it. LZ4 compression will not be available for the protocol.
 WARN [main] - Property batch.size is not valid
 WARN [main] - Property buffer.memory is not valid
 WARN [main] - Property queue.size is not valid
 WARN [main] - Property queue.time is not valid
 WARN [main] - Property batch.size is not valid
 WARN [main] - Property buffer.memory is not valid
 WARN [main] - Property buffer.size is not valid
 WARN [main] - Property queue.size is not valid
 WARN [main] - Property queue.time is not valid
 WARN [main] - Property socket.receive.buffer is not valid
 WARN [main] - Property socket.send.buffer is not valid
 WARN [main] - session timeout [250] is less than connection timeout [30000]
 WARN [main] - session timeout [250] is less than connection timeout [30000]
 WARN [main] - session timeout [250] is less than connection timeout [30000]
 WARN [main] - session timeout [250] is less than connection timeout [30000]
 WARN [main] - session timeout [250] is less than connection timeout [30000]
 WARN [main] - session timeout [250] is less than connection timeout [30000]
FatafatManager is running now. Waiting for user to terminate with CTRL + CERROR [main-EventThread] - Data not found for key:{"T":"adapteruniqkvdata","K":["{\"version\":1,\"type\":\"kafka\",\"name\":\"testin_1\",\"topicname\":\"le-inbound\",\"partitionid\":0}"],"D":[0,0],"V":1}
ERROR [main-EventThread] - getIntermediateStatusInfo() -- Unable to load Status Info

**Comment by ligadata-william** [comment]
The error message no longer appears. Closing.
