### ISSUE TITLE
Start engine: Failed to load Wait Processing Info.

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#587]
Pre-request
Install v1.0.5 release

Start zk, kafka, cassandra and engine
Start Engine

Expected:
Load wait processing info successfully 

Actual:
ERROR [main] - Failed to load Wait Processing Info.

le@le-demo2:~/EngineCassConfigs/bin$ ./StartEngine.sh
ERROR [main] - Failed to load Wait Processing Info.
 WARN [main] - DO_AUTH remains unset
 WARN [main] - MODEL_EXEC_LOG remains unset
 WARN [main] - JAR_TARGET_DIR remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - ZOOKEEPER_CONNECT_STRING remains unset
 WARN [main] - SECURITY_IMPL_CLASS remains unset
 WARN [main] - AUDIT_IMPL_JAR remains unset
 WARN [main] - SECURITY_IMPL_JAR remains unset
 WARN [main] - FUNCTION_FILES_DIR remains unset
 WARN [main] - MESSAGE_FILES_DIR remains unset
 WARN [main] - COMPILER_WORK_DIR remains unset
 WARN [main] - CONTAINER_FILES_DIR remains unset
 WARN [main] - ZNODE_PATH remains unset
 WARN [main] - NOTIFY_ENGINE remains unset
 WARN [main] - SCALA_HOME remains unset
 WARN [main] - SERVICE_PORT remains unset
 WARN [main] - CLASSPATH remains unset
 WARN [main] - AUDIT_IMPL_CLASS remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - SSL_CERTIFICATE remains unset
 WARN [main] - SERVICE_HOST remains unset
 WARN [main] - CONCEPT_FILES_DIR remains unset
 WARN [main] - JAVA_HOME remains unset
 WARN [main] - MANIFEST_PATH remains unset
 WARN [main] - TYPE_FILES_DIR remains unset
 WARN [main] - MODEL_FILES_DIR remains unset
 WARN [main] - DO_AUDIT remains unset
 WARN [main] - JAR_PATHS remains unset
 WARN [main] - GIT_ROOT remains unset
 WARN [main] - CONFIG_FILES_DIR remains unset
 WARN [main] - ROOT_DIR remains unset
 WARN [main] - Cannot find LZ4 class, you should make sure the LZ4 library is in the class

**Comment by ligadata-william** [comment]
This has since been removed. Closing.
