### ISSUE TITLE
Start engine errore: Found more than one of NodeId:1 in Participents:{1,1}

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#588]
There is only single node id in engine configuration file, but start engine logs is throwing an error message that says it found multiple node id.

Pre-request
Install v1.0.5 release

Start zk, kafka, cassandra and engine
Start Engine

Expected:
NodeId = 1

Actual:
ERROR [main] - Found more than one of NodeId:1 in Participents:{1,1}. Waiting for 30000 milli seconds to check whether it is real duplicate or not.

 INFO [main-EventThread] - NodeId:1, IsLeader:false, Leader:1, AllParticipents:{1,1}
DEBUG [main-EventThread] - EventChangeCallback => Enter
 INFO [main-EventThread] - NodeId:1, IsLeader:false, Leader:1, AllParticipents:{1,1}
DEBUG [main-EventThread] - EventChangeCallback => Exit
DEBUG [main-SendThread(10.30.50.25:2181)] - Reading reply sessionid:0x14edb6eb1d2008c, packet:: clientPath:/ligadata/engineleader serverPath:/ligadata/engineleader finished:false header:: 8,12  replyHeader:: 8,308687,0  request:: '/ligadata/engineleader,T  response:: v{'_c_6e8c3204-221c-45f1-a4a9-6a104a742dea-latch-0000000014,'_c_168b43fc-ceb9-415e-8b7e-1a56e9fe0b23-latch-0000000013},s{3547,3547,1438105656093,1438105656093,0,28,0,0,0,2,308687}
DEBUG [main-SendThread(10.30.50.25:2181)] - Reading reply sessionid:0x14edb6eb1d2008c, packet:: clientPath:/ligadata/engineleader serverPath:/ligadata/engineleader finished:false header:: 9,12  replyHeader:: 9,308687,0  request:: '/ligadata/engineleader,F  response:: v{'_c_6e8c3204-221c-45f1-a4a9-6a104a742dea-latch-0000000014,'_c_168b43fc-ceb9-415e-8b7e-1a56e9fe0b23-latch-0000000013},s{3547,3547,1438105656093,1438105656093,0,28,0,0,0,2,308687}
DEBUG [main-SendThread(10.30.50.25:2181)] - Reading reply sessionid:0x14edb6eb1d2008c, packet:: clientPath:/ligadata/engineleader/_c_168b43fc-ceb9-415e-8b7e-1a56e9fe0b23-latch-0000000013 serverPath:/ligadata/engineleader/_c_168b43fc-ceb9-415e-8b7e-1a56e9fe0b23-latch-0000000013 finished:false header:: 10,4  replyHeader:: 10,308687,0  request:: '/ligadata/engineleader/_c_168b43fc-ceb9-415e-8b7e-1a56e9fe0b23-latch-0000000013,T  response:: #31,s{307992,307992,1438270447847,1438270447847,0,0,0,94253910697574529,1,0,307992}
ERROR [main] - Found more than one of NodeId:1 in Participents:{1,1}. Waiting for 30000 milli seconds to check whether it is real duplicate or not.

**Comment by ligadata-william** [comment]
Duplicate node ids are no longer able to start. Closing as fixed.
