### ISSUE TITLE
Start engine logs show warning even when Engine1Config.properties parameters are set correctly 

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#589]
Start engine logs show warning even when Engine1Config.properties parameters are set correctly 

Pre-request
Install v1.0.5 release

Start zk, kafka, cassandra and engine
Start Engine

Expected:
No warnings 

Actual:

DEBUG [main] - NODE_ID = Undefined
DEBUG [main] - API_LEADER_SELECTION_ZK_NODE = /ligadata
DEBUG [main] - ZK_SESSION_TIMEOUT_MS = 3000
DEBUG [main] - ZK_CONNECTION_TIMEOUT_MS = 3000
DEBUG [main] - DATABASE_LOCATION  = localhost
DEBUG [main] - DATABASE_HOST  = localhost
DEBUG [main] - DATABASE_SCHEMA = metadata
DEBUG [main] - NODE_ID = 1
DEBUG [main] - DATABASE = cassandra
 WARN [main] - DO_AUTH remains unset
 WARN [main] - MODEL_EXEC_LOG remains unset
 WARN [main] - JAR_TARGET_DIR remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - ZOOKEEPER_CONNECT_STRING remains unset
 WARN [main] - SECURITY_IMPL_CLASS remains unset
 WARN [main] - AUDIT_IMPL_JAR remains unset
 WARN [main] - SECURITY_IMPL_JAR remains unset
 WARN [main] - FUNCTION_FILES_DIR remains unset
 WARN [main] - MESSAGE_FILES_DIR remains unset
 WARN [main] - COMPILER_WORK_DIR remains unset
 WARN [main] - CONTAINER_FILES_DIR remains unset
 WARN [main] - ZNODE_PATH remains unset
 WARN [main] - NOTIFY_ENGINE remains unset
 WARN [main] - SCALA_HOME remains unset
 WARN [main] - SERVICE_PORT remains unset
 WARN [main] - CLASSPATH remains unset
 WARN [main] - AUDIT_IMPL_CLASS remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - SSL_CERTIFICATE remains unset
 WARN [main] - SERVICE_HOST remains unset
 WARN [main] - CONCEPT_FILES_DIR remains unset
 WARN [main] - JAVA_HOME remains unset
 WARN [main] - MANIFEST_PATH remains unset
 WARN [main] - TYPE_FILES_DIR remains unset
 WARN [main] - MODEL_FILES_DIR remains unset
 WARN [main] - DO_AUDIT remains unset
 WARN [main] - JAR_PATHS remains unset
 WARN [main] - GIT_ROOT remains unset
 WARN [main] - CONFIG_FILES_DIR remains unset
 WARN [main] - ROOT_DIR remains unset
DEBUG [main] - Opening datastore

**Comment by ligadata-william** [comment]
Closing as will not fix.
