### ISSUE TITLE
Add model UI console failed

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#593]
Pre-request
Install v1.0.5 release

Start zk, kafka, cassandra
Start Engine
Add metadata 
Add messages (successfully added messages)
Add model 

Enter your choice: 1
Pick a Model Definition file(pmml) from below choices
[1] /home/le/EngineCassConfigs/metadata/model/Pre_Certification_Requirement_Visit.xml
[2] Main Menu

Expected:
Model added successfully 

Actual: 
  "Result Description" : "Failed to Add Model:(pmml compile failed).000000000000000000000"

Enter your choice: 1
Pick a Model Definition file(pmml) from below choices
[1] /home/le/EngineCassConfigs/metadata/model/Pre_Certification_Requirement_Visit.xml
[2] Main Menu

Enter your choice: 1
DEBUG [main] - PmmlCompiler ctor ... begins
DEBUG [main] - compile begins
ERROR [main] - While processing Apply function 'booleanBlock' (70:42) found in DerivedField 'save_assertions' (67:99)...
ERROR [main] - selectMacro ...macroDef produced?  NO!! Either a function or a macro by this name must exist or perhaps the spelling or function signature is incorrect
ERROR [main] - While processing Apply function 'booleanBlock' (70:42) found in DerivedField 'save_assertions' (67:99)...
ERROR [main] - Function booleanBlock is not known in the metadata...
ERROR [main] - While processing Apply function 'DatePlus' (104:38) found in DerivedField '__macro__2' (103:94)...
ERROR [main] - selectMacro ...macroDef produced?  NO!! Either a function or a macro by this name must exist or perhaps the spelling or function signature is incorrect
ERROR [main] - While processing Apply function 'DatePlus' (104:38) found in DerivedField '__macro__2' (103:94)...
ERROR [main] - Function DatePlus is not known in the metadata...
ERROR [main] - While processing Apply function 'ID_GEN' (108:36) found in DerivedField '__macro__3' (107:95)...
ERROR [main] - selectMacro ...macroDef produced?  NO!! Either a function or a macro by this name must exist or perhaps the spelling or function signature is incorrect
ERROR [main] - While processing Apply function 'ID_GEN' (108:36) found in DerivedField '__macro__3' (107:95)...
ERROR [main] - Function ID_GEN is not known in the metadata...
ERROR [main] - While processing Apply function 'booleanBlock' (112:40) found in DerivedField 'rule_text' (111:95)...
ERROR [main] - selectMacro ...macroDef produced?  NO!! Either a function or a macro by this name must exist or perhaps the spelling or function signature is incorrect
ERROR [main] - While processing Apply function 'booleanBlock' (112:40) found in DerivedField 'rule_text' (111:95)...
ERROR [main] - Function booleanBlock is not known in the metadata...
ERROR [main] - Pmml compile completes... error count = 8... Scala compile abandoned... model definition will NOT be produced.
Results as json string =>
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Failed to Add Model:(pmml compile failed).000000000000000000000"
  }
}

**Comment by ligadata-william** [comment]
The menu system is not supported and adding custom UDFs has worked for a long time. Closing.
