### ISSUE TITLE
Failed to add Pre_Certification_Requirement model after pulling lates code drop (v1,0.5 release)

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#600]
Pre-request
Install v1.0.5 release

Start zk, kafka, cassandra
Start Engine
Add metadata
Add messages (successfully added messages)
Add model Pre_Certification_Requirement

Enter your choice: 1
Pick a Model Definition file(pmml) from below choices
[1] /home/le/EngineCassConfigs/metadata/model/Pre_Certification_Requirement_Visit.xml
[2] Main Menu

Expected:
Model added successfully

Actual:
************Error 1************
/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala:8: error: object EdifecsPmmlUdfs is not a member of package com.ligadata.pmml.udfs
************Error 2************
/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala:488: error: not found: value booleanBlock
        val rule_text = booleanBlock(if(Not(ctx.valueFor("__known__1").asInstanceOf[BooleanDataValue].Value))

************Error 3************
5 errors found
ERROR [main] - Compile for Pre_Certification_Requirement_Visit.scala has failed...rc = 1
ERROR [main] - Command used: ArrayBuffer(sh, -c, /usr/bin/scalac -cp /home/le/dev/OnLEPInstall/lib/system/metadata_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/basefunctions_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/sys

Enter your choice: 1
Pick a Model Definition file(pmml) from below choices
[1] /home/le/EngineCassConfigs/metadata/model/Flying_Under_the_Radar_At_Risk_for_COPD_Visit.xml
[2] /home/le/EngineCassConfigs/metadata/model/Pre_Certification_Requirement_Visit.xml
[3] /home/le/EngineCassConfigs/metadata/model/COPD_HIGH_ED_UTILIZER_NO_PCP_Visit.xml
[4] /home/le/EngineCassConfigs/metadata/model/COPD_CAT1_Rule1a1b_Visit.xml
[5] /home/le/EngineCassConfigs/metadata/model/Member_Leakage_Monitoring_Visit.xml
[6] /home/le/EngineCassConfigs/metadata/model/Blood_Pressure_Monitoring_Visit.xml
[7] /home/le/EngineCassConfigs/metadata/model/Stroke_Readmission_Risk_Alert_Visit.xml
[8] /home/le/EngineCassConfigs/metadata/model/Network_Leakage_Visit.xml
[9] Main Menu

Enter your choice: 2
DEBUG [main] - PmmlCompiler ctor ... begins
DEBUG [main] - compile begins
DEBUG [main] -

dump of the inputVars for the model metadata construction:
DEBUG [main] - ("assertions.needs_pre_certification", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Asserts_9000323000706_1438621039949", "system", "pre_certification_requirement_visit_asserts", false, null)
DEBUG [main] - ("msgHistoryInclIncomingMsgBases", "com.ligadata.FatafatBase.MessageContainerBase", "system", "messagecontainerbase", false, null)
DEBUG [main] - ("msg.inpatient_visit", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msg.admission_date_time", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msg.enterprise_master_patient_index", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msgHistoryInclIncomingMsg", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msg.emergency_visit_converted_to_inpatient_visit", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("gCtx", "com.ligadata.FatafatBase.EnvContext", "system", "envcontext", false, null)
DEBUG [main] - ("msg.admission_event", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msg.treatment_facility_identifier_namespace", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msg.first_name", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msg", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msg.precertification_complete", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] - ("msg.last_name", "com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233", "system", "pre_certification_requirement_visit_message", false, null)
DEBUG [main] -

dump of the outputVars for the model metadata construction:
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___CreateTS", "system", "integer")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___NotificationId", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___EMPId", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION", "system", "boolean")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_3_Value", "system", "boolean")
DEBUG [main] - ("__prediction__", "system", "boolean")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___RuleDescr", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_1_Type", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___EndTS", "system", "integer")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_2_Value", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_2_Type", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Score", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___RuleName", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_1_Name", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Frequency", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_3_Type", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_2_Name", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_1_Value", "system", "integer")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___last_name", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___RuleId", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Criteria_3_Name", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___Severity", "system", "string")
DEBUG [main] - ("NEEDS_PRE_CERTIFICATION___first_name", "system", "string")
DEBUG [main] - createJar begins
DEBUG [main] - write a copy of the generated source to /home/le/dev/OnLEPInstall/lib/system/pre_certification_requirement_visit.pmml
DEBUG [main] - compile Pre_Certification_Requirement_Visit
DEBUG [main] - scalac cmd used: ArrayBuffer(sh, -c, /usr/bin/scalac -cp /home/le/dev/OnLEPInstall/lib/system/metadata_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/basefunctions_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/messagedef_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/methodextractor_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmlcompiler_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/fatafatbase_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/bootstrap_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/joda-time-2.3.jar:/home/le/dev/OnLEPInstall/lib/system/joda-convert-1.6.jar:/home/le/dev/OnLEPInstall/lib/system/basetypes_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmludfs_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmlruntime_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-native_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-core_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-ast_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-databind-2.3.1.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-annotations-2.3.0.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-jackson_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-core-2.3.1.jar:/home/le/dev/OnLEPInstall/lib/system/log4j-1.2.17.jar:/home/le/dev/OnLEPInstall/lib/system/system_pre_certification_requirement_visit_message_9000323000706_1438621071422.jar:/home/le/dev/OnLEPInstall/lib/system/basetypes_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/metadata_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/system_pre_certification_requirement_visit_asserts_9000323000706_1438621054668.jar /home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala)
/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala:8: error: object EdifecsPmmlUdfs is not a member of package com.ligadata.pmml.udfs
import com.ligadata.pmml.udfs.EdifecsPmmlUdfs._
                              ^
/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala:405: error: not found: value booleanBlock
        var result : Boolean = if (save_assertions) { booleanBlock(new assertions_enterprise_master_patient_index_msg_enterprise_master_patient_index_setField(ctx, ctx.valueFor("assertions").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Asserts_9000323000706_1438621039949], ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233]).setField, new gCtx_value2_assertPartitionKey_assertions_Put(ctx, ctx.valueFor("gCtx").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.FatafatBase.EnvContext], "System.Pre_Certification_Requirement_Visit_Asserts", ctx.valueFor("assertPartitionKey").asInstanceOf[AnyDataValue].Value.asInstanceOf[scala.collection.immutable.List[String]], ctx.valueFor("assertions").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Asserts_9000323000706_1438621039949]).Put, true) } else { true }
                                                      ^
/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala:458: error: not found: value DatePlus
        val __macro__2 = DatePlus(ctx.valueFor("TODAY").asInstanceOf[IntDataValue].Value, "40 days")
                         ^
/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala:473: error: not found: value ID_GEN
        val __macro__3 = ID_GEN()
                         ^
/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala:488: error: not found: value booleanBlock
        val rule_text = booleanBlock(if(Not(ctx.valueFor("__known__1").asInstanceOf[BooleanDataValue].Value)) {if((ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("admission_event").asInstanceOf[Boolean]) && ((ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("inpatient_visit").asInstanceOf[Boolean]) || (ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("emergency_visit_converted_to_inpatient_visit").asInstanceOf[Boolean]))) {if(Not(ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("precertification_complete").asInstanceOf[Boolean])) {booleanBlock(booleanBlock(new assertions_needs_pre_certification_value3_setField(ctx, ctx.valueFor("assertions").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Asserts_9000323000706_1438621039949], true).setField, Put(ctx, "asserted", true), ctx.valueFor("assertions").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Asserts_9000323000706_1438621039949].get("needs_pre_certification").asInstanceOf[Boolean]), booleanBlock(Put(ctx, "NEEDS_PRE_CERTIFICATION", true), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_3_Type", "display"), Put(ctx, "NEEDS_PRE_CERTIFICATION___first_name", ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("first_name").asInstanceOf[String]), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_3_Name", "Pre-certification available"), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_2_Value", ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("treatment_facility_identifier_namespace").asInstanceOf[String]), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_1_Type", "display"), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_2_Type", "display"), Put(ctx, "NEEDS_PRE_CERTIFICATION___RuleName", "Pre_Certification_Requirement"), Put(ctx, "NEEDS_PRE_CERTIFICATION___EndTS", ctx.valueFor("__macro__2").asInstanceOf[IntDataValue].Value), Put(ctx, "NEEDS_PRE_CERTIFICATION___RuleId", "Pre_Certification_Requirement_ver1"), Put(ctx, "NEEDS_PRE_CERTIFICATION___CreateTS", ctx.valueFor("TODAY").asInstanceOf[IntDataValue].Value), Put(ctx, "NEEDS_PRE_CERTIFICATION___last_name", ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("last_name").asInstanceOf[String]), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_1_Value", ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("admission_date_time").asInstanceOf[Int]), Put(ctx, "NEEDS_PRE_CERTIFICATION___Score", "1"), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_2_Name", "Inpatient facility name"), Put(ctx, "NEEDS_PRE_CERTIFICATION___RuleDescr", "Identifies members who need pre-certification due to inpatient admit"), Put(ctx, "NEEDS_PRE_CERTIFICATION___NotificationId", ctx.valueFor("__macro__3").asInstanceOf[StringDataValue].Value), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_1_Name", "Inpatient admit date"), Put(ctx, "NEEDS_PRE_CERTIFICATION___EMPId", ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("enterprise_master_patient_index").asInstanceOf[String]), Put(ctx, "NEEDS_PRE_CERTIFICATION___Frequency", "Daily"), Put(ctx, "NEEDS_PRE_CERTIFICATION___Severity", "Critical"), Put(ctx, "NEEDS_PRE_CERTIFICATION___Criteria_3_Value", ctx.valueFor("msg").asInstanceOf[AnyDataValue].Value.asInstanceOf[com.ligadata.messagescontainers.System_Pre_Certification_Requirement_Visit_Message_9000323000706_1438621056233].get("precertification_complete").asInstanceOf[Boolean])))} else {true}} else {true}} else {true}, true)
                        ^
5 errors found
ERROR [main] - Compile for Pre_Certification_Requirement_Visit.scala has failed...rc = 1
ERROR [main] - Command used: ArrayBuffer(sh, -c, /usr/bin/scalac -cp /home/le/dev/OnLEPInstall/lib/system/metadata_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/basefunctions_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/messagedef_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/methodextractor_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmlcompiler_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/fatafatbase_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/bootstrap_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/joda-time-2.3.jar:/home/le/dev/OnLEPInstall/lib/system/joda-convert-1.6.jar:/home/le/dev/OnLEPInstall/lib/system/basetypes_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmludfs_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/pmmlruntime_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-native_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-core_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-ast_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-databind-2.3.1.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-annotations-2.3.0.jar:/home/le/dev/OnLEPInstall/lib/system/json4s-jackson_2.10-3.2.9.jar:/home/le/dev/OnLEPInstall/lib/system/jackson-core-2.3.1.jar:/home/le/dev/OnLEPInstall/lib/system/log4j-1.2.17.jar:/home/le/dev/OnLEPInstall/lib/system/system_pre_certification_requirement_visit_message_9000323000706_1438621071422.jar:/home/le/dev/OnLEPInstall/lib/system/basetypes_2.10-0.1.0.jar:/home/le/dev/OnLEPInstall/lib/system/metadata_2.10-1.0.jar:/home/le/dev/OnLEPInstall/lib/system/system_pre_certification_requirement_visit_asserts_9000323000706_1438621054668.jar /home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/Pre_Certification_Requirement_Visit.scala)
mv: cannot stat ‘com’: No such file or directory
ERROR [main] - unable to move classes to build directory, /home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit ... rc = 1
ERROR [main] - cmd used : mv com /home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit/
ERROR [main] - jarCode has failed... no jar produced
DEBUG [main] - #########################################################
DEBUG [main] - Dump model variables for diagnostic purposes:
DEBUG [main] - #########################################################
DEBUG [main] - modelClassName=com.ligadata.System_Pre_Certification_Requirement_Visit_9000323000706_1438621158659.pmml.Pre_Certification_Requirement_Visit
DEBUG [main] - modelVersion=9000323000706
DEBUG [main] - pmmlFilePath=/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit.xml
DEBUG [main] - pmml=`cat "/home/le/dev/OnLEPInstall/workingdir/Pre_Certification_Requirement_Visit.xml"`
DEBUG [main] - jarPath=Not Set
DEBUG [main] - clientName=ligadata
DEBUG [main] - createJar ends
ERROR [main] - Failed to compile the model definition com.ligadata.MetadataAPI.ModelCompilationFailedException: Failed to produce the jar file
Results as json string =>
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Error :com.ligadata.MetadataAPI.ModelCompilationFailedException: Failed to produce the jar fileFailed to Add Model"
  }
}

**Comment by ligadata-william** [comment]
Closing due to age and lack of response.
