### ISSUE TITLE
Load Functions from a file  session expires

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#602]
Pre-request
Install v1.0.5 release

Start zk, kafka, cassandra
Add metadata
Add function 30

Enter your choice: 30
Pick a Function Definition file(function) from below choices
[1] /home/le/EngineCassConfigs/metadata/function/edfxUdfs.fcns.json
[2] Main Menu

Enter your choice: 1

Expected
Upload should take lest 1 second 

Actual 
Upload function is taking 3 minutes with error message 

 WARN [main-EventThread] - Session expired event received
ERROR [main] - Failed to Save the object(pmml.booleanblock.000000000000000100): Function pmml.booleanblock with signature 'pmml.booleanblock(any)' already exists.
ERROR [main] - Failed to Save the object(pmml.stringblock.000000000000000100): Function pmml.stringblock with signature 'pmml.stringblock(any)' already exists.
ERROR [main] - Failed to Save the object(pmml.integerblock.000000000000000100): Function pmml.integerblock with signature 'pmml.integerblock(any)' already exists.
ERROR [main] - Failed to Save the object(pmml.anyblock.000000000000000100): Function pmml.anyblock with signature 'pmml.anyblock(any)' already exists.
ERROR [main] - Failed to Save the object(pmml.longblock.000000000000000100): Function pmml.longblock with signature 'pmml.longblock(any)' already exists.
ERROR [main] - Failed to Save the object(pmml.dateblock.000000000000000100): Function pmml.dateblock with signature 'pmml.dateblock(any)' already exists.
ERROR [main] - Failed to Save the object(pmml.durationblock.000000000000000100): Function pmml.durationblock with signature 'pmml.durationblock(any)' already exists.
ERROR [main] - Failed to Save the object(pmml.lessorequal.000000000000000100): Function pmml.lessorequal with signature 'pmml.lessorequal(int,string)' already exists.
ERROR [main] - Failed to Save the object(pmml.id_gen.000000000000000100): Function pmml.id_gen with arguments '' already exists.
ERROR [main] - Failed to Save the object(pmml.dateplus.000000000000000100): Function pmml.dateplus with signature 'pmml.dateplus(int,string)' already exists.
ERROR [main] - Failed to Save the object(pmml.dateminus.000000000000000100): Function pmml.dateminus with signature 'pmml.dateminus(int,string)' already exists.
ERROR [main] - Failed to Save the object(pmml.dateblock.000000000000000100): Function pmml.dateblock with signature 'pmml.dateblock(string,any)' already exists.
Result as Json String =>
{
  "APIResults" : {
    "Status Code" : 1,
    "Function Name" : "AddFunctions",
    "Result Data" : "pmml.booleanblock.100,pmml.stringblock.100,pmml.integerblock.100,pmml.anyblock.100,pmml.longblock.100,pmml.dateblock.100,pmml.durationblock.100,pmml.lessorequal.100,pmml.id_gen.100,pmml.dateplus.100,pmml.dateminus.100,pmml.dateblock.100",
    "Result Description" : "Some functions failed to update"
  }
}

**Comment by ligadata-william** [comment]
Closing as invalid.
