### ISSUE TITLE
 create_namespace 'metadata'   add these 2 name spaces : "statusinfo" , "testdata" in the same way

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#613]
create_namespace 'metadata'

add these 2 name spaces : "statusinfo" , "testdata" in the same way

**Comment by ligadata-alison** [comment]
Hi William,
    I have:

https://wiki.apache.org/hadoop/Hbase/Shell
after this section of documentation

Note: If you are using HBase and you receive an error message, you may need to create the namespaces manually. To do this, run the following in the HBase shell:


but am missing what to run. Would you please let me know and then I can add to the website?

thanks,
alison

**Comment by ligadata-william** [comment]
This documentation would be out of date. Closing as invalid.
