### ISSUE TITLE
Need to delete lines from sbt assembly to compile Kamanja

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#637]
Kamanja will not compile without removing the following lines:
lazy val LoadtestCommon = project.in(file("Tools/LoadtestCommon")) dependsOn(StorageManager, Exceptions)
lazy val LoadtestRunner = project.in(file("Tools/LoadtestRunner")) dependsOn(LoadtestCommon, Exceptions)
lazy val LoadtestMaster = project.in(file("Tools/LoadtestMaster")) dependsOn(LoadtestCommon, Exceptions)
lazy val Loadtest = project.in(file("Tools/Loadtest")) dependsOn(StorageManager, Exceptions)

**Comment by ligadata-pokuri** [comment]
we removed these projects from trunk/build.sbt long back.
