### ISSUE TITLE
Json nesting needs documentation

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#639]
Hi, this question was asked by a user and we need to document it and add it to the FAQ.

1)      How do we define a nested json message

for eg below there’s a nested field json object which is contains other json fields :-

{

    "field1": "abc",

    "nestedfeild": {

        "nestedfield1": 3022744317,

    },

    "field2": null,

}

 
2) If the input message doesn’t match the message definition defined, will the engine discard the entire message or pick relevant fields matching to the json or the engine would fail for eg if I have defined A,B as two csv fields and if the input message is received as A,B,C then will the engine pick A,B & discard C or it will discard the entire message

**Comment by ligadata-alison** [comment]
Hi Tulasi,
    Can I add to the message documentation that we do NOT support nested json for message/container definitions?
thanks,
alison

**Comment by ligadata-tulasi** [comment]
Yes Alison, please add it.

**Comment by ligadata-alison** [comment]
Added documentation that we do not support nested JSON and also what happens when the input message does not match the message definition.
