### ISSUE TITLE
Format of EventData in ModelResult

### ISSUE THREAD

**Issue by edifecs-pankaj** [LigaData/Kamanja#641]
How do we read the event date coming in ModelResult "  "EventDate":1422259242656"  "? What format are we using here?

"ExecutionTime":"2015-01-26T16:53:42.656-08:00",
"EventDate":1422259242656,
"TxnId":100000000000021,
"ModelName":"com.ligadata.pmml.System_COPDRiskAssessment_100",
"uniqKey":"{"Version":1,
  "Type":"Kafka",
  "Name":"testin_1",
  "TopicName":"testin_1",
  "PartitionId":0}",
  "uniqVal":"{"Version":1,
  "Offset":1393}",
  "ModelVersion":"100",
  "DataReadTime":"2015-01-26 16:53:42.620",
  "xformCntr":1,
  "ElapsedTimeFromDataRead":35994
}

**Comment by ligadata-pokuri** [comment]
This is not valid any more. @ligadata-william verify this and close.

**Comment by ligadata-william** [comment]
Closing.
