### ISSUE TITLE
When MetadataAPI loads, unknown objectType ConfigDef is cited

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#679]
This is occurring after adding a model compile config. Looks like we aren't handling things for ConfigDef here.

WARN [main-EventThread] - Unknown objectType ConfigDef in zookeeper notification, notification is not processed ..

**Comment by ligadata-pokuri** [comment]
@ligadata-william can you verify this? if it still exists assign this to @ligadata-dan

**Comment by ligadata-william** [comment]
This isn't an issue anymore. Closing.
