### ISSUE TITLE
kamanja push data only allows for csv data and the partition key MUST be in the first position

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#683]
We need to be able to allow the user to input their desired format (JSON or CSV) as well as the partitionidxs; whether it is 1, 2, or system.message:nameOfPartitionKey

**Comment by ligadata-pokuri** [comment]
For Delimited data, Message/Container type must be at first position and Partition key can be anywhere. From 1.4 on wards we don't even consider partition idx to push data. We simply take the partition key specified in Message/Container definition.

**Comment by ligadata-pokuri** [comment]
@ligadata-william , @ligadata-dhaval , one of you please verify whether this is working as expected or not.

**Comment by ligadata-dhaval** [comment]
@ligadata-pokuri I will verify this.

**Comment by ligadata-william** [comment]
I've verified this. Closing.
