### ISSUE TITLE
When starting web service, if SSL_PASSWD isn't set or is incorrect, DEBUG message is printed

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#724]
If property SSL_PASSWD isn't set or is incorrect (both cases should be handled individually), then we need to print an ERROR statement indicating such and exit out with a proper return code.

**Comment by ligadata-yasser** [comment]
@ligadata-william 
please verify, pull request is #1195

**Comment by ligadata-william** [comment]
I've verified this as fixed. Closing.
