### ISSUE TITLE
There is no documentation on how to reset the queues for customers to recognize problem or do this on their own.

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#732]
In the demos Kamanja needs to be reset frequently. This is an ongoing issue.

**Comment by ligadata-william** [comment]
@ligadata-alison I know this issue has been stale a while (my fault). Can you post the link to the cleanup documentation here?

**Comment by ligadata-alison** [comment]
http://kamanja.org/administration-monitoring-1-4/cleanutil-1-0-1-4/

**Comment by ligadata-alison** [comment]
William has added the cleanutil script that properly cleans up Kafka, ZooKeeper etc. The documentation is:
http://kamanja.org/administration-monitoring-1-4/cleanutil-1-0-1-4/
