### ISSUE TITLE
How can we implement security and push alerts?

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#733]
How can we implement security and push alerts?  How to filter the output so only the user with permissions can see the alerts that belong to them? How can we control Kamanja output? The documentation has not been enough for the implementation engineers to do this at our banking customers. This is necessary at a bank.

**Comment by ligadata-william** [comment]
Some more detail was needed to fill out exactly what was desired and it was never given. This has been stale a long time. Closing until someone has an issue related to this again.
