### ISSUE TITLE
Heartbeat output needs to be JSON

### ISSUE THREAD

**Issue by donald-ligadata** [ligaDATA/Kamanja#738]
Impelementation engineers would like the heartbeat output to be JSON

**Comment by ligadata-dan** [comment]
https://github.com/ligaDATA/Kamanja/pull/802

**Comment by ligadata-dan** [comment]
@ligadata-william @donald-ligadata 

By the way, a / character is not really an issue.. I am not sure how you are gong to create a Java String without escaping the ".  The Object in the Result Data was not a valid JSON by itself.  it should be an Array of values...   It should be valid now.

{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "GetHeartbeat",
    "Result Data" : [ "{\"Name\":\"2\",\"Components\":[],\"LastSeen\":\"2015-10-15 15:30:12\",\"UniqueId\":12,\"Metrics\":[],\"StartTime\":\"2015-10-15 15:29:17\"}" ],
    "Result Description" : "Heartbeats fetched successfully"
  }
}


By the way, all our Embedded Json strings have escape characters in them

**Comment by ligadata-william** [comment]
Dan, it isn't a Java string that is being created. It's a json object that
needs to be created. Json parsers don't parse java strings, they parse raw
strings into json objects.

**Comment by ligadata-krishna** [comment]
You can use \uxxxx to specify characters that need special handling.

 

Thanks

-Krishna

**Comment by ligadata-william** [comment]
Verified this is fixed. Closing.
