### ISSUE TITLE
Metadata Message missing warnings 

### ISSUE THREAD

**Issue by edifecs-mohamed** [LigaData/Kamanja#752]
When mapped messages contains unknown property (example: contains  wrong property name)  there is no warning telling the user message contains wrong property.

**Comment by ligadata-pokuri** [comment]
In mapped messages, you can have any key & data which does not declared in Mapped message defintion. i don't think this is valid issue. We capture all the extra input we get and hold them as strings (in mapped messages).

**Comment by ligadata-william** [comment]
@ligadata-pokuri, I don't think this issue was regarding having an unregistered field passed in so much as it was to have a mechanism by which a user could determine that a field was misspelled in the data. I think this was desired more for debugging purposes.

**Comment by ligadata-pokuri** [comment]
william, how do we know whether it is new field or misspelled? What is the criteria you are deciding this is misspelled?

**Comment by ligadata-william** [comment]
The best thing here is to let the responsibility of the error handling fall on the model itself and not on the platform. Closing.
