### ISSUE TITLE
New Feature: "allow users to make custom configurations" does not have on-line documentation.

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#768]
In the list of new features for 1.1, a feature "allow users to make custom configurations." This does not have on-line documenation yet.

**Comment by ligadata-alison** [comment]
Hi Donald,
    Please take a look at:
http://kamanja.org/administration-monitoring-2/#Custom_Configuration

Does this answer your question? Please verify.

**Comment by ligadata-william** [comment]
Verified and closing.
