### ISSUE TITLE
Kafka script issue

### ISSUE THREAD

**Issue by ligadata-dhaval** [ligaDATA/Kamanja#778]
If 'kamanja --with-all' command is used, it will install zookeeper and kafka. However, brew installs latest version of kafka which does not have the kaka-topics.sh and some other scripts. This will cause error if someone tries to use easy install later. This is an edge case.

**Comment by ligadata-william** [comment]
As far as I can see, kafka-topics.sh does indeed exist in the latest version of kafka. However, the location of those scripts are probably different due to the fact that kafka is installed with a different structure when installed using homebrew.

**Comment by ligadata-william** [comment]
After installing kafka with homebrew, I run:
```
 ls /usr/local/Cellar/kafka/0.8.2.1/bin/
```
which results in
```
kafka-console-consumer.sh		kafka-replica-verification.sh
kafka-console-producer.sh		kafka-run-class.sh
kafka-consumer-offset-checker.sh	kafka-server-start.sh
kafka-consumer-perf-test.sh		kafka-server-stop.sh
kafka-mirror-maker.sh			kafka-simple-consumer-shell.sh
kafka-preferred-replica-election.sh	"kafka-topics.sh"
kafka-producer-perf-test.sh		zookeeper-server-start.sh
kafka-reassign-partitions.sh		zookeeper-server-stop.sh
kafka-replay-log-producer.sh		zookeeper-shell.sh
```
I see kafka-topics and placed quotes around it.
