### ISSUE TITLE
Adapter Configuration should treat empty string as null

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#779]
When initialing an input adapter, if the various delimiters are set as an empty string, those delimiters are incorrectly set, causing the input messages to be delimited on each character. When creating an input adapter, there should be a check for null OR "" (empty string) when determining whether to use default delimiters.

**Comment by ligadata-pokuri** [comment]
I don't know whether empty string should be treated as NULLs or not. Both have different meaning.

**Comment by ligadata-william** [comment]
True though that may be, I very much doubt users want to separate an input message on every character. In code, they are different, from a user perspective, they are not.

**Comment by ligadata-pokuri** [comment]
If you want to document the following we can support it.

If it empty string or unset or null, it will take default parameters.

**Comment by ligadata-william** [comment]
I think that is probably best. We can have @ligadata-alison document it as such.

**Comment by ligadata-pokuri** [comment]
Did you open this bug on sprint8features or any other branch?

**Comment by ligadata-william** [comment]
This bug is on sprint8features since the testing revealed it on this branch. I suspect something similar exists on dev.

**Comment by ligadata-pokuri** [comment]
yes, for now we fix this on sprint8features and port back to dev later

**Comment by ligadata-pokuri** [comment]
Fixed with Pull request https://github.com/ligaDATA/Kamanja/pull/780

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
