### ISSUE TITLE
PMML models with custom namespaces; scala generation gives proper package name but wrong name for getModelDef

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#781]
When compiling a PMML model with a custom namespace, the scala that is generated has the proper package name; in this case:
```
package com.ligadata.tests.outputmessage
```
but the generated override def getModelName is incorrectly set to:
```
override def ModelName(): String = "System.OutputMessageTest"
```
Instead, it should read:
```
override def ModelName(): String = "com.ligadata.tests.outputmessage.OutputMessageTest"
```

**Comment by ligadata-william** [comment]
The model name is showing incorrectly on the output. The ModelName shows as System.OutputMessageTest:
```
{
    "ModelsResult": [
        {
            "ModelName": "System.OutputMessageTest",
            "ModelVersion": "1000000",
            "uniqKey": "{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":0}",
            "uniqVal": "{\"Version\":1,\"Offset\":0}",
            "xformedMsgCntr": 1,
            "totalXformedMsgs": 1,
            "output": [
                {
                    "Name": "TestHit",
                    "Value": "1"
                },
                {
                    "Name": "carYear",
                    "Value": "2012"
                },
                {
                    "Name": "vinNumber",
                    "Value": "V1234HKASDF91FA6"
                },
                {
                    "Name": "carModel",
                    "Value": "Camry"
                },
                {
                    "Name": "carMake",
                    "Value": "Toyota"
                }
            ]
        }
    ]
}
```
but during model compilation I see this:
```
 INFO [Thread-12-EventThread] - Created Model:com.ligadata.tests.outputmessage.outputmessagetest
```
and this:
```
API Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : "Map()",
    "Result Description" : "Model Added Successfully:com.ligadata.tests.outputmessage.outputmessagetest.000000000001000000"
  }
}
```

**Comment by ligadata-rich** [comment]
good bug... the pmml node printer for the object failed to get the package namespace to be used as the namespace for the fq class name.

**Comment by ligadata-rich** [comment]
See https://github.com/ligaDATA/Kamanja/commit/52f2374a8951548ee00550a8a1bb96b850f45452

Object generator in the pmml node printer helpers was not accessing package name variable established in
the model comment function.

Metadata api template fixed so that the copd v3 model could be compiled.
The copd v3 model changed to use an explicit namespace in the application name of the header.

This header:

        <Header copyright="Medco Corp. Copyright 2014" description="COPD Risk Assessment">
                <Application name="com.medco.pmml.COPDRiskAssessmentNmSpc" version="00.01.00"/>
        </Header>

now produces this in the Object:

object COPDRiskAssessmentNmSpc extends ModelBaseObj {
    override def ModelName(): String = "com.medco.pmml.COPDRiskAssessmentNmSpc"
    override def Version(): String = "1000000"
   .
   .
   .

**Comment by ligadata-william** [comment]
Verified this is fixed. Closing.
