### ISSUE TITLE
Kamanja cluster distribution needs to be documented

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#785]
We need documentation on the details of how Kamanja distributes workload within a cluster.

**Comment by ligadata-alison** [comment]
Hi William,
    The:

http://kamanja.org/administration-monitoring-2/

webpage is dedicated to cluster installation. If you have any ideas for improvement, please let me know. Maybe even move the cluster installation to a separate section of the website called "Cluster Installation" to differ it from "Administration and Monitoring". Please do comment,

**Comment by ligadata-william** [comment]
Verified and closing.
