### ISSUE TITLE
Sprint8Features: Only Sql Server is supported

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#794]
All other choices for datastores: hashmap, treemap, cassandra and hbase, are no longer supported due to storage interface changes. These need to be supported before a merge into dev can happen.

**Comment by ligadata-ramana** [comment]
The adapters cassandra/hbase/hashmap/treemap for new storage interface are complete. I need to do more work on hbase (and may be cassandra) to improve performance. I am creating a pull request so testing can be started while I am still working on improving hbase performance.

**Comment by ligadata-william** [comment]
Verified this is fixed. Closing.
