### ISSUE TITLE
MetadataAPI unit test setup fails

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#795]
There is an issue with executing setup with zookeeper. It appears as though the properties being passed in at line 36 of trunk/MetadataAPI/src/test/scala/MetadataManager.scala is setting the zookeeper connection string to localhost:2181.
```
var zkConnStr: String = "localhost:2181", 
```
and when MetadataManager is instantiated in line 31 of /Users/will/dev/kamanja/trunk/MetadataAPI/src/test/scala/LocalTestFixtures.scala
```
val mdMan: MetadataManager = new MetadataManager(new MetadataAPIProperties)
```
it isn't overwriting the default connection string, which it needs to do because in /Users/will/dev/kamanja/trunk/MetadataAPI/src/test/scala/EmbeddedZookeeper.scala, def resolvePort is resolving the port number to a random port.
```
private def resolvePort(port: Int): Int = {
      if (port == -1) {
        val availablePort = TestUtils.getAvailablePort
        logger.debug("AUTOMATION-EMBEDDED-ZOOKEEPER: Resolving port '" + port + "' to port '" + availablePort)
        return availablePort
      }
      return port
    }
```
 In order for tests to run properly, MetadataManager needs to be instantiated with a new MetadataAPIProperties(zkConnStr = zkServer.getConnection)

**Comment by ligadata-ramana** [comment]
1. Verified the change in dev environment
2. Moved and verified the change in Sprint8Features as well

This can be closed.

**Comment by ligadata-pokuri** [comment]
william, can you check this once?

**Comment by ligadata-william** [comment]
Verified and closing.
