### ISSUE TITLE
Error documentation for installing via linuxbrew should be a part of standard installation instructions

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#796]
The error describe at http://kamanja.org/qs/homebrew/kamanja-installation-instructions/error-messages/#Error_gcc_cannot_be_built_with_any_available_compilers seems like it may be a common issue with linuxbrew. It may be prudent for us to have this step (or a link to it) as part of the installation instructions for a brew install. 

@ligadata-dhaval @ligadata-alison can we can discuss this in more detail to see how common this issue is?

**Comment by ligadata-alison** [comment]
Hi William,
     Please check:

http://kamanja.org/qs/homebrew/kamanja-installation-instructions/

scroll to the very end of the page and verify.

**Comment by ligadata-william** [comment]
Verified and closed.
