### ISSUE TITLE
kamanja 1.1 quick start section needs clearer instructions to proceed to samples after installation is done

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#797]

**Comment by donald-ligadata** [comment]
This tracks Forum item: https://groups.google.com/a/ligadata.com/forum/?hl=en#!topic/kamanja/kEdWLuLMzR4

**Comment by ligadata-william** [comment]
This is a part of an active work item already on Alison's plate. I'll assign it to her. In the meantime, please include within this issue directly a summary of the problem as well as specific steps to resolve it.

**Comment by ligadata-joerg** [comment]
http://kamanja.org/qs/working-binaries/

Step 5: Run SetPaths.sh

It is expected to pass-in the root of the kafka installation
SetPaths.sh <path-to-kafka>
SetPaths.sh ~/kafka_2.10-0.8.2.2

**Comment by ligadata-ahmad** [comment]
Its already documented . if you click on Step 5: Run SetPaths.sh
you will see how to run the script :
bash ~/Downloads/Kamanja/bin/SetPaths.sh $KAFKA_HOME

**Comment by ligadata-alison** [comment]
Hi Joerg,
    Can you please verify that the instructions in Quick Start are working for your issue? If not, please let  me know how it fails?
thanks,
alison

**Comment by ligadata-pokuri** [comment]
William, can you verify it and close?

**Comment by ligadata-william** [comment]
Verified and closing.
