### ISSUE TITLE
Our installation should automatically create those links as I posted or as documented in errormessages section.

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#800]
This is discussed in the issue: 
gcc issues - while installing Kamanja 1.1 in Cloudera VM (CDH 5.4.2) with brew
https://groups.google.com/a/ligadata.com/forum/?hl=en#!topic/kamanja/APEQBwKtgiA

**Comment by ligadata-william** [comment]
This is a duplicate of #796

**Comment by ligadata-pokuri** [comment]
@ligadata-william , verify this one as #796 is already closed

**Comment by ligadata-william** [comment]
Closing as duplicate.
