### ISSUE TITLE
Kaman sample application link unavailable

### ISSUE THREAD

**Issue by ligadata-dhaval** [ligaDATA/Kamanja#801]
Hi Alison,

After installation, I cannot see the link to the sample apps. It takes me back to the install kamanja page.

**Comment by ligadata-alison** [comment]
You never get to:

http://kamanja.org/qs/homebrew/kamanja-installation-instructions/kamanja-with-all/run-samples/
 ??

it should be the final step in the installation.

Please send me the webpage that you arrive at that takes you back to the
installation page.

**Comment by ligadata-alison** [comment]
Thanks for showing me the problem. I have added the samples to the
drop-down menu at the top of kamanja.org.
