### ISSUE TITLE
Documentation is needed for storage adapter specific configuration for each supported datastore

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#808]
Currently, we allow configuration for specific storages, however, we are lacking in documentation what values we support for each database.

We need all keys supported for cassandra as well as hbase.

**Comment by ligadata-alison** [comment]
Can someone please let me know all the keys supported for cassandra as well as hbase? Where can I find this information?

**Comment by ligadata-ahmad** [comment]
Hi @ligadata-alison  please find attached the configuration  that we support for each storage adapter

[keys_for_storage_adapters.txt](https://github.com/ligaDATA/Kamanja/files/112658/keys_for_storage_adapters.txt)

**Comment by ligadata-alison** [comment]
Added
