### ISSUE TITLE
Messages fail to be written to cassandra when using large amounts of redundant data

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#811]
I am pushing 5000 messages into the input topic on kafka. These messages are actually only 10 unique messages, however, they are duplicated until there are 5000 messages total.

Upon reaching 3747 input messages, this error begins to appear for every single message after. Restarting kamanja has no effect. After the error starts, whether I send a single message or another 5000, this error still occurs for each message pushed. The error is below:
```
2015-10-21 17:00:41,834 - com.ligadata.SimpleEnvContextImpl.SimpleEnvContextImpl$ [pool-7-thread-3] - ERROR - Failed to write data
2015-10-21 17:00:41,834 - com.ligadata.KamanjaManager.ExecContextImpl [pool-7-thread-3] - ERROR - Failed to serialize uniqueKey/uniqueVal. Reason:com.datastax.driver.core.exceptions.InvalidQueryException: Batch too large Message:Batch too large
```

The message definition:
```
{
  "Message": {
    "NameSpace": "com.ligadata.kamanja.stress",
    "Name": "StressMsg",
    "Version": "00.01.00",
    "Description": "Testing the Stress Level",
    "Fixed": "true",
    "Persist": "true",
    "Fields": [
      {
        "Name": "StressLevel",
        "Type": "System.Integer"
      },
      {
        "Name": "FirstName",
        "Type": "System.String"
      },
      {
        "Name": "LastName",
        "Type": "System.String"
      },
      {
        "Name": "ID",
        "Type": "System.String"
      }
    ],
    "PartitionKey":[
      "ID"
    ]
  }
}
```

A portion of the data:
```
com.ligadata.kamanja.stress.StressMsg,1,John,Doe,1
com.ligadata.kamanja.stress.StressMsg,2,John,Doe,2
com.ligadata.kamanja.stress.StressMsg,3,John,Doe,3
com.ligadata.kamanja.stress.StressMsg,4,John,Doe,4
com.ligadata.kamanja.stress.StressMsg,5,John,Doe,5
com.ligadata.kamanja.stress.StressMsg,6,John,Doe,6
com.ligadata.kamanja.stress.StressMsg,7,John,Doe,7
com.ligadata.kamanja.stress.StressMsg,8,John,Doe,8
com.ligadata.kamanja.stress.StressMsg,9,John,Doe,9
com.ligadata.kamanja.stress.StressMsg,10,John,Doe,10
```

These 10 messages are duplicated 500 times each (for a total of 5000) in the test.

My best guess is that batch writes are occurring based on the partition key. Since the same partition key is appearing so many times, it may be causing an error in Cassandra. I will test further to see if unique partition keys resolves this issue.

**Comment by ligadata-pokuri** [comment]
Lowered the priority because no customers are really using cassandra at this moment

**Comment by ligadata-ashish** [comment]
@ligadata-ramana A customer might look at this, please review and fix

**Comment by ligadata-ramana** [comment]
Two weeks ago, pumping large amount of data into kafka queues caused few issues due to kafka-queue getting filled up too quickly. Lack of resources in our simple laptops may be part of the issue. We addressed the issue by minimizing retry interval and data is pumped without interruptions and fairly efficiently. Couldn't reproduce the issue in a test where I used Medical Model and 108000 messages distributed among 32users. More tests are being done.

**Comment by ligadata-ramana** [comment]
Unable to reproduce the issue; I have done the following tests

Using MedicalApp, 
Uploaded a file with 108k messages and 32 unique users
Uploaded a file with 500k messages and 32 unique users

Created a test spec Storage/Cassandra/src/test/scala/SimulateConcurrentUpdates.scala
and ran a variety of tests where 16 threads were doing both single-row inserts as well batch inserts
concurrently. Still unable to reproduce the issue

Please test this again in 1.6.0 environment.

**Comment by ligadata-ramana** [comment]
William, Please try to reproduce the problem in your environment in 1.6.0.

**Comment by ligadata-william** [comment]
Running into an issue connecting to cassandra related to an incompatible guava version that we have. I'll need to talk to @ligadata-pokuri about this. I think @ligadata-haitham faces a similar issue for elasticsearch.

**Comment by ligadata-william** [comment]
I'm unable to reproduce this on 1.6.0. Closing as fixed.
