### ISSUE TITLE
Sprint8Features: Non-persisted messages can't be saved from model without a partition key

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#812]
A persistent message can be saved without providing a partition key (appears empty in the database) however, a non-persistent message can't be saved from within a model if it doesn't have a partition key. When I attempt to save the message (not-persisted, no partition key) I look in the database and it isn't there. Once I give it a partition key, saving it from the model works fine.

Additionally, when the save fails, there is no logging of success or fail, it simply doesn't save.

**Comment by ligadata-pokuri** [comment]
this is must. We need to have Persist as True and Partition keys. We simply ignore the messages which does not have these instead of throwing error (and failing transaction) while comiting data.

**Comment by ligadata-william** [comment]
Closing as By Design.
