### ISSUE TITLE
Removing message/container doesn't remove associated types

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#813]
When I remove a message or a container from metadata, the types that were generated when they were added (such as arraybufferof[message]) are not removed.

**Comment by ligadata-pokuri** [comment]
Can you verify it once? I am thinking this is there now

**Comment by ligadata-pokuri** [comment]
If not fixed assign back to me

**Comment by ligadata-william** [comment]
This is still an issue.

**Comment by ligadata-pokuri** [comment]
We have only two types now. Array[Container] & Map[String, Container]. We can remove them (of same version when we remove the container/message.

**Comment by ligadata-tulasi** [comment]
Please Verify.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
