### ISSUE TITLE
Sprint8Features: Update message doesn't recompile associated models

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#814]
When I attempt to update a message, the message is appropriate updated, however, existing models that consume that message type are no longer updated appropriately.

**Comment by ligadata-ramana** [comment]
Tried to reproduce the issue with HelloWorld example. But unable to. Going to try other examples.

**Comment by ligadata-william** [comment]
I can reproduce this issue using scala models. I made a change to the message definition and updated it and the model doesn't pick up the change.

**Comment by ligadata-william** [comment]
I should have given my reproduce steps here because I finally found out why the model isn't updating.

When I run the following:
```
kamanja update message <path to message>
```
Only the message gets compiled. However, if I run:
```
java -jar MetadataAPI-1.0 $KAMANJA_HOME/config/MetadataAPIConfig.properties
```
and choose to update the message through the menu, the model properly recompiles. It looks like whatever @ligadata-dhaval is doing is incorrect because it doesn't look like it's updating properly when I call it through the kamanja script.

Re-assigning to Dhaval.

**Comment by ligadata-william** [comment]
I found the issue. When using kamanja commands, if you run:
```
kamanja update message
```
in the code, it's actually calling "AddContainer" which is passing in false to recompile. I'll change this to "UpdateMessage" and test. I also noticed kamanja add message also calls "AddContainer" so I'll change that to "AddMessage". I'll test real quick and push the code if it works ok.

**Comment by ligadata-william** [comment]
I've tested and pushed the changes required to properly update a message through kamanja commands. Closing this issue.
