### ISSUE TITLE
When compiling metadata, errors are logged as DEBUG and suppressed

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#818]
When compiling metadata, if there is an error, it isn't logged as an ERROR but as a DEBUG statement. This means when compilation fails, it appears to stop without any message indicating why. This is because by default, log4j is set at log level WARN, which only catches warnings and errors.

**Comment by ligadata-ramana** [comment]
Identified couple of locations where errors are being reported at debug level. Corrected them. Default LogLevel was already changed to INFO with an earlier fix. Code change is available in Sprint8Features.

**Comment by ligadata-william** [comment]
Verified and closing.
