### ISSUE TITLE
Install cluster on multiple nodes documentation needs revision. 

### ISSUE THREAD

**Issue by donald-ligadata** [LigaData/Kamanja#819]
This is outlined, discussed, and the fix is documented in the forum in the topic;
Cluster install,
https://groups.google.com/a/ligadata.com/forum/?hl=en#!topic/kamanja/NwUQ3wxCtCk

**Comment by ligadata-alison** [comment]
Hi Donald,
    There has been a lot of work on cluster configuration in the Administration and Monitoring section of kamanja.org. Has your issue been resolved?
thanks,
alison

**Comment by ligadata-william** [comment]
Verified and closing.
