### ISSUE TITLE
After updating a message that causes a model to recompile, an error appears the first time MetadataAPI or the engine is run

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#836]
Reproduce steps:
run command 
```
kamanja add message $KAMANJA_HOME/input/SampleApplications/metadata/message/Message_Definition_HelloWorld.json
```

run command 
```
kamanja add model /tmp/Kamanja/input/SampleApplications/metadata/model/PMML_Model_HelloWorld.xml
```

increase the version of the message in the file $KAMANJA_HOME/input/SampleApplications/metadata/message/Message_Definition_HelloWorld.json

run command
```
kamanja update message $KAMANJA_HOME/input/SampleApplications/metadata/message/Message_Definition_HelloWorld.json
```

Run kamanja manager
```
kamanja start -v
```

Observe error:
```
ERROR [main] - Transaction is incomplete with the object modeldef.system.helloword.1000000,we may not have notified engine, attempt to do it now...
```

**Comment by ligadata-pokuri** [comment]
@ligadata-ahmad fixed couple of issues with increment transactionid. Can you please verify this ?

**Comment by ligadata-ahmad** [comment]
there was another issue related to this . it should be fixed in this pull request https://github.com/LigaData/Kamanja/pull/899

**Comment by ligadata-pokuri** [comment]
Hi @ligadata-ahmad , 
@ligadata-william  can verify this now in 1.4.0. right?

**Comment by ligadata-william** [comment]
Verified and closing.
