### ISSUE TITLE
All log4j.properties files in source need to be change to log level WARN

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#838]
It has been requested that all our log4j.properties files are changed to log level WARN to prevent unnecessarily large logging.

**Comment by heman-duraiswamy** [comment]
This effort is completed as part of sprint 8 features.
https://github.com/ligaDATA/Kamanja/tree/Sprint8Features/trunk/SampleApplication/ClusterInstall

Closing
