### ISSUE TITLE
Kamanja kafka offset is out of sync with kafka

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#840]
It has been reported that there may be an issue where the kafka offsets we're tracking are out of sync with the proper offset causing message processing to stop.

The following items are needed to fill out this issue:
1. Zookeeper environment setup information (number of nodes, configuration files, logs, etc.)
2. Data from /kamanja/enginedistribution using zkCli (at the time of error)
3. Data from /kamanja/datachange using zkCli (at the time of error)
4. Kafka environment setup information (number of nodes, configuration files, logs, etc.)
5. Output of the status queue at the time of error
6. Number of messages in the input queue at the time of error (read directly from kafka, not as seen in the status queue)
7. Kamanja environment setup information (number of nodes, cluster configuration, metadata configuration, engine configuration)
8. Full DEBUG logs from each node of Kamanja in the cluster (Check $KAMANJA_HOME/config/log4j.properties; Also be sure to increase the property "og4j.appender.R.MaxBackupIndex" from 2 to 50 to ensure all logs are available as well as increase the property "log4j.appender.R.MaxFileSize" from 200KB to 2MB)

**Comment by ligadata-william** [comment]
Assigning to myself for now until the information is gathered. Will reassign as necessary.

**Comment by ligadata-pokuri** [comment]
So far we did not get any information & we could not able to repro this. Lowering the priority to P3.

**Comment by ligadata-william** [comment]
So far we've been unable to reproduce this issue and no information has been given on how we could reproduce this. This will be closed. If anything comes up in the future, this issue can be reopened.
