### ISSUE TITLE
Kamanja command getall is documented at "get all"

### ISSUE THREAD

**Issue by donald-ligadata** [ligaDATA/Kamanja#843]
Minor fix that can cause pain.  The command is "kamnja get all" not "kamanja getall" 
I am not sure where this is documented.  If you don't know off the top-of-your-head, I will help your find it.
Please let me know when this is fixed so I can close this. 
THANKS

**Comment by donald-ligadata** [comment]
Oops, this seems to be an actual code bug that is fixed.

**Comment by ligadata-rich** [comment]
http://kamanja.org/kamanja-commands/
