### ISSUE TITLE
SampleApplication don't work

### ISSUE THREAD

**Issue by ligadata-joerg** [LigaData/Kamanja#853]
The HelloWorld sample application is not working.

The sample data file (input/SampleApplications/data/Input_Data_HelloWorld.csv.gz ) is pointing to System.msg1 instead to com.ligadata.kamanja.samples.messages.msg1

Branch: Sprint8Features

Bash 1:
export EASYINSTALL=<>
export PATH=$PATH:$EASYINSTALL/bin
cd $EASYINSTALL
input/SampleApplications/bin/HelloWorldApp.sh
bin/StartEngine.sh

Bash 2:
export EASYINSTALL=<>
export PATH=$PATH:$EASYINSTALL/bin
cd $EASYINSTALL
input/SampleApplications/bin/PushSampleDataToKafka_HelloWorld.sh

**Comment by ligadata-dan** [comment]
Hi,

Thank you for the heads up.  There is a problem in our sample application in our development branch which has yet to pass our integration test, we will fix it.

Regards,
Dan

**Comment by ligadata-pokuri** [comment]
I fixed some (at least medical sample) in log4j2 branch.

**Comment by ligadata-pokuri** [comment]
@ligadata-william can you verify this?

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
