### ISSUE TITLE
Sprint8Features: SampleApplication medical generates compiler error

### ISSUE THREAD

**Issue by ligadata-joerg** [LigaData/Kamanja#854]
Follow "instructions" http://kamanja.org/qs/run-samples/medical/ and make sure to select medicals

The following step creates compiler error

kamanja add model java

Prompt 1:
[2]/home/joerg/app/input/SampleApplications/metadata/model/COPDRiskAssessment.java

Prompt 2:
[1]metadataapi.copdriskassessment

Compiler error 

skAssessment/COPDRiskAssessment.java)
/home/joerg/app/workingdir/COPDRiskAssessment/COPDRiskAssessment.java:88: error: cannot find symbol
    private ArrayList<InpatientClaim> inpatientClaimHistory = new ArrayList<>();
                      ^
  symbol:   class InpatientClaim
  location: class COPDRiskAssessment
/home/joerg/app/workingdir/COPDRiskAssessment/COPDRiskAssessment.java:89: error: cannot find symbol
    private ArrayList<OutpatientClaim> outpatientClaimHistory = new ArrayList<>();

Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Error : Model Compilation Failed, see compliation errors in the log"
  }
}

**Comment by ligadata-pokuri** [comment]
@ligadata-william can you verify this

**Comment by ligadata-william** [comment]
Verified and closing.
