### ISSUE TITLE
Remove model against a running engine isn't processed until the next metadata operation

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#858]
If I remove a model from metadata while the engine is running and I push messages, those messages continue to be processed as if the model is still present. Once I perform another metadata operation such as add a different model, the messages for the previously removed model cease to be processed.

1. Add modelA
2. Push messages and observe output
3. Remove modelA
4. Push messages and observe output (incorrect behavior)
5. Add modelB
6. Push messages for modelA and observe no output.

**Comment by ligadata-rich** [comment]
I have been staring at the remove and update model semantics for a while
now as I worked on the Jpmml adaptation.  It seems to me that we should
have different semantics for these sorts of commands.  The current
implementations are fraught with lag times that will cause future woe for
us.  This is especially true now that the model factories have soon have
access to the metadata.

I suggest we do the following:

1) Eliminate the update commands altogether.
2) Only allow remove <obj> when object is "inactive"

This suggests:

3) To remove a model, first deactivate it, then remove it.
4) To update an existing model that is running, add the new model and swap
it (a deactivate current model/activate new model operation) with the
current active model.

Obviously in a clustered environment, this does not eliminate the possible
race conditions that could be experienced, but it does minimize the window
for these sorts of problems and *more importantly* simplifies the semantics
of processing messages to the activate/deactivate state change.  As it is,
there are more than a few combinations to contend with given our current
remove/update semantics.  This will only be exacerbated as we move to the
ensemble (DAG of) models.

The other command that may be needed is some kind of message processing
state change at the input adapter to say "pause processing", "queue these
up on some path until further notice", et al.

**Comment by ligadata-pokuri** [comment]
@ligadata-yousef can you verify this?

**Comment by ligadata-yousef** [comment]
the below is my scenario:

1- Add modelA
2- start the engine
3- Push messages for modelA and observe output
4- Remove modelA
5- Push messages for modelA and observe output (incorrect behavior)
6- Add modelB
7- Push messages for modelA and observe output (incorrect behavior)
8- stop the engine and start it again.
9- Push messages and observe no output.

where:

modelA : HelloWorld
modelB : Medical

**Comment by ligadata-pokuri** [comment]
Rich, can you check this one?

**Comment by ligadata-rich** [comment]
This has been fixed.  There was no data emitted to the watchoutput after submitting it a 2nd time after the model remove... closing.

**Comment by ligadata-rich** [comment]
this is complete

**Comment by ligadata-rich** [comment]
done
