### ISSUE TITLE
No log4j2 configuration file found...

### ISSUE THREAD

**Issue by ligadata-alison** [LigaData/Kamanja#870]
I'm getting the following error:

$ bash PushSampleDataToKafka_HelloWorld.sh 
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
log4j:WARN No appenders could be found for logger (kafka.utils.VerifiableProperties).
log4j:WARN Please initialize the log4j system properly.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tid: 0, Time:  12971154ms, Lines:      51, Read:           2755, Sent:           2755, Last, file:/usr/local/Cellar/kamanja/1.2/input/SampleApplications/data/Input_Data_HelloWorld.csv.gz
00. File:/usr/local/Cellar/kamanja/1.2/input/SampleApplications/data/Input_Data_HelloWorld.csv.gz ElapsedTime:50.00ms
Done. ElapsedTime:308.83ms

How can I provide the log4j2 configuration file?

**Comment by ligadata-pokuri** [comment]
Add -D log for all scripts like we have in other scripts (Ex: StartEngine.sh)

**Comment by ligadata-saleh** [comment]
fixed in https://github.com/LigaData/Kamanja/pull/1179 

please verify

**Comment by ligadata-william** [comment]
Verified as fixed. closing.
