### ISSUE TITLE
adding a new version of message causes shrieks over the collection types that are built

### ISSUE THREAD

**Issue by ligadata-rich** [LigaData/Kamanja#873]
One of the things I am seeing (probably not news to some/all of you) is this:

log4j:WARN No appenders could be found for logger (org.apache.curator.framework.imps.CuratorFrameworkImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
ERROR [main] - Already Exists! Failed to Cache the object(system.treesetofirismsg.000000000001000001): TreeSet system.treesetofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.immutablemapofintarrayofirismsg.000000000001000001): Map system.immutablemapofintarrayofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.arraybufferofirismsg.000000000001000002): ArrayBuffer system.arraybufferofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.sortedsetofirismsg.000000000001000001): SortedSet system.sortedsetofirismsg cannot be created... a type by that name already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.immutablemapofstringarrayofirismsg.000000000001000001): Map system.immutablemapofstringarrayofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.mapofstringarrayofirismsg.000000000001000001): Map system.mapofstringarrayofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.setofirismsg.000000000001000001): Set system.setofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.mapofintarrayofirismsg.000000000001000001): Map system.mapofintarrayofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.arrayofirismsg.000000000001000001): Array system.arrayofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.arrayofarrayofirismsg.000000000001000001): Array system.arrayofarrayofirismsg already exists.
ERROR [main] - Already Exists! Failed to Cache the object(system.irismsg.000000000001000002): Message type system.irismsg already exists.
added manifest

Adding a new version of the message will cause the models that depended on the prior version to be recompiled.  During these actions, it complains about the ancillary collection variants that are built when a new message is added.

I am going to add this as an issue.  We should probably check for this case and suppress the errors... it is disconcerting for the uninitiated I would say.  I don't think we want to support the version to disambiguate, but we probably want to quell the shrieking.

**Comment by ligadata-tulasi** [comment]
Please Verify

**Comment by ligadata-william** [comment]
Verified fixed. Closing.
