### ISSUE TITLE
When accessing non-existent tables in hbase, ERRORs are displayed

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#877]
When metadataAPI attempts to access a table on hbase, rather than log an ERROR with a scary exception, it needs to silently create the table and continue.

**Comment by ligadata-ramana** [comment]
Included the fix in the branch "StorageExceptions"

**Comment by ligadata-krishna** [comment]
System should create tables only when certain flags are specified. In
certain environments, there may not be privileges to create tables and/or
databases in the underlying storage.

**Comment by ligadata-william** [comment]
This is fixed.
