### ISSUE TITLE
ClusterInstall should be included in binaries

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#878]
When shipping our binaries, we need to include the cluster install script and associated scripts should be included as part of the binaries. We should also include kamanja commands that allow the user to enact the cluster install as well as start/stop and check the status of the cluster.

**Comment by ligadata-william** [comment]
Assigned to @mahesh-lalwani to assign to the proper person to take this work item.

**Comment by ligadata-pokuri** [comment]
Please verify this in https://github.com/ligaDATA/Kamanja/pull/885 pull request

**Comment by ligadata-william** [comment]
Verified.
