### ISSUE TITLE
When 'kamanja upload cluster config' fails, the APIResult indicates success

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#879]
Whether Cluster Config has been properly uploaded or not, the APIResult given is always indicating successful. If the upload is a failure for any reason, there should be an error given in the APIResult.

**Comment by ligadata-pokuri** [comment]
William, can you verify this one. As far as I know dhaval/dan fixed it.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
