### ISSUE TITLE
NodeConfig_*.cfg and log4j2.xml files are empty after cluster installation

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#880]
It has been reported that NodeConfig config files and log4j2.xml files created after cluster installation are empty. Root cause needs to be determined.

**Comment by ligadata-william** [comment]
Assigned to @mahesh-lalwani to determine who this task belongs to.

**Comment by ligadata-pokuri** [comment]
Please verify this in https://github.com/ligaDATA/Kamanja/pull/885 pull request

**Comment by ligadata-william** [comment]
Verified.
