### ISSUE TITLE
When updating a message or container, scala/java models fail to recompile

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#888]
When I update a message or container that is consumed by a scala or java model, recompiling the model fails because model configuration isn't passed into the model recompile.

```
public class COPDRiskAssessment extends ModelInstance {
^
one error found
ERROR [main] - Compile for tempCode.scala has failed...rc = 1
ERROR [main] - Command used: ArrayBuffer(sh, -c, /Users/will/.svm/current/rt/bin/scalac -cp /private/tmp/Kamanja/lib/system/metadata_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/basefunctions_2.10-0.1.0.jar:/private/tmp/Kamanja/lib/system/messagedef_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/pmmlcompiler_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/kamanjabase_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/kvbase_2.10-0.1.0.jar:/private/tmp/Kamanja/lib/system/bootstrap_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/joda-time-2.8.2.jar:/private/tmp/Kamanja/lib/system/joda-convert-1.6.jar:/private/tmp/Kamanja/lib/system/basetypes_2.10-0.1.0.jar:/private/tmp/Kamanja/lib/system/pmmludfs_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/pmmlruntime_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/json4s-native_2.10-3.2.9.jar:/private/tmp/Kamanja/lib/system/json4s-core_2.10-3.2.9.jar:/private/tmp/Kamanja/lib/system/json4s-ast_2.10-3.2.9.jar:/private/tmp/Kamanja/lib/system/jackson-databind-2.3.1.jar:/private/tmp/Kamanja/lib/system/jackson-annotations-2.3.0.jar:/private/tmp/Kamanja/lib/system/json4s-jackson_2.10-3.2.9.jar:/private/tmp/Kamanja/lib/system/jackson-core-2.3.1.jar:/private/tmp/Kamanja/lib/system/log4j-core-2.4.1.jar:/private/tmp/Kamanja/lib/system/log4j-api-2.4.1.jar:/private/tmp/Kamanja/lib/system/guava-16.0.1.jar:/private/tmp/Kamanja/lib/system/exceptions_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/scala-reflect-2.10.4.jar:/private/tmp/Kamanja/lib/system/scala-library-2.10.4.jar:/private/tmp/Kamanja/lib/system/jsr305-1.3.9.jar:/private/tmp/Kamanja/lib/system/datadelimiters_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/customudflib_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/customudflib_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/log4j-core-2.4.1.jar:/private/tmp/Kamanja/lib/system/jackson-databind-2.3.1.jar:/private/tmp/Kamanja/lib/system/pmmlcompiler_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/basetypes_2.10-0.1.0.jar:/private/tmp/Kamanja/lib/system/log4j-api-2.4.1.jar:/private/tmp/Kamanja/lib/system/basefunctions_2.10-0.1.0.jar:/private/tmp/Kamanja/lib/system/jackson-core-2.3.1.jar:/private/tmp/Kamanja/lib/system/joda-time-2.8.2.jar:/private/tmp/Kamanja/lib/system/jackson-annotations-2.3.0.jar:/private/tmp/Kamanja/lib/system/scala-library-2.10.4.jar:/private/tmp/Kamanja/lib/system/joda-convert-1.6.jar:/private/tmp/Kamanja/lib/system/scala-reflect-2.10.4.jar:/private/tmp/Kamanja/lib/system/json4s-core_2.10-3.2.9.jar:/private/tmp/Kamanja/lib/system/json4s-jackson_2.10-3.2.9.jar:/private/tmp/Kamanja/lib/system/pmmlruntime_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/pmmludfs_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/datadelimiters_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/metadata_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/exceptions_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/kvbase_2.10-0.1.0.jar:/private/tmp/Kamanja/lib/system/jsr305-1.3.9.jar:/private/tmp/Kamanja/lib/system/json4s-ast_2.10-3.2.9.jar:/private/tmp/Kamanja/lib/system/json4s-native_2.10-3.2.9.jar:/private/tmp/Kamanja/lib/system/bootstrap_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/kamanjabase_2.10-1.0.jar:/private/tmp/Kamanja/lib/system/guava-16.0.1.jar:/private/tmp/Kamanja/lib/system/messagedef_2.10-1.0.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.messages_HL7_1000000_1450930765071.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.containers_CoughCodes_1000000_1450930628342.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.containers_DyspnoeaCodes_1000000_1450930647839.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.containers_EnvCodes_1000000_1450930669301.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.messages_InpatientClaim_1000000_1450930796541.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.messages_OutpatientClaim_1000000_1450930827009.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.messages_Beneficiary_1000000_1450930734442.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.containers_SmokeCodes_1000000_1450930691438.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.containers_SputumCodes_1000000_1450930711174.jar:/private/tmp/Kamanja/lib/system/metadata_2.10-1.0.jar:/private/tmp/Kamanja/lib/application/com.ligadata.kamanja.samples.messages_Beneficiary_1000006_1450931301274.jar:/private/tmp/Kamanja/lib/system/basetypes_2.10-0.1.0.jar /private/tmp/Kamanja/workingdir/tempCode/tempCode.scala)
ERROR [main] - COMPILER_PROXY: Error compiling model source. Unable to create Jar RC = 1
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during recompile. ERROR tempCode
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.samples.messages.beneficiary.000000000001000006"
  }
}{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Error :com.ligadata.Exceptions.MsgCompilationFailedException: tempCodeFailed to Add Model"
  }
}
```

**Comment by ligadata-ahmad** [comment]
This only happened with java model . scala model worked fine with me.
I am not sure if the reason of the problem is that when we are recompiling the model (java) we copy the  source code to tempCode.scala then we use scala compiler to compile .
I renamed  tempCode.scala to HelloWorldModel.java then I used java compiler and that compiled successfully.

**Comment by ligadata-dan** [comment]
@ligadata-william @ligadata-ahmad 

Ok, pretty sure the issue here is my bug... in MetadataAPIImpl when I call RecompileModel, I pass in

mod.objectFormat.toString into the recompile method (last argument)... which evaluates to 'fJAVA' and not 'java'.... so as a result we use the scalac to compile everything even if it is a java model.  It works for scala, because scalac is the default value.

**Comment by ligadata-ahmad** [comment]
I tested the fix with the following scenarios : 

* Updating message:

1.Adding hello world message (msg1) 
2.Adding hello world model (java/scala/kpmml)
3.change the version of msg1 
4.update msg1 through metadataAPI
The result  : 

{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.samples.messages.msg1.000000000003000000"
  }
}
RecompileModel results for com.ligadata.samples.models.helloworldmodel.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.samples.models.helloworldmodel.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.samples.models.helloworldmodel.000000000000000001"
  }
}

* Updating container 
1. run MedicalApp.sh
2. change the version of SmokeCodes_Medical container 
3. update SmokeCodes_Medical containr through MetadataAPI

The result :

{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddContainerDef",
    "Result Data" : null,
    "Result Description" : "Container Added Successfully:com.ligadata.kamanja.samples.containers.smokecodes.000000000002000000"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.copdriskassessment.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001"
  }
}

**Comment by ligadata-pokuri** [comment]
@ligadata-yousef can you verify this?

**Comment by ligadata-yousef** [comment]
i tested this fix with same William scenario : 

1- update message ==> works fine.
2- update container ==> i did not see the RecompileModel results for com.ligadata.kamanja.samples.models.copdriskassessment.1 in my result. i just see the below:

Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddContainerDef",
    "Result Data" : null,
    "Result Description" : "Container Added Successfully:com.ligadata.kamanja.samples.containers.smokecodes.000000000003000000"
  }
}

note: 

1- i used hbase as a storage.
2- the medical models was added before i do update container.

**Comment by ligadata-yousef** [comment]
i see the below error in enginge logs:

Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 000002F7E0A96C32
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException
Executing COPD Risk Assessment against Beneficiary message:
	Message Name: Beneficiary
	Message Version: 000000.000002.000000
	Message Desynpuf ID: 00001C24EE7B06AC
ERROR [pool-25-thread-1] - Failed to execute model:com.ligadata.kamanja.samples.models.COPDRiskAssessment
java.lang.ArrayStoreException

**Comment by ligadata-pokuri** [comment]
Not yet fixed for containers. Messages are ok.

**Comment by ligadata-dan** [comment]
@ligadata-william @ligadata-pokuri  @ligadata-yousef 

Hi Yousef,  Tested this scenario, and I am unable to reproduce.  Pokuri and I tried a number of scenarios and seems ok.

Willie,

Can you verify this doing your final testing.

**Comment by ligadata-william** [comment]
Messages cause a successful recompile in models. However, containers don't trigger a recompile at all. Still not fixed.

**Comment by ligadata-dan** [comment]
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddContainerDef",
    "Result Data" : null,
    "Result Description" : "Container Added Successfully:com.ligadata.kamanja.samples.containers.coughcodes.000000000001000001"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.copdriskassessment.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.copdriskassessment.000000000000000001"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.copddataingest.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.copddataingest.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.COPDDataIngest.000000000000000001"
  }
}

**Comment by ligadata-william** [comment]
Verified and closing.
