### ISSUE TITLE
kamanja start webservice doesn't use log4j2.xml as it's logging configuration file

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#889]
When kamanja is used to start MetadataAPIService, it should pass in the log4j2.xml file that exists in <Kamanja Install Directory>/config.

**Comment by ligadata-saleh** [comment]
Hi , 
   fixed in `https://github.com/LigaData/Kamanja/pull/1144` , please verify .

Thanks
Saleh

**Comment by ligadata-pokuri** [comment]
Pull reque #1155

**Comment by ligadata-dan** [comment]
Merged, Closing
