### ISSUE TITLE
When using sql server as the storage adapter, jarpaths should not be a required configuration

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#894]
When configuring the datastore for sql server, jarpaths and the jar name should not be required in the datastore configuration. It should look for the proper jar automatically in the JarPaths.

**Comment by ligadata-saleh** [comment]
fixed in `https://github.com/LigaData/Kamanja/pull/1145` please verify , the adapter now search for the jar in the given path , no need to send it in json . 

Thanks
Saleh

**Comment by ligadata-saleh** [comment]
pull request changed to `https://github.com/LigaData/Kamanja/pull/1155 `

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
