### ISSUE TITLE
All configuration templates should include JarPaths

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#895]
When we install kamanja, the template configuration files don't include the JarPaths for the engine configuration and the metadata configuration. This should be added for those storage adapters that require the JarPaths.

**Comment by ligadata-pokuri** [comment]
Make sure all configurations in ClusterConfig, Generated configs from Cluster installations, other configs like EnginConfig, etc has JarPaths.

**Comment by ligadata-pokuri** [comment]
NodeInfoExtract also should do the same when it generated config files

**Comment by ligadata-saleh** [comment]
fix in https://github.com/LigaData/Kamanja/pull/1181

please verify

**Comment by ligadata-william** [comment]
Verified fixed. Closing.
