### ISSUE TITLE
we are not updating transaction id properly  in  (1. Update Model 2. Upload Jars ) through metadataAPI

### ISSUE THREAD

**Issue by ligadata-ahmad** [ligaDATA/Kamanja#896]
we are not updating transaction id properly  in  (1. Update Model 2. Upload Jars) through metadataAPI

ERROR [main] - Transaction is incomplete with the object modeldef.com.ligadata.kamanja.samples.models.helloworldmodel.5,we may not have notified engine, attempt to do it now...

**Comment by ligadata-pokuri** [comment]
Need to check all the operations which one are not updating transactionid.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
