### ISSUE TITLE
Changes to ClusterInstall to make soft links instead of removing the directory data

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#898]
Take install directory from the .properties file as we are taking it today. we take it as <installdir>

Take current installed time (in the format of YYYYMMDD_HHMMSS) as <InstalledTime> and make sure we use it where ever we find <InstalledTime> before.

Check whether the existsting path is soft link or not. If it is soft link, remove it. If it not soft link and real directory, just rename it with some _pre_<InstalledTime> or something

Install the software into new directory with <installdir>_<InstalledTime>

Create a softlink from install directory to the Installed directory which is of the form <installdir>_<InstalledTime>

We need to log what softlink is removed from where and created to where.

**Comment by ligadata-saleh** [comment]
I've been looking  into the script , i think most of the changes is on step
#5 , i think i know what is need to be done , so i will start working on
the script then test it .

**Comment by ligadata-saleh** [comment]
https://github.com/ligaDATA/Kamanja/pull/902 

the new change wont remove the old directory it will change it name and create a new soft link that point to the installation directory and keep the old ones like this : 


lrwxrwxrwx   1 root root   27 Jan 13 05:25 Kamanja -> /opt/Kamanja_20160113052458
drwxr-xr-x  12 root root 4096 Jan 13 05:25 Kamanja_20160113052458
drwxr-xr-x  12 root root 4096 Jan 13 05:25 Kamanja_20160113052134
drwxr-xr-x  12 root root 4096 Jan 13 04:51 Kamanja_pre 

Thanks
Saleh

**Comment by ligadata-pokuri** [comment]
Fixed in pull request https://github.com/ligaDATA/Kamanja/pull/902

**Comment by ligadata-saleh** [comment]
add date to the pre folder on  pull request #902

**Comment by ligadata-pokuri** [comment]
Fixed long back. Closing
