### ISSUE TITLE
Fat jar MetadataAPIService-1.0 is corrupt after assembly

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#900]
After assembling MetadataAPIService, I attempt to run it from the directory I have it in with the following command:
```
java -jar MetadataAPIService-1.0 --config ~/resources/configuration/MetadataConfig_HBase.properties
```
Immediately after I hit enter, I receive the following error:
```
Error: Invalid or corrupt jarfile MetadataAPIService-1.0
```

This appears after install on dev and a couple other branches currently based on dev.

**Comment by ligadata-william** [comment]
This is still a blocking issue for me. I can't access the REST API. @ligadata-dan can you look into this if Ramana is unavailable?

**Comment by ligadata-pokuri** [comment]
Ahmed and myself are going to look at this issue
