### ISSUE TITLE
SBT project versions should be updated to reflect the version of the product

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#903]
Currently, the version of each project we have in source denoted by SBT is 1.0. The version in that build file should reflect the version we have released. This way, rather than our jars always compiling as <jarname>_<scalaVersion>-1.0.jar they will compile as <jarname>_<scalaVersion>-<releaseVersion>.jar

**Comment by ligadata-pokuri** [comment]
This is part of 1.4.0. release. Can you verify it?

**Comment by ligadata-william** [comment]
Closing.
