### ISSUE TITLE
FailedEventsAdapter in ClusterConfig_Template.json has incorrect version of kafka

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#907]
The version of kafka in the template file for the FailedEventsAdapter configuration is set to kafka-0.8.2.1. This should be updated to kafka-0.8.2.2.

**Comment by ligadata-pokuri** [comment]
Hi William,

Can you add the branch name also here?

**Comment by ligadata-william** [comment]
branch name v13MonitorEnhancements

**Comment by ligadata-pokuri** [comment]
I will modify it

**Comment by ligadata-william** [comment]
Verified as fixed and closing.
