### ISSUE TITLE
Adding pmml rules through kamanja results in no output

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#911]
Steps to reproduce:
1. kamanja add message /Users/will/dev/Kamanja/trunk/Pmml/JpmmlAdapter/src/main/resources/metadata/message/IrisMsg1.json

2. kamanja add model pmml /Users/will/dev/Kamanja/trunk/Pmml/JpmmlAdapter/src/main/resources/metadata/model/KNIME/DecisionTreeEnsembleIris.pmml MODELNAME com.botanical.pmml.DecisionTreeEnsembleIris MODELVERSION 0.0.1 MESSAGENAME System.IrisMsg

3. java -jar /tmp/Kamanja/bin/SimpleKafkaProducer-0.1.0 --gz false --topics "testin_1" --threads 1 --topicpartitions 8 --brokerlist "localhost:9092" --files /Users/will/dev/Kamanja/trunk/Pmml/JpmmlAdapter/src/main/resources/data/iris.csv --partitionkeyidxs "1" --format CSV

4. Observe that no output messages are produced.

I've observed this with the following KNIME models:
GeneralRegressionIris.pmml
DecisionTreeIris.pmml
DecisionTreeEnsembleIris.pmml

When I run these same models through the pmml-evaluator, they all produce output.

**Comment by ligadata-william** [comment]
As an additional note, I am able to receive output through automation, so I believe the kamanja commands are parsing or calling the MetadataAPIImpl incorrectly and the API isn't handling it properly.

**Comment by ligadata-pokuri** [comment]
Hi william,

Can you try with properties file?  like kamanja MetadataApiConfig.properties add model .....

**Comment by ligadata-william** [comment]
I explicitly declared the configuration file as you suggested but the result is the same. I double checked all configuration, datastores and schema names. Nothing helped.

**Comment by ligadata-rich** [comment]
I too receive no output.  I added the first of the jpmml models - the
random forest of decision trees... namely

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties
add model pmml
$KAMANJA_SRCDIR/Pmml/JpmmlAdapter/src/main/resources/metadata/model/KNIME/DecisionTreeEnsembleIris.pmml
MODELNAME com.botanical.jpmml.DecisionTreeEnsembleIris MODELVERSION
000000.000001.000001 MESSAGENAME System.IrisMsg

I put breakpoint in the factory of factory initialization... that seems to
be working.. the code executes there that produces the factory for the
modeldef.  I need to see why the factory created for the random forest
model is not working. (I suspect that a merge after my code checkin wiped
something out that is needed... we'll see).

**Comment by ligadata-rich** [comment]
The method in KamanjaMetadata "

def PrepareModelFactory(mdl: ModelDef..." is getting control and a
factory is being produced.  The statement

modelObjsMap(mdlName) = new MdlInfo(factory, mdl.jarName,
mdl.dependencyJarNames) is being called with the factory as part of
the value...

mdlName key is "com.botanical.jpmml.decisiontreeensembleiris"

The next stop should be the RunAllModels where these factories are
exercised as appropriate according to the IsValidMessage replies from
each model factory.

After running the
$KAMANJA_SRCDIR/Pmml/JpmmlAdapter/src/main/resources/bin/JpmmlPushKafka.sh
$useCompressed $KAMANJA_SRCDIR/Pmml/JpmmlAdapter/src/main/resources/data/iris.csv

RunAllModels is *not called*.

JpmmlPushKafka.sh just does this:



if [[ $# -gt 1 ]]; then
        useCompressed="$1"
        shift
        dataFiles="$*"
        if [ "$useCompressed" == "1" ]; then
                compressedInput="true"
        else
                compressedInput="false"
        fi

        FORMAT="CSV"
        java -jar $KAMANJA_HOME/bin/SimpleKafkaProducer-0.1.0 --gz
"$compressedInput" --topics "testin_1" --threads 1 --topicpartitions 8
--brokerlist "localhost:9092" --files "$dataFiles" --partitionkeyidxs
"1" --format $FORMAT
else
        echo
        echo "Push data files through Kafka Input Adapter.  Supply a
flag indicating if the data is compressed or not followed by "
        echo "an arbitrary number of input paths to be pushed through
the input adapter."
        echo
        echo "Note: all files currently assumed to be CSV format."
        echo
        echo "Usage:"
        echo "   JpmmlPushKafka.sh <compressedInputFlag {0|1}
<filepath1> [<filepath2 <filepath3> ... <filepathN>]"
        echo
fi

**Comment by ligadata-rich** [comment]
I am using the hash map as my db.  Is that wrong now?

**Comment by ligadata-rich** [comment]
Pokuri, I think we should talk about this if you have some time.  I am going to break for an hour for dinner... maybe we can talk 8-9:30 time?

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
