### ISSUE TITLE
kamanja remove model requires user select model twice

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#912]
When I run the command
```
kamanja remove model
```
I am given a menu
```
Pick the model to be deleted from the following list:
[1] com.botanical.pmml.decisiontreeiris.000000000000000001
Enter your choice:
```
Upon selecting the model that same menu appears again, prompting me to select the model again, after which it removes the model properly.

**Comment by ligadata-rich** [comment]
I suggest we stop using the menus

**Comment by ligadata-william** [comment]
verified as fixed. closing.
