### ISSUE TITLE
Kamanja help does not display updated commands for kpmml and pmml

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#914]
The commands for pmml in kamanja help need to be changed to kpmml and new pmml commands showing examples of the new pmml support need to be added.

**Comment by ligadata-rich** [comment]
@ligadata-william, is thei the Help.txt file that is installed in the input folder of the install directory?

**Comment by ligadata-william** [comment]
verified as fixed. Closing.
