### ISSUE TITLE
kamanja deactivate model ModelName doesn't return proper APIResult with error

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#915]
When I run the command
```
kamanja deactivate model MyModel
```
without specifying the namespace and version (e.g. com.ligadata.models.HelloWorld.000000000001000000) the error I receive is
```
Result: [Ljava.lang.StackTraceElement;@116a2108
```
What should be displayed is an APIResult containing a message indicating the proper input required to retrieve a model.

**Comment by ligadata-dan** [comment]
@ligadata-william 
P1???

**Comment by ligadata-william** [comment]
This makes it difficult to determine what the user did wrong, thereby
spending more time in support to explain the issue. We can mark this as a
p2 since it doesn't break anything but kamanja help and documentation do
little to explain the proper usage.

**Comment by ligadata-dan** [comment]
don't matter, seems like a very simple fix - famous last words!

**Comment by ligadata-william** [comment]
Verified fixed. Closing.
