### ISSUE TITLE
Documentation is needed for the correct password property name  that is used by MetadataAPIService

### ISSUE THREAD

**Issue by ligadata-ahmad** [ligaDATA/Kamanja#925]
In this section http://kamanja.org/advanced-developers-guide/security/setting-ssl-certificate/

the correct password property is "SSL_PASSWD" . 
That needs to be configured in MetadataAPIConfig.properties
For example :

SSL_CERTIFICATE=/opt/kamanja/config/keystore.jks
SSL_PASSWD=pass123

**Comment by ligadata-alison** [comment]
Hi Ahmad,
     When I run the command:

     *keytool -genkey -keyalg RSA -alias selfsigned -keystore keystore.jks
-storepass password -validity 360 -keysize 2048*

*the -storepass password indicates the passord is "password". Correct?*

*So the correct definition is:*

*SSL_PASSWD=password*

*correct?*
*thanks,*
*alison*

**Comment by ligadata-ahmad** [comment]
Hi Alison , 

Hi Alison,

The command is correct .
After running that command it will ask to enter a password .
after that we need to set whatever password we typed in the previous command inside  MetadataAPIConfig.properties , The property name in that file is  "SSL_PASSWD"

**Comment by ligadata-alison** [comment]
Hi Ahmad,
     Please verify that I have the correct documentation:

http://kamanja.org/advanced-developers-guide/metadata-api/uploading-configurations/

thanks,
alison

**Comment by ligadata-alison** [comment]
Very sorry! Here's the correct link?

http://kamanja.org/administration-monitoring-2/updating-the-configuration-files/step-9-update-clustercfgmetadataapiconfig-properties/#Substep_5_Make_sure_you_have_valid_information_for_SSL_CERTIFICATE_and_SSL_PASSWD_if_required

**Comment by ligadata-alison** [comment]
Sorry again,
Here is the correct link:

http://kamanja.org/advanced-developers-guide/security/setting-ssl-certificate/

**Comment by ligadata-ahmad** [comment]
Verified. Thanks Alison.
