### ISSUE TITLE
failed to add kpmml model through RESTAPI 

### ISSUE THREAD

**Issue by ligadata-ahmad** [ligaDATA/Kamanja#930]
I am running the following  command .  PMML  API is being called instead of KPMML API

curl -X POST -d  "@/data/Ahmed/Test/kamanja/input/SampleApplications/metadata/model/KPMML_Model_HelloWorld.xml"  -k  https://localhost:8081/api/model  --header "Content-Type:application/json"

{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "One or more PMML arguments have not been specified... modelName = null, version = null, input = <!--  ~ Copyright 2015 ligaDATA  ~  ~ Licensed under the Apache License, Version 2.0 (the \"License\");  ~ you may not use this file except in compliance with the License.  ~ You may obtain a copy of t error = Failed to Add Model"
  }
}

**Comment by ligadata-pokuri** [comment]
Ahmed fixed it in 1.3.0 release with pull request #931

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
