### ISSUE TITLE
Uplead Modelconfig using RESTAPI need to be documented 

### ISSUE THREAD

**Issue by ligadata-ahmad** [ligaDATA/Kamanja#932]
To Upload ModelConfig we need to call this URL  https://yourHost/api/UploadModelConfig

**Comment by ligadata-alison** [comment]
Hi Ahmad,
    Can we talk about this? Right now, I only have the following:

http://kamanja.org/advanced-developers-guide/metadata-api/uploading-configurations/

Maybe you can show me where in the documentation I should put:

https://yourHost/api/UploadModelConfig
<https://yourhost/api/UploadModelConfig>

thanks,
alison

**Comment by ligadata-alison** [comment]
Hi Ahmad,
  Please verify that I have documented UploadModelConfig correctly and close if correct:

http://kamanja.org/advanced-developers-guide/metadata-api/uploading-configurations/

thanks,
alison

**Comment by ligadata-ahmad** [comment]
Verified . Thanks @ligadata-alison
