### ISSUE TITLE
kamanja stop fails on linux

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#938]
In the kamanja script, we use
```
ps -ef | grep -i java | grep -i KamanjaManager-1.0 | tr -s " " | cut -d" " -f3
```
to retrieve the process id. This works fine in OS X but fails in linux distributions. f3 should be changed to f2, which works in both.

**Comment by ligadata-pokuri** [comment]
Hi william,

I think we already fixed it. Can you check it once again and close it, if it is already fixed

**Comment by ligadata-william** [comment]
This is working for me. Closing.
