### ISSUE TITLE
Verify quick install - directory structure 

### ISSUE THREAD

**Issue by ligadata-greg** [ligaDATA/Kamanja#948]
Alison,

In this doc location:
http://kamanja.org/qs/#Step_7_Verify_your_Kamanja_Directory_Structure
Step 7: Verify your Kamanja Directory Structure

Bug:  the first line of the screenshot can never be correct.  The "installKamanja" is not an actual directory created by Homebrew or another installation process - it would never show up on a screenshot.  

I provided some replacement screen shots, attached.  I suggest the one with the Unix command line.  Please obscure my name in the screen shot, in the command prompts, for the docs (or maybe just retype or cut and paste, using only the $ Unix prompt).  This screen shot is specific to a Homebrew installation.  To provide an option, I attached a second screen shot, but it may be to wide of a screen to show, although it is more graphical like the  existing screen shot.  A third option is to just cut off the first line of the existing screen shot.

After discussion with William, the recommended text is:
--------------------------------------
Step 7: Verify your Kamanja Directory Structure

If you install Kamanja from Homebrew, the default path includes the software version, like:
/usr/local/Cellar/kamanja/1.3.1/

If you install Kamanja from binaries, the install location will be where you choose to untar the files to (but the version, like 1.3.1, is not part of the path)

![screen shot 2016-02-08 at 1 30 20 pm](https://cloud.githubusercontent.com/assets/10408766/12900173/e060a590-ce69-11e5-96bf-ecb584792789.png)

![screen shot 2016-02-08 at 1 28 42 pm](https://cloud.githubusercontent.com/assets/10408766/12900193/f1bafc32-ce69-11e5-8952-01d7b06ff9b4.png)

**Comment by ligadata-alison** [comment]
Hi Greg,
    I fixed the picture and added your text. Please verify http://kamanja.org/qs/#Step_7_Verify_your_Kamanja_Directory_Structure

thanks
alison

**Comment by ligadata-greg** [comment]
Thanks!!!
