### ISSUE TITLE
suggestion:  document  $kamanja help    in a table

### ISSUE THREAD

**Issue by ligadata-greg** [LigaData/Kamanja#949]
Hello,
As a suggestion in the documentation, when you type the following line at the command line, the output is so long.  Perhaps the documentation could create some kind of table to help keep things more clear.
$ kamanja help

When using search in the documentation for "kamanja help", I never came up with what appeard to be b documentation on this help message, or on what every line meant.

I attached a possible example table.  You may want to re-arrange commands in columns.  

[Kamanja command notes.xlsx](https://github.com/ligaDATA/Kamanja/files/122268/Kamanja.command.notes.xlsx)

**Comment by ligadata-greg** [comment]
http://kamanja.org/kamanja-commands/

**Comment by ligadata-alison** [comment]
Hi Greg,
    I put the kamanja-commands webpage and the CLI next to each other in the text.

With Kamanja v1.1, we are introducing utility commands to help you through installing, configuring, and running Kamanja. For a complete list of commands, see here. If you would like to see the possible Kamanja commands on the command-line, use:

kamanja help

Does this help? I did this for each of the samples.

**Comment by ligadata-greg** [comment]
Your additions are helpful - thanks.

going through the docs from quick start to running examples, this is the first time specific terms like "message", "container" and so on are used.   Can you define them, give an example, describe how they are used?   Or provide a link from those words to their definitions?   Use your judgement.

as a tech person, I can guess what a message is in general, but I would not guess that it is the "input record structure, with the field names and types".

**Comment by ligadata-alison** [comment]
Good idea - we do have a glossary so it would be a good idea when the user sees a word for the first time, I add a link to the glossary definition. I'll work on that and run it by you when I'm done.

**Comment by ligadata-alison** [comment]
For the:

http://kamanja.org/qs/run-samples/

page, I added links to the glossary for messages and metadata

and then on each sample, I added a link for container and model.

Are there other concepts that come to mind?

**Comment by ligadata-greg** [comment]
I didn't see the paragraph above at the link above.  It sounds good to add in the top.

Can you provide a summary table at the top, before kamanja help, with links to the glossery to define what can be defined?  Perhaps add text like:

The kamanja commands affect these metadata objects.  Click on one of the objects below to see the glossary definition:
* adapter
* cluster
* concept
* config
* container
* engine
* function
* message
* model
* node
* type

(please add the second sentence to the definition of message).
http://kamanja.org/glossary-1-1-rc1/#M
message – A structure that provides design-time definitions of incoming data and interfaces that makes it easy for Kamanja to process it in the flow at run-time.  Simply put, the message defines the record structure, with field names and types in the order the fields appear.

**Comment by ligadata-alison** [comment]
Hi Greg, I'm missing 4 definitions. Would you please provide me a single sentence for each of the following terms?

adapter - ?
cluster - ?
engine - ?
node - ?

**Comment by ligadata-greg** [comment]
adapter - Adapters are plugins that allow Kamanja to communicate data with
external, 3rd party systems.  We have two general types of adapters:  1)
input / output adapters for reading and writing messages (i.e. record
structures) with systems like Kafka or MQ.  2) storage adapters for talking
to for saving data, such as hashmap, HBase, Cassandra or SQL Server.

cluster (in a Kamanja context) - When installing and configuring Kamanja, a
group of Kamanja nodes working together on the same task.  Typically,
clusters would not overlap.  A cluster may be composed of one or more
nodes/engines.

cluster (in a data mining context) - When discussing data mining
algorithms, a cluster analysis is a type of unsupervised learning which
groups records together which have similar attributes or fields.  A cluster
center would be the average over the records for that cluster, for each
field used to define the cluster.  For example, if "the data" was the X, Y
position of points on a barn door, and you had fired a shotgun 3 times at
the barn door - hopefully a cluster analysis would group the pellets from
each of the the three shots as a different cluster (depending on the amount
of overlap).

engine (or node) - an instance of Kamanja (specifically the Kamanja
manager).  With respect to Kamanja, the terms "node" and "engine" are used
interchangeably.

node (or engine) - an instance of Kamanja (specifically the Kamanja
manager).  With respect to Kamanja, the terms "node" and "engine" are used
interchangeably.

**Comment by ligadata-alison** [comment]
wow - thank you Greg!

Please take a look at:

http://kamanja.org/qs/run-samples/finance/

Are things improving?

**Comment by ligadata-greg** [comment]
yes - THANKS

**Comment by ligadata-pokuri** [comment]
@ligadata-william, can you verify this?

**Comment by ligadata-william** [comment]
Verified and closing.
