### ISSUE TITLE
doc: set environment variables permanently, like KAMANJA_HOME

### ISSUE THREAD

**Issue by ligadata-greg** [LigaData/Kamanja#952]
I would suggest during the quick install, to explain how to setup any needed environment variables.  The environment variable below is assuming a Brew install.  If you untarred Kamanja to a different location, make the appropriate path changes.

---------------------
Use a Unix editor, such as vi or nano, to add this line to your .profile file, save and exit the editor.  The following source command loads the defined environment variable in that command shell.

$ nano ~/.profile
export KAMANJA_HOME=/usr/local/Cellar/kamanja/1.3.1/

$ source ~/.profile

**Comment by ligadata-greg** [comment]
export KAMANJA_HOME=/usr/local/Cellar/kamanja/1.3.1/
export ZOOKEEPER_HOME=/usr/local/Cellar/usr/local/Cellar/zookeeper/3.4.7/
export KAFKA_HOME=/usr/local/Cellar/kafka/0.8.2.2/

**Comment by ligadata-greg** [comment]
Feature request (not doc suggestion, but a feature request for the Kamanja install process):

during the install process, add to the  ~/.profile file or create the file to have the above three lines.

**Comment by ligadata-greg** [comment]
correction, I accidentally duplicated part of the Zookeeper path.  The correction is:
export ZOOKEEPER_HOME=/usr/local/Cellar/zookeeper/3.4.7/

**Comment by ligadata-alison** [comment]
Hi Greg,
     I have a:

http://kamanja.org/qs/homebrew/kamanja-installation-instructions/kamanja-with-all/double-check-bash_profile/

http://kamanja.org/qs/homebrew/kamanja-installation-instructions/kamanja-with-kafka/double-check-bash_profile/

etc

for Homebrew

and binaries:
http://kamanja.org/qs/working-binaries/double-check-bash_profile/

Are these sufficient?

**Comment by ligadata-greg** [comment]
answer:  yes, those links are sufficient.  

It was not clear to me that as part of a minimal install, I had to click on the section headings.  I expect them to be formatted differently anyways (even if not clickable).  

request:  Please be more explicit.  For example, at this link, add the text below (clicking on each step name)

http://kamanja.org/qs/homebrew/kamanja-installation-instructions/kamanja-with-all/

These are all the installation steps. Click Start to start the steps. Follow each step in order (clicking on the step name). You will find the Next button at the bottom of each page.

Please generalize this to other areas of the documentation, where clicking on the section headings is a required link with more directions to follow.  Assume people are reading quickly to get through setup to get to fun stuff.

**Comment by ligadata-alison** [comment]
Hi Greg,
    I think you have a critical point and I can't figure out how to solve it. How can I get the readers to step through the installation of all these other components when they are in a hurry to get through quick start?
    Would it help to have the following line?

http://kamanja.org/qs/homebrew/kamanja-installation-instructions/kamanja-with-all/

Alternatively, you can click on each step name below.  <==

I want the readers to either click on "Start" and go through each step OR go through step by step, clicking on the blue link.

Is this more clear? What do you think? Help, help. :)

**Comment by ligadata-greg** [comment]
yes, this is fine to be more explicit on clicking on the links

"Alternatively, you can click on each step name below."

**Comment by ligadata-pokuri** [comment]
@ligadata-william, can you verify this?

**Comment by ligadata-william** [comment]
Verified and closing.
