### ISSUE TITLE
doc / examples / use the clean up utility

### ISSUE THREAD

**Issue by ligadata-greg** [ligaDATA/Kamanja#953]
Hello,
The examples, such as
http://kamanja.org/qs/run-samples/telecom/

go through a lot of very manual (and potientially off-putting) detailed steps for cleanup, needed before starting to run the first example.   William said there was a clean utility that does this (and would help give a much better first impression of our product).  Please change the doc to remove the old way, and use the mentioned utility.

http://kamanja.org/administration-monitoring-2/cleanutil-1-0/

NOTE: the doc for the clean utility depends on having $KAMANJA_HOME defined.  See my other git bug report on defining this variable in .profile

$ cat ~/.profile
export KAMANJA_HOME=/usr/local/Cellar/kamanja/1.3.1/

**Comment by ligadata-alison** [comment]
Fixed in 1.3.1:

http://kamanja.org/qs/run-samples/helloworld/
http://kamanja.org/qs/run-samples/medical/
http://kamanja.org/qs/run-samples/telecom/
http://kamanja.org/qs/run-samples/finance/

Please verify
