### ISSUE TITLE
doc / examples / add a section heading between cleanup & starting the system

### ISSUE THREAD

**Issue by ligadata-greg** [ligaDATA/Kamanja#954]
Alison,
In the examples, like the Telecom, section 1 is very long.
http://kamanja.org/qs/run-samples/telecom/

I would suggest you break it up into sub-sections
1.1 Clean up any previous runs
Talk about the clean up tool here  (optionally, cover the manual detailed process)
State this step can be skipped if the user just installed Kamanja.

1.2.  Start Kamanja and needed services (where "Now get the servers back up and running") below

sudo rm -r *

Enter your computer password if you are prompted for a password.

Note: After removing the Kafka logs, you need to clear the Kamanja metadata.

To remove the metadata, run the following commands:

cd $KAMANJA_HOME

and then:

rm storage/*

For example:

cd /usr/local/Cellar/kamanja/1.2

rm storage/*

**Now get the servers back up and running.**

Type:

cd $ZOOKEEPER_HOME/bin

./zkServer.sh start

You should see something such as:

JMX enabled by default
Using config: /usr/local/etc/zookeeper/zoo.cfg
Starting zookeeper ... STARTED
Type:

cd $KAFKA_HOME/bin

**Comment by ligadata-alison** [comment]
Fixed in 1.3.1:

http://kamanja.org/qs/run-samples/helloworld/
http://kamanja.org/qs/run-samples/medical/
http://kamanja.org/qs/run-samples/telecom/
http://kamanja.org/qs/run-samples/finance/

Please verify
