### ISSUE TITLE
doc / examples zkServer does not have a *.sh for Homebrew install

### ISSUE THREAD

**Issue by ligadata-greg** [ligaDATA/Kamanja#955]
Alison,
The docs below are valid for a normal Linux install, but things are different when using Homebrew to install on a Mac.  William stated that Homebrew creates links that do not have the file name extensions, so the following directions do not work.  Some how, either with some document branching or footnoting, check all examples.  Check for other shell commands in the doc, the same issue will exist broadly, on Kamanja, Kafka or Zookeeper (if I understand the issue correctly).

IF (homebrew was used to install) then remove the *.sh from the script commands
  zkServer
  kafka-server-start
ELSE IF (Linux or other install) then use commands with the *.sh extension
  zkServer.sh
  kafka-server-start.sh
END IF

http://kamanja.org/qs/run-samples/telecom/

Type:

cd $ZOOKEEPER_HOME/bin

./zkServer.sh start

You should see something such as:

JMX enabled by default
Using config: /usr/local/etc/zookeeper/zoo.cfg
Starting zookeeper ... STARTED
Type:

cd $KAFKA_HOME/bin

./kafka-server-start.sh <Kafka install directory>/server.properties

For example:

kafka-server-start.sh /usr/local/etc/kafka/server.properties

You should see something such as:

**Comment by ligadata-greg** [comment]
aarrrrggg..    The kafka scripts to have a *.sh and so do the Kamanja scripts.

I guess it is just zookeeper

**Comment by ligadata-alison** [comment]
I like this:

IF (homebrew was used to install) then remove the *.sh from the script commands
zkServer
kafka-server-start
ELSE IF (Linux or other install) then use commands with the *.sh extension
zkServer.sh
kafka-server-start.sh
END IF

but I have a question. Do you mean

ELSE IF (binary install) then use commands with the *.sh extension?

**Comment by ligadata-greg** [comment]
William,
Can you comment on when the *.sh appears and does not appear?

I assume *.sh appears by default for all other installs, including binary.
The exception is a Homebrew install, where *.sh does not appear for some
commands.

Greg

**Comment by ligadata-dhaval** [comment]
Hi,

If kafka is installed via homebrew, it create a softlink to the $PATH and
we can run the following commands from any location:

kafka-server-start.sh /usr/local/etc/kafka/server.properties


Similarly for zookeeper, we run the command zkServer start from any
location.


We can find the information by running the command- brew info
kafka/zookeeper.

Best Regards,
Dhaval Kolapkar
Platform Engineer Intern | LigaDATA
