### ISSUE TITLE
doc / examples / kamanja create queues

### ISSUE THREAD

**Issue by ligadata-greg** [ligaDATA/Kamanja#956]
Alison,
In this doc link:
http://kamanja.org/qs/run-samples/telecom/

This section heading is also a unix commend, but the command is not correct.
2. bash $KAMANJA_HOME/bin/kamanja create queues

----------------------------
Suggestion (keeping your descriptive text), but change the section heading and command
2. Run a Kamanja script to create default Kafka queues

$ cd $KAMANJA_HOME/bin
$ ./CreateQueues.sh 
Created topic "testin_1".
Created topic "testout_1".
Created topic "teststatus_1".
Created topic "testfailedevents_1".
$

**Comment by ligadata-alison** [comment]
Fixed in 1.3.1:

http://kamanja.org/qs/run-samples/helloworld/
http://kamanja.org/qs/run-samples/medical/
http://kamanja.org/qs/run-samples/telecom/
http://kamanja.org/qs/run-samples/finance/

Please verify
