### ISSUE TITLE
doc / examples / make first listing of examples clickable

### ISSUE THREAD

**Issue by ligadata-greg** [ligaDATA/Kamanja#958]
Can you make these first examples clickable links?  It is not intuitive to think to scroll down to get to the clickable linke

http://kamanja.org/qs/run-samples/

We are going to implement 4 use cases (samples). They are:

HelloWorld – This use case demonstrates the basic functionality of Kamanja.
Medical – This use case simulates a diagnostic tool that helps you to discover those patients who are at risk for COPD.
Telecom – This use case helps you find out when you have used your cell phone beyond the number of minutes that are allowed each month.
Finance – This use case lets you know when your account balance is too low.

**Comment by ligadata-alison** [comment]
Hi Greg,
     I updated http://kamanja.org/qs/run-samples/ according to your feedback. Please verify.
thanks,
alison

**Comment by ligadata-greg** [comment]
verified.
