### ISSUE TITLE
doc / examples / kamanja upload compile config - not needed for PMML

### ISSUE THREAD

**Issue by ligadata-greg** [ligaDATA/Kamanja#959]
The step 5, below, is only needed if Java or Scala code is being added as part of the "model".  When adding PMML only, this step can be skipped.  Please note this at the beginning of this part of the samples, or when discussing "upload compile config" in general.

http://kamanja.org/qs/run-samples/telecom/

5. bash $KAMANJA_HOME/bin/kamanja upload compile config
This command uploads a ​model​ configuration file in the form of a JSON file to Kamanja. The model configuration is used to specify the dependencies, messages, and containers that the model needs to run successfully in Kamanja. Here is an example of the model configuration file called SubscriberUsageAlertCompileCfg_Telecom.json:

**Comment by ligadata-greg** [comment]
in the following, step 6, this is only for adding Java, NOT for adding PMML.  Please remove mention of PMML and remove mention of Scala.  There is one command per language type.

kamanja add model java
kamanja add model scala
kamanja add model pmml

6. bash $KAMANJA_HOME/bin/kamanja add model java
This command uploads a ​Java model. Models are small programming constructs written in Java, Scala, or PMML to control the input ingestion, make decisions, and produce output for different use-cases. Multiple models can be compiled into single executable jar, configured and deployed on a cluster for better performance.

**Comment by ligadata-greg** [comment]
for details on the PMML, see the following.  Note, I added the "\" at the end of the line as a continuation, so I could cut and paste from my editor to Unix, so it is pasted as one long line before being executed.

------------------------------------------------
Now add the PMML model.  The first line is an example.  The second line is used for this model.  The last shows the end of the logging to the screen, indicating the model was added successfully.

$ kamanja add model pmml /path/to/yourmodel.pmml 
    MODELNAME com.botanical.jpmml.DecisionTreeEnsembleIris 
    MODELVERSION 000000.000001.000001 
    MESSAGENAME System.IrisMsg

$ kamanja add model pmml  \ /usr/local/Cellar/Kamanja/1.3.1/input/SampleApplications/metadata/model/AutoMPG.xml  \
    MODELNAME com.ligadata.pmml.DecisionTreeAutoMPG  \
    MODELVERSION 000000.000001.000001                \
    MESSAGENAME com.ligadata.kamanja.samples.messages.msg1
:
    "Result Description" : "Model Added Successfully:com.ligadata.pmml.decisiontreeautompg.000000000001000001"

**Comment by ligadata-alison** [comment]
Hi Greg,
     I fixed steps 5 and 6 in all the samples. Please verify.  About the "add the PMML model" issue, I'm not sure where to add it. Does it go in the HelloWord, Medical, Telecom, or Finance sample? Or is this an entirely new sample?

**Comment by ligadata-greg** [comment]
I am working on examples now for PMML.  

No, there would not be any "add the PMML model" in any of the current examples unless they have a PMML (or *.xml) file.
