### ISSUE TITLE
doc / examples / sections should be English, not computer commands

### ISSUE THREAD

**Issue by ligadata-greg** [ligaDATA/Kamanja#960]
http://kamanja.org/qs/run-samples/telecom/

For the examples, after section 2, all the sections titles are Unix commands.  I would suggest that the section titles be clear to a person who does not yet know the Unix commands, and be a descriptive English phrase.

Also, the sections usually start for a few lines, do some commands before any overview on motivation - what are we doing and why in the bigger picture.  Please start each section with that.  Please don't launch directly into commands without context.

**Comment by ligadata-alison** [comment]
Fixed in 1.3.1:

http://kamanja.org/qs/run-samples/helloworld/
http://kamanja.org/qs/run-samples/medical/
http://kamanja.org/qs/run-samples/telecom/
http://kamanja.org/qs/run-samples/finance/

Please verify

**Comment by ligadata-greg** [comment]
thank you, thank you!
this helps with "user friendly"

(I don't like being told what to do "just because", I appreciate "why" and context)
