### ISSUE TITLE
easyInstallKamanja should take scala version as an optional argument

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#964]
When running easyInstallKamanja.sh, there are two installations that occur, one for 2.10.4 and one for 2.11.7. In the event that a user wants to run this script to build from source, they would only be interested in the scala version they currently have installed. As such, they should be able to pass in their scala version as an optional argument. If no argument is given, scala 2.10.x should be the default since that is what sbt defaults to.

**Comment by ligadata-dhaval** [comment]
Also, from discussion with Haitham, what I understand is that if I have
scala 2.11.7 installed and I run the easyinstall script, 2 binaries
corresponding to 2.10.4 and 2.11.7 will be generated. However, the scala
2.10.4 related binary, in this case, won't be compiled properly(as I have
scala 2.11.7 installed on my system) and may have issues running it.

Please correct me if I am wrong on this.

Thank you.

Regards,
Dhaval Kolapkar

Best Regards,
Dhaval Kolapkar
Platform Engineer Intern | LigaDATA

**Comment by ligadata-pokuri** [comment]
Rich changed easyInstall script in his branch. We will fix this in 1.4.0, worst it will go to 1.5

**Comment by ligadata-haitham** [comment]
this issue has been solved.
now we have easyInstallKamanjaExperimental.sh that takes scalaVersion as an argument.

**Comment by ligadata-pokuri** [comment]
let william verify it and close it

**Comment by ligadata-pokuri** [comment]
@ligadata-saleh can you verify this?

**Comment by ligadata-saleh** [comment]
easyInstallKamanjaExperimental.sh take the scala version as a paramter and work fine .  

verfied  .

Thanks
Saleh
