### ISSUE TITLE
kamanja script shebang needs to be the first line in kamanja

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#965]
Currently, we have the license at the top of the kamanja script, then the shebang below it, which is causing errors in some cases where a user runs as root.

**Comment by ligadata-pokuri** [comment]
All script should have shebang as the first line.

**Comment by ligadata-saleh** [comment]
adding missing Shebang to some scripts and make sure they are all in top  , please verify

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
