### ISSUE TITLE
Subscruber Usage model (Telecom) and COPD Risk Assessment model (Medical) produce no output

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#966]
Found in branch 1.3.2.Test, neither the subscriber usage model nor the COPD Risk Assessment model (java/scala or kpmml) are producing output anymore. For COPD it depends on a date/time sent with the messages and some of the dates are too old and need to be updated to within a year (preferably 6 months or less).

I don't know yet why subscriber usage isn't producing output.

**Comment by ligadata-pokuri** [comment]
Hi william,

Can you check this? As far as I remember this is related to data dates for COPD and I don't remember the Finance example. Can you check it in 1.4.0? We should fix this in 1.4.0. if there is any issue with model or sample data.

**Comment by ligadata-pokuri** [comment]
@ligadata-saleh can you verify this?

**Comment by ligadata-pokuri** [comment]
@ligadata-yasser can you verify this?

**Comment by ligadata-yasser** [comment]
Medical is verified so far

**Comment by ligadata-pokuri** [comment]
@ligadata-ramana can you check why telecom is not producing any result

**Comment by ligadata-pokuri** [comment]
Verified Telecom.
