### ISSUE TITLE
clusterInstallerDriver options fromKamanja, fromScala and migrateTemplate should be optional

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#970]
fromKamanja, fromScala and migrateTemplate options need to be optional. In the event that this is a fresh install, there should be no need for these values.

**Comment by ligadata-pokuri** [comment]
William,
This is fixed in latest version
Can you check this with latest Installer.

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
