### ISSUE TITLE
Requesting for unused Pre Requisites

### ISSUE THREAD

**Issue by ligadata-pokuri** [LigaData/Kamanja#974]
At this moment we are checking for Kafka, HBase & Zookeeper with empty hostlist, even though ClusterConfig.json does not have it.

Solution:
  Request only if they are available in ClusterConfig.json

**Comment by ligadata-pokuri** [comment]
Workaround:
For now use --skipPrerequisites  with the components we want to skip.

**Comment by ligadata-pokuri** [comment]
@ligadata-william , can you verify it once>

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
