### ISSUE TITLE
AuditRecord def toJson has unhandle NumberFormatException when AuditRecord.actionTime is not in a pre-defined format

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#976]
Currently, AuditRecord.actionTime is defined as a String. When toJson is called, if that string is not in the exact format "yyyy-MM-dd hh:mm:ss", an unhandled NumberFormatException occurs. If we want a DateTime object in the toJson method, then actionTime needs to be a DateTime instead of a String.

**Comment by ligadata-ashish** [comment]
@ligadata-ramana please work on the fix

**Comment by ligadata-ramana** [comment]
Even though We have defined AuditRecord.actionTime as a String, The MetadataAPI.addAuditRecord populates Long value of Datetime as a String. So AuditRecord.actionTime is acutally a long value of Datetime when the audit record was created. Unable to reproduce NumberFormatException as long as we use our API functions addAuditRecord and getAuditRecord. Created a new Scala Test Component TestAuditAPISpec.scala to reproduce the problem.

**Comment by ligadata-ramana** [comment]
A pull request #1408 created.

**Comment by ligadata-william** [comment]
I'm currently unable to verify this using the unit test. There seems to be an issue with the setup for the MetadataAPI tests. See #1408 for details.

I'll take a quick look and see if I can fix it in short order.

**Comment by ligadata-ramana** [comment]
A new pull request #1444 has been created. The issues related to MetadataAPI Unit Test specs are addressed.

**Comment by ligadata-william** [comment]
Verified. Closing.
