### ISSUE TITLE
AuditRecord defs don't have protection against NullPointerException

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#977]
The class AuditRecord, rather than passing in values at time of construction, requires a person to set them after. If a variable isn't set, that variable defaults to null and any use of that variable or of the defs toJson or toString will result in an unhandle NullPointerException.

**Comment by ligadata-yousef** [comment]
pull request ID : #1152

**Comment by ligadata-william** [comment]
The changes in the pull request are not enough to protect against a NullPointerException. There is nothing keeping me from changing any of the empty strings to null and then calling toJson. def toJson itself needs to have a try/catch to check for null and, at the very least, throw a KamanjaException indicating that the variables cannot be null.

**Comment by ligadata-yousef** [comment]
Please verify.
pull request ID : #1152

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
