### ISSUE TITLE
MetadataAPI test setup fails when compiled in scala 2.10

### ISSUE THREAD

**Issue by ligadata-william** [LigaData/Kamanja#979]
Test setup is failing when compiled in 2.10 when attempting to copy jars. This is happening because in object ConfigDefaults, private val RootDir is set to "./MetadataAPI/target/scala-2.11/test-classes". This directory assumes the scala version is 2.11.

The line
```
private val RootDir = "./MetadataAPI/target/scala-2.11/test-classes"
```
needs to be changed to
```
private val RootDir = getClass.getResource("/").getPath
```
This will alow it to refer to it's own resources directory as the root directory which will automatically conver to target/scala-2.10 or target/scala-2.11 depending on the version being used to compile.

**Comment by ligadata-william** [comment]
Apparently when we use getClass.getResource as a means of determining target location for jars, it somehow manages to corrupt the jars on copy, causing errors during metadata compilation. Not sure why, looks like some manner of scala error. Next best way I've found for this is:
```
val scalaVersionFull = scala.util.Properties.versionNumberString
  val scalaVersion = scalaVersionFull.substring(0, scalaVersionFull.lastIndexOf('.'))

  private val RootDir = s"./MetadataAPI/target/scala-$scalaVersion/test-classes"
```

**Comment by ligadata-pokuri** [comment]
william, can you verify this once again whether we still have this issue or not? I am lowering the priority for this. If we still have issue we will take care of this next release.

**Comment by ligadata-william** [comment]
Issues with running the tests themselves but the setup is ok. Closing.
