### ISSUE TITLE
PmmlTestTool does not handle models that use a sub set of the columns in the dataset

### ISSUE THREAD

**Issue by ligadata-rich** [LigaData/Kamanja#989]
Bill tried to use a pmml model that used 4 of the 15 fields available in the incoming dataset.  The argument check was incorrect.  It makes the assumption that all fields must be consumed.   The Set.difference below was the issue.  It has been replaced with Set.intersection and validating the length of the intersection result matches the length of the input fields from the model:

```
    if (inputRecords.size() > 0) {
        Map<FieldName, ?> inputRecord = inputRecords.get(0);

        Sets.SetView<FieldName> missingActiveFields = Sets.difference(new LinkedHashSet<>(activeFields), inputRecord.keySet());
        Sets.SetView<FieldName> requiredFields = Sets.intersection(new LinkedHashSet<>(activeFields), inputRecord.keySet());
        boolean allFieldsAvailable = (requiredFields.size() == activeFields.size());
        if (! allFieldsAvailable) {
            throw new IllegalArgumentException("One or more of the model's input fields is missing: " + activeFields.toString());
        }
        /*if (missingActiveFields.size() > 0) {   this is wrong... doesn't account for fields in input that are not used by the model
            throw new IllegalArgumentException("Missing active field(s): " + missingActiveFields.toString());
        }*/

        Sets.SetView<FieldName> missingGroupFields = Sets.difference(new LinkedHashSet<>(groupFields), inputRecord.keySet());
        if (missingGroupFields.size() > 0) {
            throw new IllegalArgumentException("Missing group field(s): " + missingGroupFields.toString());
        }
    }
```

**Comment by ligadata-rich** [comment]
Bill found another issue with the PmmlTestTool.  Most (perhaps all) of the PMML src provider tools will put double quotes around the column names.  This makes the sanity check as to whether the fields mentioned in the model are present in the dataset produce 0 fields on the set intersection of the two (e.g., field "ID" in the model and ""ID"" in the column header line 0 of the dataset.

These quotes are now stripped.

**Comment by ligadata-pokuri** [comment]
Rich,

Did you already fixed this and given to Bill or still need to fix something in this area? 

And also is it really P0?

**Comment by ligadata-rich** [comment]
As far as I am concerned, it is a production bug.  These guys are trying to write models.  I put this in the Issue989 branch.  I suggest we merge it.  I think there is a pull request.

**Comment by ligadata-pokuri** [comment]
William, merge if we have any pending changes related to this into 1.4.0 and we need to verify this in 1.4.0. 

And also make sure the same model is working in Kamanja platform too (if there is issue in tool, there may be issue in Kamanja Platform also. We need to make sure we fixed in both places)

**Comment by ligadata-pokuri** [comment]
If you need any help, talk with Bill & Rich

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
