### ISSUE TITLE
PMML model commands need precise details in Advanced Developer's Guide

### ISSUE THREAD

**Issue by DataBillB** [LigaData/Kamanja#993]
There are several PMML model commands in the Kamanja Advanced Developer's Guide.There are necessary details that need to be document, otherwise the commands will fail, without giving enough information to allow the user to correct the command line.

One of these necessary details is the structure of the value of the MODELNAME portion of the command.  The detail is that this MUST have both a "namespace" and a "model name" part, separated by a period, as in "abc.xyz".  In this example, "abc" is the namespace and "xyz" is the model name.  These should be meaningful text, as they will identify the model in any lists of active models - but in reality they can be ANY text - although it would be wise NOT to include spaces.

It would also be helpful to the reader to list the options on separate lines in a fashion that still creates a valid "copy and paste" command, for example:
sudo kamanja add model pmml \
   <path-to-file>/AutoMPG_rpart_FromGregsVideos_PMML.xml \
   MODELNAME Rattle.PMML \
   MODELVERSION 1.4  \
   MESSAGENAME com.ligadata.kamanja.samples.messages.msg1 \
   MESSAGEVERSION 00.01.00

**Comment by ligadata-alison** [comment]
Hi Bill,
     Thank you for your suggestions. I will get approval from the developer of this section and let you know once  I have updated it.
thanks,
alison

**Comment by ligadata-rich** [comment]
From http://kamanja.org/advanced-developers-guide/models/#Adding_a_PMML_Model , this is the current text for add model :

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add model pmml <SomePath>/DecisionTreeAuto.pmml MODELNAME com.auto.pmml.DecisionTreeAuto MODELVERSION 000000.000001.000001 MESSAGENAME System.AutoMsg

In the example, an add model command is invoked. The command is followed by several name/value pairs. Its version must also be supplied. When treated as a Long integer, its value must be greater than any other version for models with this name. The PMML model text is supplied in the pmml value, namely $KAMANJA_SRCDIR/Pmml/JpmmlAdapter/src/main/resources/metadata/model/Rattle/DecisionTreeAuto.pmml. Note that the leading 0’s are not required, but used here to illustrate the maximum size that the Long version could take (when ‘.’ are eliminated).

Notice that the command (after the Kamanja configuration file) is enclosed in single quotes. This prevents bash from interpreting the parentheses slashes in unsavory ways.
--------------------------------

The last paragraph should be eliminated.  That is a hold over from the prior mechanism.  I missed that during my (sloppy) review.  On the other hand, there really is a "copy/paste" command here in the bold text.

As shown, but perhaps not well explained, the model name is shown to consist of a package name (com.auto.pmml) with a simple model name (DecisionTreeAuto) connected with a '.'.  This is not unlike the syntax used in Java and Scala to express a full package qualified class name.  Perhaps what is missing in the documentation is that there is no general explanation about our use of names for identifying metadata objects.

ALL Kamanja metadata objects (messages, containers, models, functions, types, concepts.... everything) are identified with a namespace.name.  Virtually every kamanja script command that ingests/changes/removes these objects uses a namespace.name (possibly with version) to effect its action on the right object(s).

The standard named parameter notation in unfortunately not used in these kamanja commands.  It is a bit confusing I think.  At some point this will be redone so you will see commands something like this:

$KAMANJA_HOME/bin/kamanja --apiConfig $KAMANJA_HOME/config/MetadataAPIConfig.properties add model --pmml <SomePath>/DecisionTreeAuto.pmml --modelName com.auto.pmml.DecisionTreeAuto --modelVersion 000000.000001.000001--messageName  System.AutoMsg

That's more inline with how named parameters are used in a *nix world.

---------------------------------

So what needs to be done?

- let's add some explanation of our metadata names (if it is not there already) in a section that describes metadata perhaps, or perhaps in the kamanja command introduction.
- I am not sure anything needs to be done on page http://kamanja.org/advanced-developers-guide/models/#Adding_a_PMML_Model .
- the kamanja command help... I think there is a file there that one can peruse that describes the commands.  OTOH, a  command like "kamanja" should have help support.  For example,

      kamanja --help (this would dump general info about what commands are available with what help command to use to gain specific information about a given command... e.g.,..

      kamanja --help add pmml (would describe the details about the command illustrated above).

**Comment by ligadata-alison** [comment]
Hi Bill,
     I have added your note to:

http://kamanja.org/advanced-developers-guide/models/

Please take a look and verify.

Also, I put the options on separate lines. Please verify.

Let me know if you find other problems with the documentation. I very much
appreciate your input.
thanks,
alison

**Comment by DataBillB** [comment]
Hi,
Well there are some changes needed.
First, in the command itself, each line (except the last) should end with a
space and a backslash, and all except the first line can be indented for
readability.  This will still be copy-and-paste friendly.  Like this:






*$KAMANJA_HOME/bin/kamanja \
$KAMANJA_HOME/config/MetadataAPIConfig.properties \    add model pmml
<SomePath>/DecisionTreeAuto.pmml \    MODELNAME
com.auto.pmml.DecisionTreeAuto \    MODELVERSION 000000.000001.000001  \
MESSAGENAME System.AutoMsg  \*


Then the following paragraph should be removed.  Rich has pointed out that
it is a holdover from the past and is no longer valid.

"Notice that the command (after the Kamanja configuration file) is enclosed
in single quotes. This prevents bash from interpreting the parentheses
slashes in unsavory ways."

Thanks!


On Tue, Mar 22, 2016 at 12:24 PM, ligadata-alison <notifications@github.com>
wrote:

> Hi Bill,
> I have added your note to:
>
> http://kamanja.org/advanced-developers-guide/models/
>
> Please take a look and verify.
>
> Also, I put the options on separate lines. Please verify.
>
> Let me know if you find other problems with the documentation. I very much
> appreciate your input.
> thanks,
> alison
>
> On Thu, Mar 17, 2016 at 6:10 PM, DataBillB <notifications@github.com>
> wrote:
>
> > There are several PMML model commands in the Kamanja Advanced Developer's
> > Guide.There are necessary details that need to be document, otherwise the
> > commands will fail, without giving enough information to allow the user
> to
> > correct the command line.
> >
> > One of these necessary details is the structure of the value of the
> > MODELNAME portion of the command. The detail is that this MUST have both
> a
> > "namespace" and a "model name" part, separated by a period, as in "
> abc.xyz".
> > In this example, "abc" is the namespace and "xyz" is the model name.
> These
> > should be meaningful text, as they will identify the model in any lists
> of
> > active models - but in reality they can be ANY text - although it would
> be
> > wise NOT to include spaces.
> >
> > It would also be helpful to the reader to list the options on separate
> > lines in a fashion that still creates a valid "copy and paste" command,
> for
> > example:
> > sudo kamanja add model pmml \
> > /AutoMPG_rpart_FromGregsVideos_PMML.xml \
> > MODELNAME Rattle.PMML \
> > MODELVERSION 1.4 \
> > MESSAGENAME com.ligadata.kamanja.samples.messages.msg1 \
> > MESSAGEVERSION 00.01.00
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ligaDATA/Kamanja/issues/993>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-199973943>
>



-- 
Bill Bruns
LigaData

**Comment by ligadata-alison** [comment]
OK - the text has been updated - please verify. Thank you for your detailed
review!

**Comment by DataBillB** [comment]
Hi, it appears that what I am sending is not reaching you with the proper
formatting.
Somehow the text I send is getting messed up.
The result is that the command format under the "ADD" option is messed up.
What it should look like is that each line should END with the " \" (space
and backslash, but the email system is causing problems for us, because the
lines are all running together in the "ADD" case, instead of being on
separate lines.

One other issue is that the last line of the group should NOT have a "\" at
the end.

Thank you for your efforts and your patience with these tricky details!

On Wed, Mar 23, 2016 at 10:35 AM, ligadata-alison <notifications@github.com>
wrote:

> OK - the text has been updated - please verify. Thank you for your detailed
> review!
>
> On Tue, Mar 22, 2016 at 4:44 PM, DataBillB <notifications@github.com>
> wrote:
>
> > Hi,
> > Well there are some changes needed.
> > First, in the command itself, each line (except the last) should end
> with a
> > space and a backslash, and all except the first line can be indented for
> > readability. This will still be copy-and-paste friendly. Like this:
> >
> >
> >
> >
> >
> >
> > *$KAMANJA_HOME/bin/kamanja \
> > $KAMANJA_HOME/config/MetadataAPIConfig.properties \ add model pmml
> > <SomePath>/DecisionTreeAuto.pmml \ MODELNAME
> > com.auto.pmml.DecisionTreeAuto \ MODELVERSION 000000.000001.000001 \
> > MESSAGENAME System.AutoMsg \*
>
> >
> >
> > Then the following paragraph should be removed. Rich has pointed out that
> > it is a holdover from the past and is no longer valid.
> >
> > "Notice that the command (after the Kamanja configuration file) is
> enclosed
> > in single quotes. This prevents bash from interpreting the parentheses
> > slashes in unsavory ways."
> >
> > Thanks!
> >
> >
> > On Tue, Mar 22, 2016 at 12:24 PM, ligadata-alison <
> > notifications@github.com>
> > wrote:
> >
> > > Hi Bill,
> > > I have added your note to:
> > >
> > > http://kamanja.org/advanced-developers-guide/models/
> > >
> > > Please take a look and verify.
> > >
> > > Also, I put the options on separate lines. Please verify.
> > >
> > > Let me know if you find other problems with the documentation. I very
> > much
> > > appreciate your input.
> > > thanks,
> > > alison
> > >
> > > On Thu, Mar 17, 2016 at 6:10 PM, DataBillB <notifications@github.com>
> > > wrote:
> > >
> > > > There are several PMML model commands in the Kamanja Advanced
> > Developer's
> > > > Guide.There are necessary details that need to be document, otherwise
> > the
> > > > commands will fail, without giving enough information to allow the
> user
> > > to
> > > > correct the command line.
> > > >
> > > > One of these necessary details is the structure of the value of the
> > > > MODELNAME portion of the command. The detail is that this MUST have
> > both
> > > a
> > > > "namespace" and a "model name" part, separated by a period, as in "
> > > abc.xyz".
> > > > In this example, "abc" is the namespace and "xyz" is the model name.
> > > These
> > > > should be meaningful text, as they will identify the model in any
> lists
> > > of
> > > > active models - but in reality they can be ANY text - although it
> would
> > > be
> > > > wise NOT to include spaces.
> > > >
> > > > It would also be helpful to the reader to list the options on
> separate
> > > > lines in a fashion that still creates a valid "copy and paste"
> command,
> > > for
> > > > example:
> > > > sudo kamanja add model pmml \
> > > > /AutoMPG_rpart_FromGregsVideos_PMML.xml \
> > > > MODELNAME Rattle.PMML \
> > > > MODELVERSION 1.4 \
> > > > MESSAGENAME com.ligadata.kamanja.samples.messages.msg1 \
> > > > MESSAGEVERSION 00.01.00
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/ligaDATA/Kamanja/issues/993>
> > > >
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-199973943
> >
> > >
> >
> >
> >
> > --
> > Bill Bruns
> > LigaData
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-200081616>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-200457759>
>



-- 
Bill Bruns
LigaData

**Comment by ligadata-alison** [comment]
We will prevail. :) How does it look now?

**Comment by DataBillB** [comment]
Hello, yes, that looks more correct!

But in the UPDATE PMML section the line
*update model pmml <SomePath>/DecisionTreeAuto.pmmlDecisionTreeAuto.pmml \*

*has some repetition that is not meant to be there.  And the *
*"<SomePath>" should be in the ADD PMML section too.*
*I cannot at this point evaluate the DELETE PMML section.*

On Wed, Mar 23, 2016 at 3:06 PM, ligadata-alison <notifications@github.com>
wrote:

> We will prevail. :) How does it look now?
>
>
> On Wed, Mar 23, 2016 at 2:51 PM, DataBillB <notifications@github.com>
> wrote:
>
> > Hi, it appears that what I am sending is not reaching you with the proper
> > formatting.
> > Somehow the text I send is getting messed up.
> > The result is that the command format under the "ADD" option is messed
> up.
> > What it should look like is that each line should END with the " \"
> (space
> > and backslash, but the email system is causing problems for us, because
> the
> > lines are all running together in the "ADD" case, instead of being on
> > separate lines.
> >
> > One other issue is that the last line of the group should NOT have a "\"
> at
> > the end.
> >
> > Thank you for your efforts and your patience with these tricky details!
> >
> > On Wed, Mar 23, 2016 at 10:35 AM, ligadata-alison <
> > notifications@github.com>
> > wrote:
> >
> >
> > > OK - the text has been updated - please verify. Thank you for your
> > detailed
> > > review!
> > >
> > > On Tue, Mar 22, 2016 at 4:44 PM, DataBillB <notifications@github.com>
> > > wrote:
> > >
> > > > Hi,
> > > > Well there are some changes needed.
> > > > First, in the command itself, each line (except the last) should end
> > > with a
> > > > space and a backslash, and all except the first line can be indented
> > for
> > > > readability. This will still be copy-and-paste friendly. Like this:
> > > >
> > > >
> > > >
> > > >
> > > >
> > > >
> > > > *$KAMANJA_HOME/bin/kamanja \
> > > > $KAMANJA_HOME/config/MetadataAPIConfig.properties \ add model pmml
> > > > <SomePath>/DecisionTreeAuto.pmml \ MODELNAME
> > > > com.auto.pmml.DecisionTreeAuto \ MODELVERSION 000000.000001.000001 \
> > > > MESSAGENAME System.AutoMsg \*
> > >
> > > >
> > > >
> > > > Then the following paragraph should be removed. Rich has pointed out
> > that
> > > > it is a holdover from the past and is no longer valid.
> > > >
> > > > "Notice that the command (after the Kamanja configuration file) is
> > > enclosed
> > > > in single quotes. This prevents bash from interpreting the
> parentheses
> > > > slashes in unsavory ways."
> > > >
> > > > Thanks!
> > > >
> > > >
> > > > On Tue, Mar 22, 2016 at 12:24 PM, ligadata-alison <
> > > > notifications@github.com>
> > > > wrote:
> > > >
> > > > > Hi Bill,
> > > > > I have added your note to:
> > > > >
> > > > > http://kamanja.org/advanced-developers-guide/models/
> > > > >
> > > > > Please take a look and verify.
> > > > >
> > > > > Also, I put the options on separate lines. Please verify.
> > > > >
> > > > > Let me know if you find other problems with the documentation. I
> very
> > > > much
> > > > > appreciate your input.
> > > > > thanks,
> > > > > alison
> > > > >
> > > > > On Thu, Mar 17, 2016 at 6:10 PM, DataBillB <
> notifications@github.com
> > >
> > > > > wrote:
> > > > >
> > > > > > There are several PMML model commands in the Kamanja Advanced
> > > > Developer's
> > > > > > Guide.There are necessary details that need to be document,
> > otherwise
> > > > the
> > > > > > commands will fail, without giving enough information to allow
> the
> > > user
> > > > > to
> > > > > > correct the command line.
> > > > > >
> > > > > > One of these necessary details is the structure of the value of
> the
> > > > > > MODELNAME portion of the command. The detail is that this MUST
> have
> > > > both
> > > > > a
> > > > > > "namespace" and a "model name" part, separated by a period, as
> in "
> > > > > abc.xyz".
> > > > > > In this example, "abc" is the namespace and "xyz" is the model
> > name.
> > > > > These
> > > > > > should be meaningful text, as they will identify the model in any
> > > lists
> > > > > of
> > > > > > active models - but in reality they can be ANY text - although it
> > > would
> > > > > be
> > > > > > wise NOT to include spaces.
> > > > > >
> > > > > > It would also be helpful to the reader to list the options on
> > > separate
> > > > > > lines in a fashion that still creates a valid "copy and paste"
> > > command,
> > > > > for
> > > > > > example:
> > > > > > sudo kamanja add model pmml \
> > > > > > /AutoMPG_rpart_FromGregsVideos_PMML.xml \
> > > > > > MODELNAME Rattle.PMML \
> > > > > > MODELVERSION 1.4 \
> > > > > > MESSAGENAME com.ligadata.kamanja.samples.messages.msg1 \
> > > > > > MESSAGEVERSION 00.01.00
> > > > > >
> > > > > > —
> > > > > > You are receiving this because you are subscribed to this thread.
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <https://github.com/ligaDATA/Kamanja/issues/993>
> > > > > >
> > > > >
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-199973943
> > > >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Bill Bruns
> > > > LigaData
> > > >
> > > > —
> > > > You are receiving this because you were assigned.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-200081616
> > >
> > >
> > > >
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-200457759
> >
> > >
> >
> >
> >
> > --
> > Bill Bruns
> > LigaData
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-200557099>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ligaDATA/Kamanja/issues/993#issuecomment-200563332>
>



-- 
Bill Bruns
LigaData

**Comment by ligadata-alison** [comment]
OK I updated it and await your DELETE PMML review - thanks Bill!

**Comment by ligadata-alison** [comment]
Fixed

**Comment by ligadata-alison** [comment]
Bill cannot verify so this issue remains closed.
