### ISSUE TITLE
In Quick Start, add instruction to copy Zookeeper config file

### ISSUE THREAD

**Issue by DataBillB** [ligaDATA/Kamanja#995]
Zookeeper will not start after an install from binaries, unless the sample zookeeper config file is copied to zoo.cfg.

When downloading from binaries, the Quick Start guide does not tell the user to copy the zookeeper sample configuration file.  This instruction is explicitly given in another part of the documentation at
http://kamanja.org/administration-monitoring-2/starting-zookeeper-and-hbase-servers/
but not in the QuickStart/Binaries brach.

**Comment by ligadata-alison** [comment]
I have added the documentation to the Working with Binaries section. Please verify

**Comment by DataBillB** [comment]
Yes, verified in the Quick Start guide at
http://kamanja.org/qs/working-binaries/install-zookeeper/

Nothing more needed.

On Mon, Mar 21, 2016 at 6:50 PM, ligadata-alison <notifications@github.com>
wrote:

> I have added the documentation to the Working with Binaries section.
> Please verify
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ligaDATA/Kamanja/issues/995#issuecomment-199580659>
>



-- 
Bill Bruns
LigaData
