### ISSUE TITLE
Update message does not return a valid json

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#998]
Update message returns this:
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddMessageDef",
    "Result Data" : null,
    "Result Description" : "Message Added Successfully:com.ligadata.kamanja.samples.messages.msg1.000000000002000000"
  }
}
RecompileModel results for com.ligadata.kamanja.samples.models.helloworldmodel.1
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "RemoveModel",
    "Result Data" : null,
    "Result Description" : "Deleted Model Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001"
  }
}{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000001"
  }
}

This is not a valid json format to parse.

**Comment by ligadata-ashish** [comment]
@ligadata-dhaval please fix

**Comment by ligadata-dhaval** [comment]
Part of the pull request #1423

**Comment by ligadata-william** [comment]
Testing this is blocked by #1434

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
