### ISSUE TITLE
Kamanja get all models does not return a json

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/Kamanja#999]
Kamanja get all models command returns only a string of model names. This does not go with the standardized json format of API result

**Comment by ligadata-ashish** [comment]
@ligadata-dhaval Good job raising it. We need to fix this and if you find more, please open issues.

**Comment by ligadata-dhaval** [comment]
Part of the pull request #1423

**Comment by ligadata-william** [comment]
Verified as fixed. Closing.
